### ISSUE TITLE
What is the difference between charge and payment when initiating payment?

### ISSUE THREAD

**Issue by justforjava** [stripe/stripe-java#1004]
When we initiate payment, the callback received is charge, but your demo here is the callback of payment, what is the difference between charge and payment?
Here is the link:https://stripe.com/docs/webhooks/signatures
Here is the screenshot:[question](https://github.com/justforjava/test_clong/blob/master/q1.png)

**Comment by remi-stripe** [comment]
@justforjava I'm going to close this ask as Github issues should be limited to bugs or feature requests with the library and not used for product support.

I recommend reaching out to our support team instead https://support.stripe.com/contact

To unblock you though, `PaymentIntent` is a newer API we shipped mi-2018. It allows you to better support all types of payment methods that could require an action from the customer. For example having to go through 3D Secure to confirm your card payment or approving a payment out of band for example with iDeal or Sofort.
This is documented here https://stripe.com/docs/payments/accept-a-payment

Charges is our legacy integration, though a `PaymentIntent` still creates a `Charge` object when it succeeds to make it easier to migrate.
