### ISSUE TITLE
Add missing invoicing field to Customer

### ISSUE THREAD

**Issue by Edubits** [stripe/stripe-java#1005]
The `invoicing` object is missing in Customer, so it seems it's only possible to add separate billing email addresses through the dashboard. It would be useful to be able to do this through the Java library as well.

Snippet from the API used by the dashboard:
```
POST /v1/customers/cus_CUSTOMER_ID

{
  "phone": "+312012345678",
  "invoicing": {
    "email_to": [
      "test@test.com"
    ],
    "email_cc": ""
  }
}
```

**Comment by remi-stripe** [comment]
@Edubits At the moment, this feature is only available in the Dashboard and it can not be used in the API. That's why it's not in the stripe-java library today. We're working on adding this to the API and when that happens it will be automatically added to stripe-java!

**Comment by j4ckofalltrades** [comment]
Any updates to when this will be added to the API?

**Comment by remi-stripe** [comment]
@j4ckofalltrades for now there are not plans to add this to the API in the short term unfortunately. I'd recommend registering your interest for that feature with our support team: https://support.stripe.com/contact

**Comment by yogen-darji-hs** [comment]
It will be great if we get API support for Customer billing details emails fields. Currently we are doing it manually from Dashboard if someone wants to use multiple CC emails in invoices.
