### ISSUE TITLE
Support for set up TransferGroup in the PaymentIntentData for Checkout

### ISSUE THREAD

**Issue by gianpaolodn** [stripe/stripe-java#1031]
Hi,

we have both integration in our website:

checkoutSession for web and mobile
standardFlow for ios/android.

In the standardFlow we can correctly set up the TransferGroup while creating the PaymentIntent.

Instead, while creating the checkout session for web, we have PaymentIntentData which is missing the transfer group: [https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data](doc)

And we are in need of this when we create the transfer to move all the paymentIntents to the connected account.

Moreover if we try to retrieve the PaymentIntent and update we have this error:

> "message": "Some of the parameters you provided (statement_descriptor, transfer_group) cannot be used when modifying a PaymentIntent that was created by Checkout. You can try again without those parameters."

We are using this API version:

API_VERSION = "2019-12-03";
VERSION = "17.11.0";

**Comment by remi-stripe** [comment]
@gianpaolodn at the moment, this is a limitation in the API itself and not stripe-java. The API doesn't yet support this feature. I'll flag this internally but I would encourage you to reach out to our support team to also raise this request: https://support.stripe.com/contact
