### ISSUE TITLE
Method subscriptionItem.getUsageRecords() is undefined

### ISSUE THREAD

**Issue by chandankumar4** [stripe/stripe-java#1045]
Reference API docs: https://stripe.com/docs/api/usage_records/create
Error:
![Screenshot from 2020-06-14 14-26-35](https://user-images.githubusercontent.com/28861964/84589299-2b45db00-ae4b-11ea-8fed-2efd24e22083.png)

Stripe version: `compile group: 'com.stripe', name: 'stripe-java', version: '19.23.0'`

Java version:
```bash
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

**Comment by remi-stripe** [comment]
@chandankumar4 Thanks for the report. The docs are incorrect and we'll get them fixed. Instead you should use `UsageRecord.createOnSubscriptionItem` which is defined in the library here: https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/UsageRecord.java#L72
