### ISSUE TITLE
Could FileCreateParams.Builder.setFile take InputStream?

### ISSUE THREAD

**Issue by totof3110** [stripe/stripe-java#1054]
The `com.stripe.param.FileCreateParams.Builder.setFile` method only accept an instance of either `java.io.File` or `java.io.FileInputStream`. Looking at `com.stripe.net.HttpContent.buildMultipartFormDataContent(Collection<KeyValuePair<String, Object>>, String)`, it seem like this param doesn't have to be a `FileInputStream` but could be just an `InputStream`. This would make it easier to upload files from the classpath in a JAR for example (which cannot be read as a file / file input stream).

**Comment by remi-stripe** [comment]
@totof3110 Thanks for the report! We'll look into whether this is something we can support in the future!

**Comment by richardm-stripe** [comment]
Fixed by #1180, released in [v20.38.0](https://github.com/stripe/stripe-java/blob/master/CHANGELOG.md#20380---2021-02-10)
