### ISSUE TITLE
Google Gson is not included with gradle dependency

### ISSUE THREAD

**Issue by RumbosN** [stripe/stripe-java#1063]
Hi,

I'm getting the next error when I try to do `ApiResource.GSON.fromJson(json, Event::class.java)`:
`Cannot access class 'com.google.gson.Gson'. Check your module classpath for missing or conflicting dependencies`

I'm using Java 11, gradle 6.3 and `implementation("com.stripe:stripe-java:19.31.0")`

I can solve this adding `implementation("com.google.code.gson:gson:2.8.5")` in my build.gradle but I think it is not the idea

**Comment by ob-stripe** [comment]
Hi @RumbosN, thanks for the report.

As it is, you are correct, you would need to declare a dependency on Gson in your own `build.gradle` file to use `ApiResource.GSON`.

While we could expose the transitive dependency on Gson, not doing so has several benefits for the majority of stripe-java users that do not need to use Gson directly (cf. https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation).

For webhook handlers specifically, we recommend that you use the `Webhook.constructEvent` method to validate webhook signatures and deserialize `Event` objects. You can find more information and a Java example at https://stripe.com/docs/webhooks/signatures.

**Comment by RumbosN** [comment]
Thank you @ob-stripe 

I'm using `Webhook.constructEvent` but in the example to check the signature you are catching `catch (JsonSyntaxException e)` and that is a exception from google.gson.

But I think this is ok, I can import `com.google.code.gson:gson:2.8.5`
