### ISSUE TITLE
instant_available property is missing in the Balance class

### ISSUE THREAD

**Issue by ta-shi** [stripe/stripe-java#1080]
I see instant_available property when I log the JSON (balance.toJson()) but instant_available property is missing in the stipe java SDK balance object.

I see balance.getPending() and balance.getAvailble() but not balance.getInstantAvailable();

**Comment by remi-stripe** [comment]
@ta-shi Thanks for reaching out about this and sorry for the trouble. This feature is pretty advanced and currently not directly covered in our API reference for the Balance object which is causing that discrepancy. I'm going to look into this internally to see if we can add support for it in the future and I'll circle back with more details though it will take a bit of time!

**Comment by remi-stripe** [comment]
@ta-shi I just released 20.8.0 which fixes this issue so if you upgrade you should be all set! Sorry again for the delays!

**Comment by ta-shi** [comment]
Wow!! Thanks for the update. @remi-stripe
