### ISSUE TITLE
Upgrade to 20.0.0 breaks Customer.getSources()

### ISSUE THREAD

**Issue by catchin** [stripe/stripe-java#1090]
Using:
* Kotlin version 1.4.0 on Java 11.
* Stripe Java library 20.0.0 (tried with 20.1.0 as well with same result).

Code similar to the following works with Stripe Java library 19.45.0, but breaks with 20.0.0:
`Customer.retrieve("some-customer-id").sources.autoPagingIterable()`
It throws a `NullPointerException` because the `sources` property is `null`. 
Can you check if you can reproduce this issue?

**Comment by remi-stripe** [comment]
@catchin Sorry for the trouble here. In the latest API version `sources` became includable and is not returned by default so for this to work you need to expand it. first We'll get our docs in the API reference updated soon but the code would look like this:

```
CustomerRetrieveParams params =
  CustomerRetrieveParams.builder()
    .addExpand("sources")
    .build();

Customer customer = Customer.retrieve("cus_123", params);
```

If you do this `getSources()` will work in that case. Can you confirm this solves your problem?

**Comment by catchin** [comment]
@remi-stripe Thank you for the hint. This (or something similar) really solves the problem. I had to add a third argument because a method with two matching arguments does not exist.

`Customer customer = Customer.retrieve("cus_123", params, null);`

Maybe it would be good to mention in the changelog that the API upgrade contains some breaking changes?

**Comment by remi-stripe** [comment]
I just updated the changelog in https://github.com/stripe/stripe-java/pull/1093 to make it easier to discover this. We also updated our API Reference examples.
