### ISSUE TITLE
Don't assume that a provided Map<String, String> is mutable

### ISSUE THREAD

**Issue by icoloma** [stripe/stripe-java#1091]
There are places in stripe-java where arguments are provided as a `Map`, and it modifies the map content. For example, in [OAuth.java:29](https://github.com/stripe/stripe-java/blob/ec82d87509fd04fad930ba9e0cee94a3ff633cca/src/main/java/com/stripe/net/OAuth.java#L29)

```Java
params.put("client_id", getClientId(params, options));
```

In general modifying objects provided as params to your API is not considered good form, as it makes this use case impossible:

```
OAuth.authorizeUrl(
  Map.of(
    "client_id", "foobar",
    "response_type", "code",
   // ... other parameters...
  ),
  url
)
```

In this example, `Map.of()` returns an immutable Map, which should be a valid parameter to pass to Stripe. Instead, the current implementation tries to `put()` and throws an Exception. 

A common workaround would be to use a forwarding map instead.

Java version: 1.11
stripe-java version: 19.35.0

**Comment by suz-stripe** [comment]
Hi @icoloma thanks for bringing this to our attention. I've gone ahead and patched the parts of the SDK that present this problem with using immutable Maps. We'll be releasing this change as a patch in the next release which should be going out today.

Thanks again and we hope this makes stripe-java a better experience for you!
