### ISSUE TITLE
Fail to retrieve promotional code

### ISSUE THREAD

**Issue by Kenji94** [stripe/stripe-java#1094]
Hi,

I'm at the last version 20.2.0.

When I try to get a promotional code with the id ('PKJCYXTO') and the api, it does not work. 
PromotionCode promotionCode = PromotionCode.retrieve("PKJCYXTO"); // NOT WORKING

However when I try to get the list of all the promotional codes with only the id ('PKJCYXTO') it works
    PromotionCodeListParams build = PromotionCodeListParams
        .builder()
        .setCode("PKJCYXTO")
        .build();
    PromotionCodeCollection list = PromotionCode.list(build); // WORKING

I found out that it works by using the id in the url of the stripe dashboard: promo_1HOjpaKaXlungdwLRBx63hEb
It's not really intuitive, could you do another way to retrieve it except doing it with the list please ?

**Comment by paulasjes-stripe** [comment]
Hi there, the issues page here should only be for problems with the stripe-java library specifically. If you have API level questions you're better off contacting support directly: https://support.stripe.com/contact

To unblock you however, Stripe doesn't currently support directly retrieving promotion codes by their user-facing `code` value. Instead you should look into saving the unique ID returned by stripe (e.g. promo_1HOjpaKaXlungdwLRBx63hEb) or using the list endpoint as you've found.
