### ISSUE TITLE
Request: Add ability to use different HTTP Clients with customization

### ISSUE THREAD

**Issue by benlei-gfm** [stripe/stripe-java#1097]
For example, I'm working on a Spring Boot project that primarily uses OkHttp v3. Additionally, the project uses logbook (https://github.com/zalando/logbook).

The end goal is to be able to create a Stripe client that can be integrated with OkHttp + Logbook so that it'll be easier to log requests/responses.

**Comment by richardm-stripe** [comment]
Support for using a custom HTTP client was added in [v17](https://github.com/stripe/stripe-java/pull/869) earlier this year: there is a little bit of documentation in the [migration guide](https://github.com/stripe/stripe-java/wiki/Migration-guide-for-v17#custom-http-clients), I hope that meets your needs. I'm closing the issue for now but if you find that inadequate please feel free to reopen.
