### ISSUE TITLE
getObject() of EventDataObjectDeserializer is not present.

### ISSUE THREAD

**Issue by surajgautam** [stripe/stripe-java#1108]
Hello there,

I am facing a weird issue. I have been using stripe-java version **19.40.0**. Today, I got an exception when I was trying to parse the payload received from Stripe webhooks. 

I have the piece of code that looks like:

     private StripeObject getStripeObject(Event event) {
        EventDataObjectDeserializer dataObjectDeserializer = event.getDataObjectDeserializer();
        StripeObject stripeObject = null;
        if (dataObjectDeserializer.getObject().isPresent()) {
            stripeObject = dataObjectDeserializer.getObject().get();
        } else {
            throw new RuntimeException("cannot serialize");
        }
        return stripeObject;
    }

It was working fine and suddenly it stopped working. The **payment_intent.succeeded** event is successfully received in my webhook endpoint but the flow enters the else block of the aforementioned code. 

When I upgraded the version to **20.7.0**, the same code works fine. 
P.S: I am using Java 8.

**Comment by remi-stripe** [comment]
@remi-stripe What is the API version associated with the event you are receiving? The fact that it works on 20.7.0 means that it's likely formatted based on the latest API version `2020-08-27` while on 19.X it expects a different API Version.

**Comment by surajgautam** [comment]
Yep, the version is 2020-08-27

**Comment by remi-stripe** [comment]
So that is the issue in that case. You are trying to parse an event that is formatted with a different API version than what the library expects/supports. You always need to make sure that your webhook endpoint is pinned to the exact same API version as the one the library supports.
