### ISSUE TITLE
Retrieve invoice API problem

### ISSUE THREAD

**Issue by ptahchiev** [stripe/stripe-java#1114]
Either your API is stupid, or I'm not using it in the right way. 
The API allows me to list all the invoices for a given user. Then I take this list (pagination doesn't seem to be supported) and I present it to the customer like this:
```
INVOICE_NUMBER_1 - INVOICE DATE - PDF LINK
INVOICE_NUMBER_2 - INVOICE DATE - PDF LINK
.......
INVOICE_NUMBER_N - INVOICE DATE - PDF LINK
```
Then the user clicks on `INVOICE_NUMBER_2` for example and I want to display to him the invoice information for INVOICE2 in a new screen. However the API does not allow me to retrieve invoice by `INVOICE_NUMBER` and USER. I can only retrieve by INVOICE_ID. But if this is my URL: `http://mysite.com/invoices/stripe_invoice_id` then people might guess `stripe_invoice_id` and get other people's invoices. 
The API must allow to retrieve invoices by `some criteria (stripe invoice id or invoice number)` + `customer`. Then I will provide the currently logged in customer as parameter and they will not be able to view other people's invoice.

**Comment by remi-stripe** [comment]
@ptahchiev Our API does not support retrieving an invoice by the number. You can only retrieve an invoice (or any of our object) via the invoice id instead, the `in_123`. So when you list invoices for a customer, you need to track that `in_123` is the one with number 1 and `in_abc` is the one with number 2 and then retrieve the invoice via the `in_` prefix. If you don't want to put the invoice id in the URL you can store that mapping in your database for example.

This is how our API works today and retrieving objects by arbitrary properties is not supported at the moment. There's also no point calling the API stupid here.

I'm going to close this out as it's not a bug with stripe-java but you can reach out to our support team for more questions.

**Comment by ptahchiev** [comment]
Yes, I understand all this, but then it really seems like a massive overkill to store information in the db just so that I would be able to call your API. Furthermore it's not me who doesn't want to use the `in_123` in the URL - it is a big security risk as I pointed out. And yes, stupid is not the right word (probably because english is not my native language). I think the right word would be `poorly designed`
