### ISSUE TITLE
Wrong invoice line item names when create subscription

### ISSUE THREAD

**Issue by altro3** [stripe/stripe-java#1132]
Hi! Could you add information about Plan to Invoice line items descriptions? 

For example now it works like that:

![изображение](https://user-images.githubusercontent.com/48474279/96219155-68b0a580-0fb0-11eb-92d0-427bc6df2a80.png)

As you see, in pricing block we can read product name and plan name, but in invoice - only product name. It would be nice if the tariff plan information was automatically added to the invoice, just like it is described in Pricing. Because customer don't understand why in some invoices he see different prices for same product, when he changed plan.

Also, your API does not provide an opportunity to customize the description of each line item when creating a subscription - just link each of them with an existing plan or product.  I mean, need something like this:
```java
        var items = new ArrayList<SubscriptionCreateParams.Item>();
        for (var tp : stripeInfo.getTariffPlans()) {
            items.add(SubscriptionCreateParams.Item.builder()
                    .setPlan(tp.getStripePlanId())
                    .setDescription("my custom description")  // <----- for customizing descriptioon, but default must bee <product_name> - <plan_name>
                    .build());
        }

```

Finally:

1. Please add the ability to customize the description of line items when creating a subscription

2. When creating subscriptions, please add the name of the plan in addition to the product name

**Comment by remi-stripe** [comment]
@altro3 Thanks for reaching out. Github issues should be limited to bugs with the library itself and this is more a product question about the API. We do not support setting your own custom description for line items associated with the subscription so it's not something we would add to the API.
I'd recommend reaching out to our support team instead and raising your interest for that feature instead: https://support.stripe.com/contact

**Comment by altro3** [comment]
@remi-stripe Thanks for the advice! :-) Sent a request to your support. I hope you will improve the invoice generator in the near future.
