### ISSUE TITLE
Invalid signature for webhook

### ISSUE THREAD

**Issue by deneb974** [stripe/stripe-java#1151]
Hello
I tried to code a webhook endpoint (i m using jaxrs/restEasy)
I use your com.stripe.net.Webhook class to check the signature 
And i always get an invalid signature

do i misunderstand  something find my code below

	public Response webhook(HttpServletRequest request) {
		String endpointSecret = "whsec_xxxx";
		String sigHeader = request.getHeader("Stripe-Signature");
		logger.info("Webhoook signature : "+sigHeader);

		String payload;
		StringBuilder out = new StringBuilder();

		try {
			payload = request.getReader().lines().collect(Collectors.joining());
			//logger.info("Webhook payload : "+ payload);
		} catch (IOException e1) {			
			return Response.status(400).build();
		}

		Event event = null;

		try {
			event = Webhook.constructEvent(out.toString(), sigHeader, endpointSecret);
		} catch (SignatureVerificationException e) {
			// Invalid signature
			logger.error("Webhook invalid signature... "+ e.getLocalizedMessage());
			logger.info("check signature manually");
		    event = ApiResource.GSON.fromJson(payload, Event.class);
		    try {
                               //call stripe-java
				Signature.verifyHeader(payload, sigHeader, endpointSecret, DEFAULT_TOLERANCE);
			} catch (SignatureVerificationException e1) {
				// Invalid signature
				logger.error("Webhook invalid signature return 400 to Stripe... "+ e.getLocalizedMessage());
				return Response.status(400).build();
			}
		}

		logger.info("Event received : \n"+
				event.toJson());

		switch (event.getType()) {
		case "checkout.session.completed":
			// Payment is successful and the subscription is created.
			// You should provision the subscription.
			break;
		case "invoice.paid":
			// Continue to provision the subscription as payments continue to be made.
			// Store the status in your database and check when a user accesses your service.
			// This approach helps you avoid hitting rate limits.
			break;
		case "invoice.payment_failed":
			// The payment failed or the customer does not have a valid payment method.
			// The subscription becomes past_due. Notify your customer and send them to the
			// customer portal to update their payment information.
			break;
		default:
			// System.out.println("Unhandled event type: " + event.getType());
		}

		return Response.ok().build();
	}

**Comment by remi-stripe** [comment]
@deneb974 For the signature verification to work, you need to get the exact raw payload that we sent to your webhook endpoint. Any change such as missing a space or a newline, or incorrect encoding can make the signature verification fail. With Java environments, it's really common that your code/framework modifies the raw payload, either to be helpful by pre-parsing it or by adding extra new lines or spaces. You also need to make sure that you read the data as UTF-8 and not any other encoding.

Unfortunately this is tricky to debug especially as it can be so specific to your own environment. What we recommend here is to dump the raw payload you are reading and make sure it matches what Stripe sends you, for example by confirming there are no new lines in the middle of the payload.

**Comment by deneb974** [comment]
Hi thank you for your answer and that s what i did suspect for my fisrt call Webhook.constructEvent

but on catch block i use your class https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/net/Webhook.java
Signature.verifyHeader to verify manually (this one recreate the signature right?

**Comment by remi-stripe** [comment]
@deneb974 It's possible though it's unclear what exact error you get and which line is throwing it in your code versus which one you reported in the issue. What's possible is that your framework is also tampering with the signatures header(s) and changing them incorrectly. We had someone else this week report that their framework is incorrectly adding spaces around each signature(s) value causing the parser to fail. Could it be something like this?

**Comment by deneb974** [comment]
i will check again thank you

**Comment by dcr-stripe** [comment]
Hi @deneb974 ,

I'll be closing this issue out to clean up our pending issues, but please feel free to re-open if you are still experiencing this issue so that we can get you unblocked.
