### ISSUE TITLE
Session object is return null for lineitems attribute

### ISSUE THREAD

**Issue by pdclouds** [stripe/stripe-java#1164]
We have identified an issue with the Java Library.

Below is a snippet of our code that is retrieving a "null" value for `line_items` from the Session object, via `checkout.session.completed` with webhook;

```
Session session = (Session) eventDataObjectDeserializer.getObject().get();
LineItemCollection lineItemCollection = session.getLineItems(); <-- this line is returning a null value
String productCode = lineItemCollection.getData().get(0).getPrice().getProduct();
Product product = Product.retrieve(productCode);
String description = product.getDescription();
```
Yet via a workaround we can obtain the information we are seeking with the following code snippet;
```
HttpHeaders headers = new HttpHeaders();
headers.add("Authorization", "Bearer " + stripeSecretKey);
String url = "https://api.stripe.com/v1/checkout/sessions/" + session.getId() + "/line_items";
HttpEntity request = new HttpEntity(headers);
ResponseEntity<String> response = new RestTemplate().exchange(url, HttpMethod.GET, request, String.class);
String rawJson = response.getBody();
JSONObject jsonObject = new JSONObject(rawJson);
JSONArray data = jsonObject.getJSONArray("data");
JSONObject item = data.getJSONObject(0);
JSONObject price = item.getJSONObject("price");
String productCode = price.getString("product");
Product product = Product.retrieve(productCode);
String description = product.getDescription();
```

Albeit that the workaround achieves the outcome we are seeking, the first code snippet is cleaner and legible for support team to follow.

We are using Java 1.8, Spring Boot 2.4 and Stripe-Java 20.30.0

Is there an issue with the Session Object in the stripe-java library? One would assume both options should return the same information?

Cheers

**Comment by remi-stripe** [comment]
@pdclouds The `line_items` collection is what we call "includable" which means it's not returned by default unless you explicitly ask for it. This is documented here: https://stripe.com/docs/expand#includable-properties

Since you're processing the `Event` here, it won't have `line_items` and you have to fetch the Session in the API instead after getting the event:

```
SessionRetrieveParams params =
  SessionRetrieveParams.builder()
    .addExpand("line_items")
    .build();

Session session = Session.retrieve("cs_test_KdjLtDPfAjT1gq374DMZ3rHmZ9OoSlGRhyz8yTypH76KpN4JXkQpD2G0", params, null);
```
