### ISSUE TITLE
Add preferred locales to CustomerCreateParams

### ISSUE THREAD

**Issue by funder7** [stripe/stripe-java#1172]
I'm creating a new Customer, by looking at the [API documentation, I saw the "preferred_locales" option](https://stripe.com/docs/api/customers/object#customer_object-preferred_locales).

Unfortunately even after updating to the latest version(20.35.0), it's still not possible to set the property.

Is it intentional or it's missing?

**Comment by remi-stripe** [comment]
@funder7 The `preferred_locales` parameter is supported in `CustomerCreateParams` and you can see it [here](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/param/CustomerCreateParams.java#L423) in the code.

To use it with typed parameters in stripe-java, your code would look like this:

```
CustomerCreateParams customerParams =
  CustomerCreateParams.builder()
    .setEmail("test@example.com")
    .addPreferredLocale("fr")
    .addPreferredLocale("en")
    .build();

Customer customer = Customer.create(customerParams);
```

**Comment by funder7** [comment]
Thank you very much @remi-stripe , my fault, I used auto-completion in many ways but I wasn't able to find it. Next time I will look in the source code!
