### ISSUE TITLE
Regarding ability to override stripe api url per API request

### ISSUE THREAD

**Issue by devansh-dalal** [stripe/stripe-java#1181]
Hi

We are using [stripe-mock](https://github.com/stripe/stripe-mock) for our e2e tests requiring stripe API calls. There we required to change the stripe api base url per request as:
```
public PaymentMethod createPaymentMethod(Card card) {
      var paymentMethodParams =
          PaymentMethodCreateParams.builder()
              .setType(Type.CARD)
              .setCard(
                  CardDetails.builder()
                      .setNumber(card.getNumber())
                      .setExpMonth((long) card.getExpiryMonth())
                      .setExpYear((long) card.getExpiryYear())
                      .setCvc(card.getCvv())
                      .build())
              .build();
      var response = testMode? "Make API call to mock stripe with params" : PaymentMethod.create(paymentMethodParams);
      return response;
  }
```

This could be done globally via static method as 
```
Stripe.overrideApiBase();
```

but this changes the url of stripe api globally, It could have been usable if I could have overridden the api url per request, maybe via `RequestOptions`. Please do let if know if there are any problems, this should be easy, or not?

**Comment by remi-stripe** [comment]
@devansh-dalal Thanks for the report! We'll track this internally but I think it will only happen once we ship support for the client/services infrastructure we're working on!

**Comment by richardm-stripe** [comment]
This was made possible in https://github.com/stripe/stripe-java/pull/1476 and was released in https://github.com/stripe/stripe-java/releases/tag/v22.5.0.
