### ISSUE TITLE
One time Coupon proration behavior!

### ISSUE THREAD

**Issue by wa3ziz** [stripe/stripe-java#1183]
When a one time coupon is applied on a subscription during its creation, any updates to this subscription during the first cycle will be result in proration calculation error. This error is two folds: 

1- The coupon is included in the new invoice of the updated subscription as: Unused time ton XX$ Coupon!! 
2- The calculated proration is Positive and its added to the invoice total amount. The user end up paying not only for what he bought, but also for a coupon that he used during the subscription creation. 

An example can be found on the attached receipts.

[Subscription_Update_Receipt.pdf](https://github.com/stripe/stripe-java/files/5968890/Subscription_Update_Receipt.pdf)
[Subscription_Cretion_Receipt.pdf](https://github.com/stripe/stripe-java/files/5968891/Subscription_Cretion_Receipt.pdf)

**Comment by remi-stripe** [comment]
@wa3ziz thanks a lot for reaching our about this. Flagging that Github issues are limited to bugs with the library itself so I'd recommend reaching out to our support team instead to discuss those product questions. You can contact them here: https://support.stripe.com/contact

Overall though the flow you describe is expected with the way proration works on our end. If you want the coupon to apply to the upgrade you have to pass it during the subscription upgrade. Today we do not prorate only the quantity increase. We refund the original amount (prorated for time used) and then charge the total for the new quantity (prorated for time left). IF you have any follow up questions our support team will be able to help!
