### ISSUE TITLE
Ability to wipe test data from API

### ISSUE THREAD

**Issue by arvindkgs** [stripe/stripe-java#1223]
During E2E I setup a testbed on a test Stripe account to test integration with Stripe. It would be useful to have ability to wipe all data to ensure the next run is successful. I see that Stripe UI Dashboard has ability to wipe all test data.

An API to do the same would be very helpful.

**Comment by remi-stripe** [comment]
@arvindkgs It's not something we have an API for today and we don't plan to build this in the near future at least. We're looking at better improvements for Test mode instead such as the ability to spin up temporary test environments on demand and delete them at the end. No firm timeline just yet but definitely top of mind for us.

I'm going to close this as github issues should be limited with bugs with the library itself, I hope it's okay!
