### ISSUE TITLE
Webhook.constructEvent(payload, sigHeader, stripeEndpointSecret) is failure

### ISSUE THREAD

**Issue by zhaoxinhu** [stripe/stripe-java#1234]
`@RequestMapping("/stripe/notify")
    @ResponseBody
    public Object test(@RequestBody String payload, HttpServletRequest servletRequest, HttpServletResponse response) throws IOException {
        String sigHeader = servletRequest.getHeader("Stripe-Signature");
        Event event = null;
        log.info("stripe异步通知payload为：{}", payload);
        log.info("stripe异步通知内容Stripe-Signature为：{}", sigHeader);
        try {
            event = Webhook.constructEvent(payload, sigHeader, stripeEndpointSecret);
        } catch (JsonSyntaxException e) {
            e.printStackTrace();
            // Invalid payload
            response.setStatus(400);
            return "JsonSyntaxException";
        } catch (SignatureVerificationException e) {
            ExceptionUtil.printStackTrace(log, e);
            response.setStatus(400);
            return "SignatureVerificationException";
        }
}`

Webhook.constructEvent(payload, sigHeader, stripeEndpointSecret) throw a SignatureVerificationException

**Comment by jacques-slice** [comment]
Is this happening all the time, or only some of the time if all of the time:
- you may want to make sure you are using the right endpoint secret value (value is different if you use stripe client than what is in the webhook config in Stirpe dashboard).
- make sure the payload was read with `UTF-8`.

If this happens only from time to time, as a test, try to make you method (that calls `Webhook.constructEvent`) `synchronized`; noticed that the `Webhook.constructEvent` is mostly all static and when two events are sent almost at the same time, each request will be processed on a separate thread and most likely corrupt the data in the `Webhook.constructEvent`...
