### ISSUE TITLE
Webhook.constructEvent(payload, sigHeader, stripeEndpointSecret)" throw a SignatureVerificationException

### ISSUE THREAD

**Issue by zhaoxinhu** [stripe/stripe-java#1235]
![jietu](https://user-images.githubusercontent.com/34291938/125270446-43cd4100-e33c-11eb-81b6-09db982eb79d.png)

"event = Webhook.constructEvent(payload, sigHeader, stripeEndpointSecret)" throw a SignatureVerificationException

**Comment by zhaoxinhu** [comment]
Stripe SDK version is 20.62.0. We webhook version is 2020-08-27

**Comment by remi-stripe** [comment]
@zhaoxinhu Github issues should be limited to bugs with the library itself. Your question is more a support question about your own code, please contact our support team directly: https://support.stripe.com/contact/email
