### ISSUE TITLE
Missing account_requirement in com.stripe.param.FileCreateParams.Purpose enum

### ISSUE THREAD

**Issue by sardortaylakov** [stripe/stripe-java#1258]
Hi, we are trying to create a file to provide company registration verification during account update. Per this [doc](https://stripe.com/docs/api/files/create#create_file-purpose), we need to set purpose as `account_requirement` when creating a file. However, there is no such enum in `com.stripe.param.FileCreateParams.Purpose`. Please advise.

**Comment by remi-stripe** [comment]
@sardortaylakov Thanks for the report and sorry about the trouble. The majority of our library is automatically generated from our openapi spec but a handful of classes are still maintained by hand and the File APIs parameter classes are manual and we forgot to add this. I opened a PR and we'll hopefully merge this soon!
