### ISSUE TITLE
Listing All PaymentMethods attached to a Customer not Supported

### ISSUE THREAD

**Issue by rishabnayak** [stripe/stripe-java#1308]
getPaymentMethods isn't defined for the Customer object - essentially preventing [this](https://stripe.com/docs/api/payment_methods/customer_list) API call from being made.

Java 17, Stripe Java Library Version 20.95.0

**Comment by remi-stripe** [comment]
@rishabnayak Thanks for the report and sorry for the confusion. I'll get the docs fixed but in the meantime you want this instead:

```
PaymentMethodListParams params =
  PaymentMethodListParams.builder()
    .setCustomer("cus_L0XyjD6h4CZ2ze")
    .setType(PaymentMethodListParams.Type.CARD)
    .build();

PaymentMethodCollection paymentMethods = PaymentMethod.list(params);  
```
