### ISSUE TITLE
Server-Side Setup Intent Confirmation with 3DS returns redirect_to_url response that returns an error

### ISSUE THREAD

**Issue by rishabnayak** [stripe/stripe-java#1309]
<img width="1436" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/31130737/152479617-f211a4f8-fca4-424c-8598-f823f1114334.png">

**Comment by remi-stripe** [comment]
@rishabnayak Github issues should be limited to bugs with the library itself. This is more an integration support question and you should work with our support team and provide a lot more context (PaymentIntent id, request id, redirect url, etc.) directly to them. You can contact them here: https://support.stripe.com/contact
