### ISSUE TITLE
NPE in Invoice.setDiscounts()

### ISSUE THREAD

**Issue by damien-swarm** [stripe/stripe-java#1316]
https://github.com/stripe/stripe-java/blob/a6633f9b27e1efd1e310bde02a054868d8b935b1/src/main/java/com/stripe/model/Invoice.java#L690

In this line, if `this.discounts == null`, it'll throw an NPE. (I'm running into this because we use Jackson for JSON, and when deserializing an Invoice object with Jackson, I see an NPE being thrown here.)

For now I'll include gson as a dependency just to deserialize this, I guess?

**Comment by dcr-stripe** [comment]
Thanks for the report @damien-swarm - great catch!

I'll put together a PR for catching this.

**Comment by dcr-stripe** [comment]
This is fixed and will go out with the next stripe-java release. Thanks again for the report!

**Comment by damien-swarm** [comment]
Thanks for fixing this bug!
