### ISSUE TITLE
applies_to returning null for coupons

### ISSUE THREAD

**Issue by carterjfulcher** [stripe/stripe-java#1317]
If you create a coupon from the Stripe Dashboard that applies only to a specific product and then go to reference it via the API, the applies_to field of the coupon is `null`. The code is very simple:

```kotlin
Coupon coupon = Coupon.retrieve(couponId);
System.out.println(coupon.getAppliesTo());
```
yet yields: 
```
null
```
Despite having an AppliesTo Product in the dashboard:
 
![Screen Shot 2022-03-01 at 11 36 57 AM](https://user-images.githubusercontent.com/23005868/156228639-d1795b5f-e30b-4f97-bded-2e029e50f054.png)

**Comment by yejia-stripe** [comment]
The `applies_to` field is not returned by default. To include it in the response, [expand](https://stripe.com/docs/api/expanding_objects) the `applies_to` field (noted in the [API reference](https://stripe.com/docs/api/coupons/object?lang=java#coupon_object-applies_to), but not the doc comment, sorry!)

**Comment by carterjfulcher** [comment]
> The `applies_to` field is not returned by default. To include it in the response, [expand](https://stripe.com/docs/api/expanding_objects) the `applies_to` field (noted in the [API reference](https://stripe.com/docs/api/coupons/object?lang=java#coupon_object-applies_to), but not the doc comment, sorry!)

Ah, I see now. Thanks!
