### ISSUE TITLE
Deleted customer data errors can not be avoided

### ISSUE THREAD

**Issue by eurozulu** [stripe/stripe-java#1325]
When an object is deleted, such as a customer, despite the docs claiming that object can be retrieved, there is no means to retrieve it without having the original id.
This causes a problem when creating / updating other customers and data clashes with the deleted customer (e.g. invoicePrefix)

If the new customer has the same prefix as a deleted customer there is no way of checking if that prefix is already in use so the only solution is to keep attempting it until no error occurs, a far from satisfactory solution.

Would be nice to be able to hard delete customers not linked to any other object in the test data but at the very least needs a means of searching deleted users for data they are using so as to avoid clashing with new/updated customers without relying on errors as feedback.

**Comment by remi-stripe** [comment]
@eurozulu Thanks for the report! Github issues are limited to bugs with the library itself. Your ask is more an improvement of our API which is something you should report to our support team instead: https://support.stripe.com/contact

To give you some pointers though, this is definitely a limitation we've heard of. An alternative would be to "clear" the prefix after a deletion but this can cause real issues with businesses who want to guarantee those prefixes are always unique. As for allowing to retrieve a deleted customer, this goes against the spirit of customer deletion which is to remove most of the data from the API. Even if you can still retrieve that customer, you don't get any of the information in the response for a deleted customer. I do agree that it makes it tricky for the invoice prefix especially. My recommendation is to not use the Delete Customers API if you can avoid it in your integration, it's more an edge-case than a recommended integration path for most developers.
