### ISSUE TITLE
Cannot get card off of created customer using token

### ISSUE THREAD

**Issue by pieterdev** [stripe/stripe-java#141]
Hi, I've created a customer:

Map<String, Object> customerParams = new HashMap<String, Object>();
        customerParams.put("source", token)
        customerParams.put("email", user.email)

Customer customer = Customer.create(customerParams)

The token was created using client-side js library. The customer entry and card gets created, and I verified this in the skype dashboard.

The problem is that the returned value, customer, has its defaultCard set to null. getCards() returns the same.

I tried doing: 

Customer cu = Customer.retrieve(customer.id)
            Card card = cu.getDefaultCard()

straight after, but card is still null. 

I need to save the card token so that I can maintain the customer record while removing a card. I also can't access cards later on using customer.getCards. It just returns null.

How do I do this using the java api? Am I missing something?

**Comment by pieterdev** [comment]
Ah nevermind, I figured it out. Been changed to payment sources due to the bitcoin stuff right? I'm now using the sources collection on the customer.

**Comment by jimdanz** [comment]
Correct!  As of https://stripe.com/docs/upgrades#2015-02-18

**Comment by pieterdev** [comment]
Awesome, thanks for getting back to me. It's been working just fine :) I love stripe

**Comment by jimdanz** [comment]
:D
