### ISSUE TITLE
Charge.create ambiguity

### ISSUE THREAD

**Issue by Argoday** [stripe/stripe-java#142]
The return of Charge.create() is ambiguous in the doc and could be made clearer.

From doc page: https://stripe.com/docs/api/java#charge_object
-- --
Returns
Returns a charge object if the charge succeeded. Throws an error if something goes wrong.
-- --
1. The returned charge object contains FailureCode and FailureMessage ... it is unclear if these are guaranteed to be null when returning from Charge.create() - the doc should specify
2. For record keeping in the case that the Charge.create() call throws a CardException the charge.id is not captured so we can not record the id of the failed charge and correlate charges to our system events (CardException only contains code/param)
3. Status field of Charge object is missing ... however it isn't clear what that field indicates

**Comment by Argoday** [comment]
Another ambiguity:
* It isn't clear when a CardException may be thrown and by which methods and with which codes ... does Customer.createCard() throw CardException? ... maybe, but since every method is marked as throwing all exceptions who knows which error cases need to be handled by which calls.
  * What are the possible CardException codes that can be thrown by Customer.createCard() ?

... in general there is near zero information on the potential error behavior of these calls - there are only 'catch-em-all' style exceptions that everything throws and they contain a universal list of codes even though I'm sure it isn't possible to get certain codes as a response from certain calls

**Comment by matthewarkin** [comment]
Ugh Chrome crashes right as I finish.

If a charge fails when you use Charge.create(), no charge object is created, and an exception is through. The status of "failed", and FailureCode and FailureMessage would only be set if a charge fails during some automatic billing (like that of an invoice). Since no charge object was created, no charge id exists.

I will give you that status does appear to be missing from the Java library.

For the most part pretty much every exception but  Card exception could happen on any call, a card error would only be thrown if for some reason the card couldn't be charged, and the [docs](https://stripe.com/docs/api/java#errors) give a short description about the other errors, incorrect parameters, connection issues, stripe issues, authentication issues.

**Comment by Argoday** [comment]
Unaddressed items:

1) The Status field documented in the API docs is missing on the com.stripe.model.Charge object in this java client

2)
> "The status of "failed", and FailureCode and FailureMessage would only be set if a charge fails during some automatic billing (like that of an invoice)."

This makes things even more confusing ... (how does an invoice come into the picture?)

Points:
* The com.stripe.model.Charge class contains failureCode and failureMessage fields.
* I've dug into the source of the client and you guys are doing a GSON.fromJson to parse the response body in the case a non-200 is returned by the API.

So the question is:

Can the API return a HTTP 200 in response to a Charge.create() call and have failureCode populated?  And, if so: what are the possible failure codes?

**Comment by matthewarkin** [comment]
Charge.create() should never return a failed charge with a failureCode set, it would be a 402 (payment required).

Charge.retrieve() can return a charge with a failureCode set (that would be a 200)

**Comment by Argoday** [comment]
awesome!

https://stripe.com/docs/api#create_charge is unclear on this point,.. would be nice for you guys to ping a doc writer to see if this can be made clearer in the api docs.

Cheers

**Comment by cyphix333** [comment]
I'm here after getting very confused about this as well - not using Java, but PHP. I know the docs said that a charge object is created if it succeeded and if not an error is thrown, but then I started looking at the response and seen the `failure_code` and `failure_message` so figured I needed to account for these - then couldn't work out why the object was always empty on failures.

Docs could use some clearer explanation of this.

**Comment by remi-stripe** [comment]
@cyphix333 When a charge succeeds, a charge object is returned. If it failed, an error is returned instead but we also return the corresponding charge id in the `charge` property on the error.

This lets you retrieve the charge afterwards and you can look at the `failure_code` and `failure_message` on that failed charge to understand what blocked it.

**Comment by cyphix333** [comment]
@remi-stripe Thanks for that. Just think the docs could be clearer as initially it's very confusing on why the object contains those properties when it's stated a charge object is only returned on success.
