### ISSUE TITLE
Need to be able to bypass/disable checkSSLCert(conn);

### ISSUE THREAD

**Issue by sveinare** [stripe/stripe-java#144]
Hi,

We are on a network that is terminating all SSL-traffic on the gateway-level. Meaning, no outgoing SSL-calls make sence, since the certificate will not match the server, only the gateway (I'm not sure of the details). Anyway: The IT-department set up rules that will translate all calls to http://api-stripe.com to https://api.stripe.com when they leave the gateway.

Is it possible to have an option to skip these tests (that fail for us).
checkSSLCert(conn);

Can I make a pull request?

**Comment by jimdanz** [comment]
Hi @sveinare,

There is an option to skip this check when you also have the API host set to something other than api.stripe.com:
https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/net/APIResource.java#L223

So specifically you can set `Stripe.verifySSL = false;` and `Stripe.apiBase =  http://api-stripe.com;`.  I truly Do Not recommend this without a thorough understanding of the downstream implications.   Also, the verification of the SSL cert is specifically to guard against a cert that was revoked as part of our Heartbleed response (https://stripe.com/blog/heartbleed).  It would be prudent to check (at the gateway level) that you're not getting that compromised cert.  But strictly speaking, we do support this with `verifySSL=false`.

**Comment by sveinare** [comment]
My problem is that the `!hconn.getURL().getHost().equals("api.stripe.com")` will be `false` since it doesn't include http/https.

My suggestion is to skip this host-compare.

**Comment by jimdanz** [comment]
Hm.  `!hconn.getURL().getHost().equals("api.stripe.com")` should be true if your host is `api-stripe.com`.

**Comment by sveinare** [comment]
Sorry. Typo.
I meant:
...will translate all calls to http://api.stripe.com to https://api.stripe.com... (in other words make the http a https)

**Comment by kyleconroy** [comment]
@sveinare This should now work. The `checkSSLCert` function has been removed.
