### ISSUE TITLE
Library accesses GSON internal API, breaks with gson on the module path

### ISSUE THREAD

**Issue by mikehearn** [stripe/stripe-java#1494]
### Describe the bug

The `ReflectionCheckingTypeAdapterFactory` class accesses a GSON internal class directly. This breaks when GSON is placed on the module path due to encapsulation.

`java.lang.IllegalAccessError: class com.stripe.net.ReflectionCheckingTypeAdapterFactory (in unnamed module @0x69a3d1d) cannot access class com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter (in module com.google.gson) because module com.google.gson does not export com.google.gson.internal.bind to unnamed module @0x69a3d1d @ com.stripe.net.ReflectionCheckingTypeAdapterFactory.create(Unknown Source)`

### To Reproduce

Place gson on the module path and then try to use the Stripe API.

### Expected behavior

There are a few possible fixes that spring to mind:

1. This class looks like a utility / assertion checking class, so it could be disabled in production code paths.
2. Instead of using `instanceof`, the class name could maybe be checked using reflection?
3. The `IllegalAccessError` could be caught, and that used to disable the check at runtime.

### OS

macOS

### Java version

Java 17

### stripe-java version

22.1.0

### API version

2022-11-15

### Additional context

A workaround is to place gson on the classpath instead of the module path. One could probably also use `--add-opens`.

**Comment by richardm-stripe** [comment]
Relates to https://github.com/stripe/stripe-java/pull/1197.

**Comment by mikehearn** [comment]
Thanks!

**Comment by richardm-stripe** [comment]
Released in https://github.com/stripe/stripe-java/releases/tag/v22.4.0
