### ISSUE TITLE
Stripe 1.27.0 not available on Maven Central

### ISSUE THREAD

**Issue by dharrigan** [stripe/stripe-java#154]
Hi,

Latest release was 6 days ago, but doesn't seem available on Maven Central, only 1.26.0.

Sonatype Nexus : http://goo.gl/nH7XWd

-=david=-

**Comment by danwang** [comment]
Sorry about that -- it's been fixed!

https://repo1.maven.org/maven2/com/stripe/stripe-java/1.27.0/

**Comment by dharrigan** [comment]
w00t! thanks for the quick turnaround :-)
