### ISSUE TITLE
Attaching a payment method to a customer without retrieving it first

### ISSUE THREAD

**Issue by michaeldimchuk** [stripe/stripe-java#1564]
### Is your feature request related to a problem? Please describe.

Currently, the only way to attach a payment method to a customer using the model classes is by retrieving the PaymentMethod object first, and then attaching it to the customer, through an instance level method: https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/PaymentMethod.java#L280.

The only reason for that method to be an instance level method rather than a static method is to get the payment method id to generate the endpoint to hit: https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/PaymentMethod.java#L307.

This is an issue because outside of using the raw API, I'm forced to first do a GET retrieve request on the payment method, which increases latency in my own APIs.

The Java SDK is the only one that does not support directly attaching a payment method without retrieving it first, all the others accept a `customer` parameter that allows for this to be done: https://stripe.com/docs/api/payment_methods/attach?lang=python.

### Describe the solution you'd like

Create an alternative static method for the `PaymentMethod#attach` function, which accepts the payment method id as well as the other parameters that are currently accepted by the instance level method.

### Describe alternatives you've considered

I can use the raw API to do this, but the model class way of doing it is a lot simpler and cleaner.

**Comment by remi-stripe** [comment]
@michaeldimchuk Thanks for the detailed report! It's something we've wanted to introduce in stripe-java for a while but haven't been able to prioritize fully just yet. I'll tag this as future and hopefully it's something we'll finally tackle this year!

**Comment by pakrym-stripe** [comment]
Hi,

This is now possible using the new `StripeClient`:

```java
StripeClient client = new StripeClient("api_key");

com.stripe.param.PaymentMethodAttachParams params =
    com.stripe.param.PaymentMethodAttachParams.builder()
        .setCustomer("cus_xxxxxxxxxxxxx")
        .build();

client.paymentMethods().attach("pm_xxxxxxxxxxxxx", params);
```
