### ISSUE TITLE
Add ability to read expanded response for collection resources

### ISSUE THREAD

**Issue by zakhenry** [stripe/stripe-java#1571]
### Is your feature request related to a problem? Please describe.

I want to be able to get a count of active subscriptions.

### Describe the solution you'd like

 The API supports adding an expand param "total_count", and while I can see the expected result in the lastResponse raw json, I cannot read it using the java sdk

I'd expect the following to work

```kotlin
    val subscriptions = Subscription.list(
        SubscriptionListParams.builder()
            .setLimit(0)
            .addExpand("total_count")
        .build())

  val totalCount = subscriptions.totalCount() // should be Int, or null if the expand was not sent
```

### Describe alternatives you've considered

I can work around it by manually parsing the lastResponse.body, but since the sdk supports setting the expand params, it should support reading it

**Comment by remi-stripe** [comment]
@zakhenry The `total_count` feature has been deprecated and undocumented for well over 6 years now. Unfortunately, this does still work to avoid breaking legacy integrations but no one should rely on this feature as it doesn't work well and is not something we want to continue supporting.

If you want a count, the best option is to use our official Search API instead which offers a count feature: https://stripe.com/docs/api/pagination/search#search_pagination-total_count
