### ISSUE TITLE
原本通过charges中的

### ISSUE THREAD

**Issue by sunchao999** [stripe/stripe-java#1573]
### Describe the bug

before:
![image](https://github.com/stripe/stripe-java/assets/23114161/057a55b9-ac93-4dd6-84a3-379cb89d62bb)
![image](https://github.com/stripe/stripe-java/assets/23114161/869ef95c-f458-4fa8-a45e-5fdb6fb6492f)
now:
![image](https://github.com/stripe/stripe-java/assets/23114161/17bb5d1b-a516-4114-8493-93275d9906d6)
![image](https://github.com/stripe/stripe-java/assets/23114161/f7eac3f9-ea3c-428d-bef4-6357a88fb1b3)
latest_charge only has ID, unable to find more information

### To Reproduce

as above

### Expected behavior

PaymentIntent can obtain last4 and other information

### OS

android

### Java version

java 8

### stripe-java version

22.3

### API version

2022-12-08

**Comment by remi-stripe** [comment]
@sunchao999 Github issues should be limited to bugs with the library and this is more an integration/support question better directed at our support team: https://support.stripe.com/contact

To unblock you though, this was a change with the latest API version ([2022-11-15](https://stripe.com/docs/upgrades#2022-11-15)) where the `charges` collection on PaymentIntent was removed and replaced with `latest_charge` which is the id of the most recent Charge (`ch_123`). What you can do is use our Expand feature (see [docs](https://stripe.com/docs/expand)) to retrieve a PaymentIntent and expand the latest Charge into a full Charge object.

I'm going to close this issue out but if you have a follow up question, don't hesitate to talk to our [support team](https://support.stripe.com/contact)

**Comment by sunchao999** [comment]
Upgrade stripe Java version from 20.111 to 222.3
I am unable to obtain last4 and other information from capture as before
I want to know how to obtain it now

I just got to know stripe and I'm not very familiar with it. I'm sorry

**Comment by remi-stripe** [comment]
No worries I understand! I did try to explain what to do above. You need to adapt your code so that when you retrieve the PaymentIntent, you **expand** the `latest_charge` at the same time to see the full card details you are looking for. The new code would look something like this:

```
PaymentIntentRetrieveParams params =
  PaymentIntentRetrieveParams.builder()
    .addExpand("latest_charge")
    .build();

PaymentIntent intent = PaymentIntent.retrieve("pi_123", params, null);
Charge charge = intent.getLatestChargeObject();
```

At that point, `charge` is a full Charge object and you can access the properties you are looking for.

Please work directly with our support team if you have any follow up questions as I won't be able to help further here.

**Comment by sunchao999** [comment]
Thank you very much，My problem has been solved by you
&nbsp;


九幡部&nbsp;	
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月1日(星期四) 上午10:58
收件人: ***@***.***&gt;; 
抄送: "九幡部 	***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stripe/stripe-java] 原本通过charges中的 (Issue #1573)





 
不用担心，我明白！我确实试图解释上面该怎么做。您需要调整代码，以便在检索付款意图时，同时展开以查看所需的完整卡详细信息。新代码将如下所示：latest_charge
 PaymentIntentRetrieveParams params =   PaymentIntentRetrieveParams.builder()     .addExpand("latest_charge")     .build(); PaymentIntent intent = PaymentIntent.retrieve("pi_123", params, null); Charge charge = intent.getLatestChargeObject();  
此时，是一个完整的 Charge 对象，您可以访问要查找的属性。charge
 
如果您有任何后续问题，请直接与我们的支持团队合作，因为我无法在这里进一步提供帮助。
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您被提及。Message ID: ***@***.***&gt;
