### ISSUE TITLE
ProductCreateParams is missing images

### ISSUE THREAD

**Issue by hstaudacher** [stripe/stripe-java#1583]
### Describe the bug

According to this [doc](https://stripe.com/docs/api/products/create) images should be able to be set during creation. Within the java sdk the `ProductCreateParams` lags this property.

### To Reproduce

Create a product using `ProductCreateParams`

### Expected behavior

Images should be available on `ProductCreateParams`

### OS

macOS

### Java version

Java 17

### stripe-java version

22.0.0

### API version

 2022-11-15

**Comment by remi-stripe** [comment]
Hey @hstaudacher, if you look at the source for `ProductCreateParams` [here](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/param/ProductCreateParams.java) you can see that we support the `images` parameter and it's defined [here](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/param/ProductCreateParams.java#L74).

I just tried locally with the latest stripe-java and the code below works as expected:

```
ProductCreateParams params =
  ProductCreateParams.builder()
    .setName("Product name")
    .addImage("https://images.com")
    .build();

Product product = Product.create(params);

System.out.println(product.getImages());
```

**Comment by hstaudacher** [comment]
Thanks for pointing this out. I was looking for setImages like it is in the update param didn't realizing there is an`add`.
