### ISSUE TITLE
Payment method configurations API beta missing from SDK

### ISSUE THREAD

**Issue by bmariesan** [stripe/stripe-java#1589]
### Is your feature request related to a problem? Please describe.

We have requested beta access to the [Payment Method Configurations API](https://stripe.com/docs/connect/payment-method-configurations) and we've noticed it's not part of the latest released SDK version

**Comment by pakrym-stripe** [comment]
Hi @bmariesan, beta APIs are released on opt-in basis. The team that owns [Payment Method Configurations API](https://stripe.com/docs/connect/payment-method-configurations) is considering an SDK release but can't provide any exact dates yet.

**Comment by anniel-stripe** [comment]
Hello, thank you for your patience! The Payment Method Configurations API has been added in [v22.28.0-beta.1](https://github.com/stripe/stripe-java/releases/tag/v22.28.0-beta.1). The [Beta SDKs](https://github.com/stripe/stripe-java#beta-sdks) section of our README has some information on how to get started with the beta version.
