### ISSUE TITLE
Null check `refunds` in `getRefunds` on charges.

### ISSUE THREAD

**Issue by andrewpthorp** [stripe/stripe-java#161]
https://github.com/stripe/stripe-java/blob/54f695e42ea09bd681fce25fe5e1b9d7e9a026b0/src/main/java/com/stripe/model/Charge.java#L219

If `refunds` has not been set (or has not been deserialized), this will throw an NPE.

**Comment by jimdanz** [comment]
When can this come up?  Every charge response should have a `refunds` entry, unless I'm mistaken.

**Comment by andrewpthorp** [comment]
I think it only happens when casting the `event.data.object` from a 'charge.*' webhook to a `Charge`

**Comment by jimdanz** [comment]
We've fixed this on the API side, so that it should no longer be an issue (it should now be impossible to get a charge object with no refunds field.)

**Comment by jimdanz** [comment]
Spoke too soon -- just realized that old event data will be affected.
