### ISSUE TITLE
Stripe invoice finalization

### ISSUE THREAD

**Issue by Saurabh48** [stripe/stripe-java#1613]
### Is your feature request related to a problem? Please describe.

Whenever a new subscription is created, the new invoice is created and then it finalized immediately.

But for next billing cycle, first it will change the billing cycle and subscription status will be still 'active'.
then it will create an invoice and will finalize it after one hour if we will listen for the 'invoice.created'.

can we finalise the invoice immediately after creating it?
and can the status of subscription can be other than 'active' if payment is not done for next billing cycle ?

**Comment by remi-stripe** [comment]
@Saurabh48 Same advice as the other question. This isn't a support forum so our support team will be better equipped to answer: https://support.stripe.com/contact

Overall, that Invoice stays open to let your code react and add any additional line items that might be expected. It will be finalized automatically after an hour and you can call the API to finalize it if needed in your webhook handler. I recommend carefully reading [this doc](https://stripe.com/docs/invoicing/integration/automatic-advancement-collection) for more details .
