### ISSUE TITLE
Upgrade the subscription

### ISSUE THREAD

**Issue by Saurabh48** [stripe/stripe-java#1618]
### Is your feature request related to a problem? Please describe.

I am creating an subscription and then it is generating an invoice and payment Intent.
Then I am sending the **Client_Secret** to my frontend.
Then I am adding the test card details in the form '4242 4242 4242 4242'. And attempt for payment.

Then this card is saved as default payment method to the subscription.

Then I am hitting on stripe to upgrade that subscription then it tries to auto collect the payment but it doesn't happen.
But the paymentIntent status is 'required_action' and it is due to 3D secure.

But in stripe docs the card '4242 4242 4242 4242' doesn't need any authentication;

can you help me in that ?

**Comment by remi-stripe** [comment]
@Saurabh48 Github issues should be limited to bugs with the stripe-java library itself and this is unfortunately not a support forum. For integration support, please work directly with our support team instead: https://support.stripe.com/contact
