### ISSUE TITLE
tax_percent is not received in fetch subscription

### ISSUE THREAD

**Issue by jpeet** [stripe/stripe-java#169]
The value is set.. but not returned.

Example response:

  "id": "sub_6CEI0cfY083D3I",
  "current_period_end": 1431039599,
  "current_period_start": 1431008320,
  "cancel_at_period_end": false,
  "customer": "cus_6CDhzGISxOHPXR",
  "start": 1431009744,
  "status": "trialing",
  "trial_start": 1431008320,
  "trial_end": 1431039599,
  "plan": {
    "amount": 5900,
    "currency": "gbp",
    "id": "core-59",
    "interval": "month",
    "interval_count": 1,
    "name": "Core Plan",
    "livemode": false,
    "trial_period_days": null,
    "metadata": {},
    "statement_descriptor": "Core Plan",
    "statement_description": null
  },
  "canceled_at": null,
  "ended_at": null,
  "quantity": 3,
  "discount": null,
  "application_fee_percent": null,
  "metadata": {}
}

**Comment by jimdanz** [comment]
Fixed by #170  -- thanks!  Let us know if you need a release cut.
