### ISSUE TITLE
Unable to use Webhook.constructEvent when using StripeClient

### ISSUE THREAD

**Issue by nielsvanvelzen** [stripe/stripe-java#1719]
### Describe the bug

When Stripe is initialized with the `StripeClient` class there is no API key set on the global Stripe object. If you then use `Webhook.constructEvent()` there is no way to set the client to use. If you then use functions that make API requests (like auto paging) you get an exception:

```
com.stripe.exception.ApiKeyMissingException: API key is not set. You can set the API key globally using Stripe.ApiKey, or by passing RequestOptions
	at com.stripe.net.LiveStripeResponseGetter.validateRequestOptions(LiveStripeResponseGetter.java:294)
	at com.stripe.model.StripeCollection.autoPagingIterable(StripeCollection.java:66)
....
```

### To Reproduce

1. Initialize StripeClient without using `Stripe.apiKey`
2. Construct webhook event `Webhook.constructEvent(payload, signature, webhookSecret)`
3. Use a method that calls the API

### Expected behavior

I expect a way to manually set the client to use when constructing the event. This could be done in 2 ways:
1. Add a "constructEvent" to webhookEndpointService/eventService
2. Add a prameter to the global constructEvent" to set the StripeClient instance

I also noticed there is a `setResponseGetter` method in `Event` but the `getResponseGetter` method in StripeClient is protected and thus cannot be accessed.

### OS

Ubuntu 22.04

### Java version

Java 20

### stripe-java version

24.10.0

### API version

2023-10-16

**Comment by pakrym-stripe** [comment]
This is definitely a bug. We'll add a `constructEvent` call to the client.
