### ISSUE TITLE
Managed account creation, Account.Verification.status field is missing

### ISSUE THREAD

**Issue by LesNovell** [stripe/stripe-java#172]
Hello, I see the Verification object for managed accounts is missing the verification status field.  Can it be added so I can check the verification status for a managed account?

Ex:
    "verification": {
      "status": "unverified",
      "document": null,
      "details": null
    }

**Comment by LesNovell** [comment]
Sorry, I found this under LegalEntity. My mistake

**Comment by jimdanz** [comment]
thanks for closing the loop!
