### ISSUE TITLE
Cannot get either tax amount or tax_percent in java library.

### ISSUE THREAD

**Issue by moqichenle** [stripe/stripe-java#173]
according to the document(https://stripe.com/docs/api/curl#retrieve_invoice) about retrieving invoice, it shows tax_percent and tax in json. However, there is no way to get it either in Invoice or Subscription.

**Comment by andrewmullaney** [comment]
Bump - this is causing us havoc!

**Comment by kyleconroy** [comment]
Tax percent was added to subscriptions in https://github.com/stripe/stripe-java/commit/eec05c2626823fe00f2a0f26f3aad899d34f3e70. It looks like we're still missing tax. Invoices are also missing tax and tax percent. Working on a fix for this now.

**Comment by moqichenle** [comment]
thank you for reply.

We noticed it was added into subscriptions in this github project. However, in the library (version 1.28.0) , we didnt it in Subscriptions. Is there a new version soon? Thanks.

**Comment by kyleconroy** [comment]
As soon as the PR is merged, I'll upload a new version of the library to central.

**Comment by kyleconroy** [comment]
@moqichenle @andrewmullaney version 1.29.0 has been updated.

**Comment by moqichenle** [comment]
Thank you very much. Could you please update in maven repository?
