### ISSUE TITLE
Could not get the country of the customer

### ISSUE THREAD

**Issue by moqichenle** [stripe/stripe-java#175]
I cannot find out which country the customer is from.....based on the java api.

it shows Country in sources part of the customer json.  however, when retrieving customer by customer_id in java, it didnt return sources with the customer. 
Thank you.

**Comment by jimdanz** [comment]
Hi there,
The customer object itself does not have a `country` property.  However, Card objects do.  So if a customer's first source is a `Card`, you should be able to do:
`((Card)customer.getSources().getData().get(0)).getCountry()`

**Comment by moqichenle** [comment]
Thank you for ur reply! I will try it. :dancer:

**Comment by moqichenle** [comment]
I had a look today. I m using 1.28.0 version in scala. 

These are the properties I can find in the Customer.class. No any sign of "Sources".
```LOG
public class Customer extends APIResource implements MetadataStore<Customer> {
	Long created;
	String id;
	Boolean livemode;
	Boolean deleted;
	String description;
	String defaultCard;
	String email;
	Long trialEnd;
	Discount discount;
	NextRecurringCharge nextRecurringCharge;
	CustomerSubscriptionCollection subscriptions;
	/** 1/2014: Legacy (from before multiple subscriptions per customer) */
	Subscription subscription;
	Boolean delinquent;
	Integer accountBalance;
	CustomerCardCollection cards;
	Map<String, String> metadata;
```

**Comment by bkrausz** [comment]
Sources has been added: for those only charging credit cards it's essentially a rename of `cards`
