### ISSUE TITLE
Charge.java Model attribute issue?

### ISSUE THREAD

**Issue by aravinthraja** [stripe/stripe-java#180]
The attribute "amount" in the Charge.java inside "com.stripe.model"  having the type of Integer. i think it has to be Float.
Amount can be in any format like  $1, 1.99 , 3.568

**Comment by kyleconroy** [comment]
@aravinthraja All amounts in the Stripe API are represented as integers. Storing money as floats has [inherent problems](http://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency), so amounts should always be stored as integers (in cents).

**Comment by aravinthraja** [comment]
Its helps Me a lot Thank you so much.
