### ISSUE TITLE
Add feature to add Discount in SubscriptionCreateParams

### ISSUE THREAD

**Issue by pranaytripathi** [stripe/stripe-java#1809]
### Is your feature request related to a problem? Please describe.

I am have service based on Spring boot and I am using Stripe library version 24.13.0.

 I am trying to add Discounts to the Subscription while trying to create a subscription. The library doesn't seem to support this feature to add the Discount to the `SubscriptionCreateParams` although it is mentioned as an example in documents. 

Documentation:
![Screenshot from 2024-05-19 20-00-16](https://github.com/stripe/stripe-java/assets/29519533/ac668eac-ab98-40bd-820a-f052cc63b90e)

Fields in the `SubscriptionCreateParams`:
![Screenshot from 2024-05-19 20-03-34](https://github.com/stripe/stripe-java/assets/29519533/95af2f17-6628-4c69-a869-24ed65eb35c3)

### Describe the solution you'd like

I would like to have this ability to add Discount to the `SubscriptionCreateParams`  as mentioned in the documentation.

### Describe alternatives you've considered

One of the alternative that we have is to create a Map for this and populate all the values there. I would like to avoid as its not easily type checked and more prone to errors.

### Additional context

I am open to contribute towards this feature. The feature request is quite essential for our recent service changes as we are trying to move discounts towards Stripe.

**Comment by remi-stripe** [comment]
@pranaytripathi You are likely on an old version of stripe-java at the moment. You can see in the code [right here](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/param/SubscriptionCreateParams.java#L778-L784) that the `addDiscount()` method has been added already. Looking at the changelog, it was added in [24.23.0](https://github.com/stripe/stripe-java/blob/master/CHANGELOG.md#24230---2024-04-04).

**Comment by pranaytripathi** [comment]
Thanks it seems it was recently added.

**Comment by remi-stripe** [comment]
Yes this feature only shipped publicly last month which is why it's on a recent version of stripe-java
