### ISSUE TITLE
Change due date attribute of Stripe invoice to a past date

### ISSUE THREAD

**Issue by rb090** [stripe/stripe-java#1830]
### Is your feature request related to a problem? Please describe.

I am generating monthly invoices for platform fees paid by a specific Stripe Connect account using the robust Stripe Invoicing tool. These fees are automatically paid through destination charges.

Here a sample of an invoice we generate:

![Screenshot 2024-06-24 at 09 17 51](https://github.com/stripe/stripe-java/assets/59200033/bdf57858-ea25-41e7-83b2-9db487a31c17)

Since I need to create invoices for previous months, the due date of the invoice should also be in the past, not the date of invoice generation or any future date. However, based on the Stripe documentation, setting a due date in the past is currently not possible.

I am using this code for invoice generation yet:

```
val automaticTaxBehaviour = InvoiceCreateParams.AutomaticTax.builder().setEnabled(true).build()

val invoiceCreateParams =
    InvoiceCreateParams
        .builder()
        .setCustomer(stripeCustomerId)
        .setCurrency("EUR")
        .setDescription("$INVOICE_DESCRIPTION_PLATFORM_FEES $localizedMonth.")
        .setFooter(INVOICE_FOOTER_PLATFORM_FEES)
        .setAutomaticTax(automaticTaxBehaviour)
        .setAutoAdvance(false)
        // ⚠️ StripeException when "monthRange.start" in the past on invoice generation
        //.setDueDate(monthRange.start)
        //.setCollectionMethod(InvoiceCreateParams.CollectionMethod.SEND_INVOICE)
        .build()

val invoiceCreateParamsPeriod =
    InvoiceItemCreateParams.Period
        .builder()
        .setStart(monthRange.start)
        .setEnd(monthRange.endInclusive)
        .build()

val newInvoice = Invoice.create(invoiceCreateParams)

val invoiceItem =
    InvoiceItemCreateParams
        .builder()
        .setCustomer(stripeCustomerId)
        .setPrice(priceId)
        .setInvoice(newInvoice.id)
        .setQuantity(1)
        .setPeriod(invoiceCreateParamsPeriod)
        .build()

val finalInvoice = newInvoice.finalizeInvoice()
```

Is there any possibility that this feature might be please implemented in the future? Allowing due dates to be set in the past would greatly enhance the flexibility of Stripe Invoicing.

### Describe the solution you'd like

Allow past timestamp in `setDueDate` on `InvoiceItemCreateParams`.

**Comment by remi-stripe** [comment]
@rb090 Your ask is more a feature request for the API itself, not the stripe-java SDK. Our SDK doesn't validate those timestamps, it's the API that rejects it. Feature requests like this should be reported to our support team directly so they can be tracked and associated with your Stripe account. You can contact them here: https://support.stripe.com/contact

I'm going to close this issue as there's no SDK work for this at the moment.

**Comment by rb090** [comment]
Hi @remi-stripe,
okay, thank you for the quick answer on this 🙌. I thought that it has sth to do with the SDK as a `StripeException` is thrown when `dueDate` is set to a past date on `InvoiceCreateParams`.
I wrote Stripe support an email regarding this with an explicit feature request.
