### ISSUE TITLE
retrieve raw JSON, instead of immediately parsing into Stripe Models

### ISSUE THREAD

**Issue by decoursin** [stripe/stripe-java#1839]
### Is your feature request related to a problem? Please describe.

In certain cases, we use our own models. The stripe-java api client has their own models. Therefore, we have to manually convert the stripe-java models into our models, which is problematic for a few reasons:

1. We have to parse the json anyways when parsing events, so we're forced to create our own models, which is fine. But now we have to write code to convert json into our models and also manual code that converts Stripe's models into our models because for example `Customer.retrieve(..)` returns a `com.stripe.model.Customer` instead of json. Only one of these should be necessary.
2. Stripe-java models are forced to integrate with all properties. Changes in API versions causes bug and parsing errors. When we use our own models, we only need to parse those properties we care about, which makes changing API versions far less prone to failures/problems due to changes in Stripe's API interfaces.
3. Generally speaking, depending on stripe-java to parse Stripe's HTTP Api json is another 3rd party dependency that we don't want to depend if we don't need to. This increases the chances of bugs and problems.

### Describe the solution you'd like

It would be nice if we could choose get the json directly instead of Stripe's models, so that we can instead parse them directly ourselves into our models.

**Comment by helenye-stripe** [comment]
Hi @decoursin. There are several ways to do this already. You can access the raw response and raw JSON object from any StripeObject that was retrieved from the API. [See here](https://github.com/stripe/stripe-java/blob/f0df4e7be54b902c4f1b134c4688b827c936e90f/src/main/java/com/stripe/model/StripeObject.java#L24). Another alternative, if it is possible for you to switch to use the stripe-java beta, it is possible to send raw requests. See documentation for [custom requests here](https://github.com/stripe/stripe-java/tree/beta?tab=readme-ov-file#custom-requests).

**Comment by decoursin** [comment]
Great @helenye-stripe thanks so much

**Comment by decoursin** [comment]
Hi @helenye-stripe can you please explain to me in a sentence or two what the beta is? Is it going to eventually replace the official `stripe-java` at some point, or is it just the same as `stripe-java` but like a nightly-build of sorts that always just a little bit more ahead of `stripe-java`?

It would be nice if this were documented on the README I think.
