### ISSUE TITLE
stripeClient throw JsonSyntaxException instead of StripeException

### ISSUE THREAD

**Issue by julienmweb** [stripe/stripe-java#1868]
### Describe the bug

Hi
After upgrading the com.stripe:stripe-java dependency from version 26.9.0 to 26.11.0, a test in our project fails:

The test expects stripeClient to throw a StripeException, but instead, a com.google.gson.JsonSyntaxException is thrown.
It looks like the JsonSyntaxException is thrown directly instead of being encapsulated within a StripeException like in the previous version

### To Reproduce

Create a test:
Configure WireMock to return an invalid JSON response when the stripeClient do a call
a JsonSyntaxException should be thrown

`
java.lang.AssertionError: 
Expecting actual throwable to be an instance of:
  com.stripe.exception.StripeException
but was:
  com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive; at path $
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1152)
	at com.google.gson.Gson.fromJson(Gson.java:1361)
	at com.google.gson.Gson.fromJson(Gson.java:1262)
	...(93 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
`

### Expected behavior

stripeClient should throw a StripeException

### OS

linux

### Java version

21

### stripe-java version

v26.11.0

### API version

2024-06-20

**Comment by ramya-stripe** [comment]
Thanks for reporting @julienmweb 
We will add this to our backlog

**Comment by mmvaubrun** [comment]
Hello, we face the same problem and it prevents us from upgrading: version 28.0.0 is also causing the same kind of issue

Is there a way to prioritise it ? 🙏

**Comment by helenye-stripe** [comment]
Hi, sorry about the delay and trouble caused here! We are looking into this issue.

**Comment by helenye-stripe** [comment]
This is fixed in the new release v28.0.1!

**Comment by julienmweb** [comment]
thank you !🙏
