### ISSUE TITLE
Charge description does not carry forward to connected account

### ISSUE THREAD

**Issue by alexg313** [stripe/stripe-java#188]
When a platform creates a charge on behalf of a connected account, the description provided for the charge appears on the payment in the platform account, but not in the connected account. In the connected account, the payment has a null/empty description. 

        Map<String, Object> params = Maps.newHashMap();
        params.put("customer", customer.getId());
        params.put("amount", amount);
        **params.put("description", myDescriptionString);**
        params.put("statement_descriptor", statementDescriptor);
        params.put("destination", input.getStripeConnectedAccount());
        params.put("application_fee", input.getApplicationFee());

**Comment by kyleconroy** [comment]
@alexg313 thanks for the bug report! This has been filed on our internal bug tracker.

**Comment by jimdanz** [comment]
@alexg313 this is expected behavior.  In order to specify a description for a charge that shows up on the connected account, you need to provide it as `transfer[description]=foo`.  So in your example:

```java
   Map<String, Object> params = Maps.newHashMap();
    params.put("customer", customer.getId());
    params.put("amount", amount);
    params.put("transfer", ImmutableMap.<String, Object>of("description", myDescriptionString));
    params.put("statement_descriptor", statementDescriptor);
    params.put("destination", input.getStripeConnectedAccount());
    params.put("application_fee", input.getApplicationFee());
```
