### ISSUE TITLE
Charge does not expose "Transfer ID"

### ISSUE THREAD

**Issue by alexg313** [stripe/stripe-java#190]
When a platform creates a charge on behalf of a connected account and provides the account ID of the connected account in the "destination" parameter, the full amount of the charge (minus the application fee) is immediately transferred to the connected account. 

When I login to my account (the platform), I can see the relevant Transfer ID in the Payment Details section of the payment. As far as I can tell, there is no way to programmatically retrieve this transfer Id.

**Comment by hardtoe** [comment]
Pull request #207 resolves this issue if it is accepted.

**Comment by kyleconroy** [comment]
PR has been merged
