### ISSUE TITLE
28.0.0 seems not available

### ISSUE THREAD

**Issue by t-k-c** [stripe/stripe-java#1918]
### Describe the bug

Hi, in your Readme, you indicated 28.0.0 but it seems not to be available: https://mvnrepository.com/artifact/com.stripe/stripe-java

### To Reproduce

 implementation "com.stripe:stripe-java:28.0.0" generates error

### Expected behavior

N/A

### Code snippets

```Java
implementation "com.stripe:stripe-java:28.0.0"
```

### OS

macOS

### Java version

Java 17

### stripe-java version

v28.0.0

### API version

N/A

**Comment by AlenMiletic** [comment]
The tests seemed to fail for https://github.com/stripe/stripe-java/actions/runs/11582760225 Java 11 and it wasn't published

**Comment by t-k-c** [comment]
@AlenMiletic okay thanks for the update.

**Comment by helenye-stripe** [comment]
@t-k-c I just reran the CI for `v28.0.0`. Can you try now?

**Comment by t-k-c** [comment]
@helenye-stripe . Yes.. looks good now. Thanks :)
