### ISSUE TITLE
v28.1.0 release failure

### ISSUE THREAD

**Issue by mbb7848** [stripe/stripe-java#1927]
### Describe the bug

I have to update API version to 2024-11-20.acacia. But `gradlew build` failed to resolve the package. After lots of investigation, just found that the release of v28.1.0 failed. Could you fix it ASAP.

https://github.com/stripe/stripe-java/actions/runs/11943592352

### To Reproduce

`gradlew build`

### Expected behavior

Build success 

### OS

Ubuntu

### Java version

Java 17

### stripe-java version

v28.1.0

### API version

2024-11-20.acacia

**Comment by xavdid-stripe** [comment]
Sorry about that - it looks like the build (at least the code portion) has passed now. Can you try again?

**Comment by mbb7848** [comment]
It works.
