### ISSUE TITLE
use wildcard bound instead of Map<String,Object>

### ISSUE THREAD

**Issue by chrylis** [stripe/stripe-java#205]
The static methods on `Charge` (and upstream, and likely elsewhere) specify a `Map<String,Object>` specifically, and it appears that a `Map<String,?>` would be suitable, as the parameters are (or should be) treated as read-only. This would make using the API with tools that perform type inference (such as Groovy) simpler, as the inferred generic type is generally `Serializable` instead of `Object`.

**Comment by kyleconroy** [comment]
@chrylis For now, we'll be sticking with `Map<String,Object>`. The plan is to move to strongly-typed RequestOption objects in version 2.
