### ISSUE TITLE
Javadoc on stripe objects

### ISSUE THREAD

**Issue by hardtoe** [stripe/stripe-java#210]
None of the model objects have javadoc on them.  It would be very useful to have javadoc on the model class declarations and accessor methods of the model objects based on the official stripe api reference.  It is my understanding that documentation for model fields does not change often and would be beneficial for the consumers of this API.

If this issue is accepted I will create a pull request with javadoc (EDIT: from the API reference documentation) for all of the model classes and their field accessors.

**Comment by kyleconroy** [comment]
@hardtoe That would be fantastic and much appreciated :D

**Comment by kyleconroy** [comment]
@hardtoe any update here? If you don't currently have time, I'm going to move this to a "version-two" task.

**Comment by Argoday** [comment]
+1

**Comment by hardtoe** [comment]
I don't currently have time to do this.  I think the "version-two" tag is the right choice...especially if it can be done as part of issue #211.

**Comment by kyleconroy** [comment]
This has now been added to the roadmap. I'm closing the issue, but feel free to continue discussing here.

**Comment by ob-stripe** [comment]
It sure took us a long time, but as of stripe-java 8.0.0, ~all fields on resource classes should have up-to-date Javadoc annotations!
