### ISSUE TITLE
Previous metadata values should be unset when updating metadata

### ISSUE THREAD

**Issue by olivierbellone** [stripe/stripe-java#236]
When updating metadata, the other bindings (tested with Python, not sure about the others) will unset the previous metadata fields.

E.g., with the Python bindings:
```python
>>> c = stripe.Customer.retrieve("cus_...")
>>> c.metadata
<StripeObject at 0x10577b868> JSON: {
  "A": "is for Aardvark", 
  "B": "is for Baboon"
}
>>> c.metadata = {'C': 'is for Cactus', 'D': 'is for Dachsund'}
>>> c.save()
>>> c = stripe.Customer.retrieve("cus_...")
>>> c.metadata
<StripeObject at 0x10577b868> JSON: {
  "C": "is for Cactus", 
  "D": "is for Dachsund"
}
```

The bindings correctly reset the `'A'` and `'B'` keys in the update request:
```
{
    metadata:
    {
        A: "",
        B: "",
        C: "is for Cactus",
        D: "is for Dachsund"
    }
}
```

However, when doing the same operation with the Java bindings:
```java
Customer customer = Customer.retrieve("cus_...");

System.out.println("Before update:");
System.out.println(customer.getMetadata());

Map<String, Object> customerParams = new HashMap<String, Object>();
Map<String, String> customerMetadata = new HashMap<String, String>();
customerMetadata.put("C", "is for Cactus");
customerMetadata.put("D", "is for Dachsund");
customerParams.put("metadata", customerMetadata);

customer.update(customerParams);

customer = Customer.retrieve("cus_...");

System.out.println("After update:");
System.out.println(customer.getMetadata());
```

The result is:
```
Before update:
{B=is for Baboon, A=is for Aardvark}
After update:
{B=is for Baboon, A=is for Aardvark, C=is for Cactus, D=is for Dachsund}
```

The update request only sent the new metadata keys, but didn't reset the previously existing ones:
```
{
    metadata:
    {
        C: "is for Cactus",
        D: "is for Dachsund"
    }
}
```

**Comment by jimdanz** [comment]
This is intended behavior.  stripe-java objects do not implement "save" methods that take the in-memory object and persist it to the API.  Instead, stripe-java objects implement an explicit update method, the contract of which is that it sends its map of parameters directly over the wire.

To unset a metadata key in stripe-java, pass empty string as the value.  For instance, `customerMetadata.put("D", "");`

**Comment by olivierbellone** [comment]
Thanks for the super fast reply @jimdanz!

**Comment by jimdanz** [comment]
My pleasure!  Thanks for raising.

**Comment by olivierbellone** [comment]
Just in case someone stumbles upon this in the future: passing an empty string (`""`) as the value for a metadata field will raise the following exception:
```
com.stripe.exception.InvalidRequestException: You cannot set 'metadata[D]' to an empty string. We interpret empty strings as null in requests. You may set 'metadata[D]' to null to delete the property.
```

As the exception message says, you should instead pass `null`:
```java
customerMetadata.put("D", null);
```

**Comment by jimdanz** [comment]
Ah sorry didn't realize that stripe-java overrides our handling of empty string.  Thanks for catching!
