### ISSUE TITLE
Customer Model Is Missing ShippingDetails Field

### ISSUE THREAD

**Issue by vberbenetz** [stripe/stripe-java#238]
Hi,

I was trying to retrieve the shipping object from the Customer object as per the API, but wasn't able to. Looking at the source of the Customer object, it appears that the ShippingDetails field is missing. Can you please let me know if this is an issue, or is there another way to retrieve the ShippingDetails object?

Thank you.

**Comment by remistr** [comment]
Hey @vberbenetz! Thank you for reporting this issue! The `shipping` parameter on the Customer object is quite recent and we haven't added it to the Java library just yet but PR are definitely welcome :)

**Comment by brandur** [comment]
Thanks for reporting! Added a fix in #244.
