### ISSUE TITLE
Version 1.38.1 missing from Maven central

### ISSUE THREAD

**Issue by steve-taylor** [stripe/stripe-java#241]
It seems that 1.38.1 is missing from central.

**Comment by brandur** [comment]
@steve-taylor Sorry, his one is my fault. I'll get a patched version released ~9 AM PT tomorrow.

**Comment by steve-taylor** [comment]
No problem at all. I'll just use the previous version until then.

**Comment by brandur** [comment]
This should be up there now. Thanks for reporting.
