### ISSUE TITLE
LegalEntity "getSsnLast4Provided" always returns null

### ISSUE THREAD

**Issue by sterfried** [stripe/stripe-java#257]
When calling this method it will always (at least in all my testing) return null. The "getPersonalIdNumberProvided" *appears* to be working. I committed these two fields in a recent pull request, so if there is an issue with this code I am happy to remedy it.

**Comment by brandur** [comment]
@sterfried Any theories? Examining the code, nothing stands out as certainly wrong. Are you sure that the object you're testing with has a `ssn_last_4_provided` attribute set?

**Comment by sterfried** [comment]
@brandur When I do a curl request on the account, in the response JSON I see that it has the value set as follows: 
    "personal_id_number_provided": true,
    "ssn_last_4_provided": true

If I had to throw out a theory it would be that the process that is converting these field names from camelcase to the json properties for the request to Stripe is possibly having an issue with the number "4", causing it to possibly look for "ssn_last4_provided" ?

That's all I can think of at the moment, not familiar with the conversion process being used, will try to do a little more digging.

**Comment by sterfried** [comment]
@brandur Looking at https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/FieldNamingPolicy.java it appears the LOWER_CASE_WITH_UNDERSCORES method then uses the separateCamelCase, which specifically looks for uppercase letters. 

If you believe my previous comment's assumption to be correct, then would changing the field name to be ssnLast_4Provided be a solution you would recommend?

If so, do you think we should change the method name to match (not sure that would be a good idea) and should I add a comment somewhere explaining the reason for the underscore?

Let me know what you think and I can make the changes if desired.

**Comment by sterfried** [comment]
Not sure of my schedule so put up PR #258 just in case.

**Comment by brandur** [comment]
Hey @sterfried!

Thanks for following up, and those are great finds! Some kind of automated name conversion mismatch does indeed seem like the most likely cause of this problem.

This is a little subjective, but the naming in #258 of `ssnLast_4Provided` looks a little bit awkward to me. As an alternative, what do you think about using Gson's `@SerializedName` annotation to just override the naming to what you already have in there?

https://google-gson.googlecode.com/svn/tags/1.2.3/docs/javadocs/com/google/gson/annotations/SerializedName.html

**Comment by brandur** [comment]
Oh, and:

> If so, do you think we should change the method name to match (not sure that would be a good idea) and should I add a comment somewhere explaining the reason for the underscore?

Yeah! A comment to go along with whatever change we make definitely wouldn't hurt.

**Comment by sterfried** [comment]
Much better! I had a feeling they would have an override somewhere, didn't spot it though. Will recommit. Comment next to annotation?

**Comment by brandur** [comment]
> Comment next to annotation?

Yes please!

**Comment by brandur** [comment]
This one was closed by #259.
