### ISSUE TITLE
Adding a bank account to a customer raises a java.lang.ClassCastException

### ISSUE THREAD

**Issue by olivierbellone** [stripe/stripe-java#260]
(Tested with the latest stripe-java 1.41.1.)

Using the [create a bank account](https://stripe.com/docs/api/java#create_bank_account) API call on a customer raises a `java.lang.ClassCastException`:
```java
Customer cu = Customer.retrieve("cus_...");
Map<String, Object> params = new HashMap<String, Object>();
params.put("source", "btok_...");
cu.createCard(params);
```

On Stripe's end, the customer is actually updated with the bank account, but this exception is raised in the code:
```
java.lang.ClassCastException: Cannot cast com.stripe.model.BankAccount to com.stripe.model.Card
	at java.lang.Class.cast(Class.java:3369)
	at com.google.gson.Gson.fromJson(Gson.java:690)
	at com.stripe.net.LiveStripeResponseGetter._request(LiveStripeResponseGetter.java:446)
	at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:65)
	at com.stripe.net.APIResource.request(APIResource.java:131)
	at com.stripe.model.Customer.createCard(Customer.java:366)
	at com.stripe.model.Customer.createCard(Customer.java:220)
	at StripeExample.main(StripeExample.java:50)
```

I guess we'd need a separate `createBankAccount()` method to account for the fact that the returned object will be a `BankAccount`, not a `Card`.

**Comment by remistr** [comment]
@ob: I wouldn't add a `createBankAccount()` and instead use a generic `createSource()` or `createExternalAccount()`. The following code works and should be generalized maybe?
```
ExternalAccount ban = customer.getSources().create(params);
```

**Comment by olivierbellone** [comment]
Right. I like the code you provided because it is very similar to what we'd do in Ruby / Python / PHP.

What I don't like is that it'd require the developer to manually upcast the `ExternalAccount` to `BankAccount` (or `Card`, etc.) if they need to use e.g. `getRoutingNumber()`.

@brandur, do you have any thoughts about this?

**Comment by brandur** [comment]
So first thought: @remistr is certainly right in that this is to some degree a user error, and can be worked around by using the `ExternalAccount` interface. However, I think the fact that you get an exception thrown from inside Gson is problematic: ideally we should add a little extra validation here so that a user who triggers this gets a much more friendly error that pushes them in the right direction towards correction.

One possibility to get around the upcasting problem might be to build a (optional) type parameterized version of create, e.g.

``` java
BankAccount ban = customer.getSources().create<BankAccount>(params);
```

It wouldn't be too much of a syntactic advantage over having a user just cast the result, _but_ what we could do is use the type hint in order to detect a type/create parameter mismatch, so as to again throw a more meaningful error to help the user along. Thoughts?

**Comment by olivierbellone** [comment]
I don't disagree that it's a user error, but at the moment our API doc educate users to use `createCard()` when creating bank accounts, so it'd be good to decide on what's the "right" way of doing this operation and update the doc accordingly.

I like your proposal: it keeps the code consistent with what we'd do in other languages while accounting for Java's static typing.

**Comment by brandur** [comment]
> I don't disagree that it's a user error, but at the moment our API doc educates users to use createCard() when creating bank accounts, so it'd be good to decide on what's the "right" way of doing this operation and update the doc accordingly.

Ah, I didn't see that this code was directly suggested by the docs! We definitely need a fix for that as well then :$

**Comment by olivierbellone** [comment]
I just deployed an update to the API reference:

- `createCard()` is no longer used (except for recipients). All payment sources creation requests now use `getSources().create(params)`.

- when retrieving a card or a bank account, there is a typecast, e.g.:
```java
BankAccount source = (BankAccount) customer.getSources().retrieve({BANK_ACCOUNT_ID});
```

Do you think we should mark `createCard()` as deprecated?

**Comment by brandur** [comment]
Nice docs changes @olivierbellone! Great work circling back around on this one.

> Do you think we should mark createCard() as deprecated?

Did you say above that we still need it for recipients?

**Comment by olivierbellone** [comment]
Sorry, what I was suggesting was that we flag `Customer.createCard()` as deprecated. We wouldn't change `Recipient.createCard()` (if anything, I guess the entire `Recipient` class should be flagged as deprecated...).

Also, I just realized that there _is_ a `createBankAccount()` method in the `Customer` class :facepalm:, so if we do decide to flag `createCard()` as deprecated, we should do the same for `createBankAccount()`.

**Comment by brandur** [comment]
> Sorry, what I was suggesting was that we flag Customer.createCard() as deprecated. We wouldn't change Recipient.createCard() (if anything, I guess the entire Recipient class should be flagged as deprecated...).
>
> Also, I just realized that there is a createBankAccount() method in the Customer class :facepalm:, so if we do decide to flag createCard() as deprecated, we should do the same for createBankAccount().

Ah, got it! And yeah, it seems reasonable to me to try and remove some of the crazy amount of surface area we have in this API, so I'm +1 on deprecation. Took a stab at it in #293.

**Comment by techyrajeev** [comment]
In test cases createBankAccount are still being used.
https://github.com/stripe/stripe-java/blob/master/src/test/java/com/stripe/functional/CustomerTest.java

`    @Test
    public void testCustomerBankAccountAddition() throws StripeException {
        Customer createdCustomer = Customer.create(defaultCustomerParams, supportedRequestOptions);
        String originalDefaultCard = createdCustomer.getDefaultCard();

        Map<String, Object> creationParams = new HashMap<String, Object>();
        creationParams.put("bank_account", defaultBankAccountParams);
        BankAccount addedBankAccount = createdCustomer.createBankAccount(creationParams);

        Token token = Token.create(defaultTokenParams);
        createdCustomer.createCard(token.getId());

        Customer updatedCustomer = Customer.retrieve(createdCustomer.getId(), supportedRequestOptions);
        assertEquals((Integer) updatedCustomer.getSources().getData().size(), (Integer) 3);
        assertEquals(updatedCustomer.getDefaultCard(), originalDefaultCard);

        Map<String, Object> updateParams = new HashMap<String, Object>();
        updateParams.put("default_source", addedBankAccount.getId());
        Customer customerAfterDefaultSourceUpdate = updatedCustomer.update(updateParams, supportedRequestOptions);
        assertEquals((Integer) customerAfterDefaultSourceUpdate.getSources().getData().size(), (Integer) 3);
        assertEquals(customerAfterDefaultSourceUpdate.getDefaultSource(), addedBankAccount.getId());
    }`
