### ISSUE TITLE
Expand support

### ISSUE THREAD

**Issue by kinfkong** [stripe/stripe-java#268]
I think we should support the expand properties in the objects.

**Comment by brandur** [comment]
Oof, you're absolutely right on this one. Unfortunately, I think we're going to need to commit to a fairly serious re-write of the code as it stands to get something like that in, but I'm going to tag this issue as "future" and leave it open so that we can keep an eye on it.

**Comment by appmagnetics** [comment]
Expand one property works if specified by param passed to APIResource.request 

		Map<String, Object> params = new HashMap<String, Object>();
		params.put("expand[]", "balance_transaction");

Can you confirm that over this interface you cannot use multiple expands like this 

		params.put("expand[]", "balance_transaction");
		params.put("expand[]", "customer");

Since the Map does not allow multiple identical keys, right?

**Comment by brandur** [comment]
@appmagnetics The library will automatically unpack any `List` given as a parameter value into the required Rack-style array encoding. So you should be able to do this:

``` java
		List<String> expands = new LinkedList<String>();
		expands.add("balance_transaction");
		expands.add("customer");

		Map<String, Object> params = new LinkedHashMap<String, Object>();
		params.put("expand", expands);
```

**Comment by appmagnetics** [comment]
Wow! it worked. I appreciate a fast answer from your side!

**Comment by brandur** [comment]
> Wow! it worked. I appreciate a fast answer from your side!

Great! And no worries! That's what we're here for.

**Comment by simon-marino** [comment]
+1 on this, see https://github.com/stripe/stripe-android/issues/81

**Comment by sowdri** [comment]
Needed expand support for `destination` field on `Payout` object.

**Comment by ob-stripe** [comment]
Hi @sowdri. We're currently working on adding support for all expandable attributes. You can see the PR here: https://github.com/stripe/stripe-java/pull/381

The PR should be merged and a new version released verys soon.

**Comment by ob-stripe** [comment]
As of [v5.3.0](https://github.com/stripe/stripe-java/blob/v5.3.0/CHANGELOG#L1-L3), the Java library supports expanding all expandable attributes! 🎆
