### ISSUE TITLE
Conflicting getter definitions for property "url": 

### ISSUE THREAD

**Issue by lsoares** [stripe/stripe-java#278]
I got this, using 
`java.lang.IllegalArgumentException: Conflicting getter definitions for property "url": com.stripe.model.StripeCollectionAPIResource#getUrl(0 params) vs com.stripe.model.StripeCollectionAPIResource#getURL(0 params)`

the problem in your class `StripeCollectionAPIResource` is:
![image](https://cloud.githubusercontent.com/assets/674045/14369898/bee4313a-fd20-11e5-850d-c06751c652cf.png)

I'm using version 1.48.0 with Maven. This is a Google Cloud Project running with a local jetty, but I don't think it matters.

**Comment by andrewnelder** [comment]
Hey @lsoares,

This looks like it might be something very specific to your JVM.  I am unable to reproduce this warning.

Can I see your stack trace?  It's possible that this is being raised by another library (like Jackson).

Cheers,
Andrew

**Comment by brandur** [comment]
+1. It does seem a little unusual that this wouldn't be showing up in our CI process.

That said, I don't think it would be too unreasonable to do a major version pass that involves just going through and removing all the interfaces marked deprecated. Most of them are just minor variations in names or arguments and it shouldn't be too terrible to upgrade to any of the non-deprecated versions.

**Comment by lsoares** [comment]
here it is:
http://pastebin.com/40jwXpuz

**Comment by brandur** [comment]
I've added a proposed fix in #279 and am open to hear feedback there. Thanks!

**Comment by andrewnelder** [comment]
Yeah, I thought it was probably something like Jackson.  I think this should probably just be consistent rather than deprecated.  I'm in favor of @brandur's solution in this case.
