### ISSUE TITLE
Convinience method on Event for getting an instance of the model it describes

### ISSUE THREAD

**Issue by andrhamm** [stripe/stripe-java#289]
It would be great if the inline comments, wiki, or Stripe API docs themselves would provide some practical examples for working with event data from webhooks. Please point me in the right direction if I'm missing something.

There doesn't appear to be any first-class support for taking the event data from an `Event` and turning it into an instance of the model it describes. An instance method on `Event` for conveniently getting an instance of the described model would be very useful. Something like `getDescribedObject()`. When I say "described object", I am referring to how the Stripe API docs denote the `invoice.payment_failed` event type as describing an `Invoice`:

<img width="361" alt="screen shot 2016-05-08 at 4 55 21 pm" src="https://cloud.githubusercontent.com/assets/591537/15100381/fe1f93f0-153d-11e6-8719-752c06631de9.png">

**Comment by olivierbellone** [comment]
Hey @andrhamm, you can do something like this:

```java
StripeObject stripeObject = event.getData().getObject();
```

and the resulting `stripeObject` will automatically be cast to the correct type. E.g. for an `invoice.payment_failed` event, it will be an `Invoice` object.

Of course, if you already know the object's type, you can initialize the object with the correct type yourself, e.g.:
```java
if (event.getType().equals("invoice.payment_failed")) {
    Invoice invoice = event.getData().getObject();
```

**Comment by andrhamm** [comment]
@olivierbellone Ah ha! Thank you for the quick reply, this helps a ton. I still can't help but feel some usage examples, preferably in the README, otherwise in the Wiki, would go a long way.

Thanks again 👍
