### ISSUE TITLE
"Not a JSON Object: null" when parsing customer.source.updated event

### ISSUE THREAD

**Issue by stevehall19** [stripe/stripe-java#290]
I've set up an Apache CXF rest service to receive Stripe webhooks. The CXF service just gives me the json String which I then pass to the Stripe Java SDK to unmarshall the json into an Event object. 

This works fine if I attempt to do this with a charge.succeeded event. However, when attempting to unmarshall a customer.source.update event it fails with the following error: "java.lang.IllegalStateException: Not a JSON Object: null".

I am testing this with the Stripe Dashboard's webhooking testing feature. This is the json being produced by the Stripe Dashboard when I tell it to send a test customer.source.update event:

```json
{
  "created": 1326853478,
  "livemode": false,
  "id": "evt_00000000000000",
  "type": "customer.source.updated",
  "object": "event",
  "request": null,
  "pending_webhooks": 1,
  "api_version": "2016-03-07",
  "data": {
    "object": {
      "id": "card_00000000000000",
      "object": "card",
      "address_city": "Austin",
      "address_country": "USA",
      "address_line1": "4500 Ave D",
      "address_line1_check": "pass",
      "address_line2": null,
      "address_state": "TX",
      "address_zip": "78751",
      "address_zip_check": "pass",
      "brand": "Visa",
      "country": "US",
      "customer": "cus_00000000000000",
      "cvc_check": null,
      "dynamic_last4": null,
      "exp_month": 12,
      "exp_year": 2016,
      "funding": "credit",
      "last4": "4242",
      "metadata": {
      },
      "name": "Testy McTester",
      "tokenization_method": null
    },
    "previous_attributes": null
  }
}
```
 
I went through it in a debugger and it appears to be choking on the 'previous_attributes' element.

This is the Stripe SDK code that I'm calling. I've verified that the responseJsonString variable is populated with the JSON string:

```java
Event event = Event.GSON.fromJson(responseJsonString, Event.class);
```

Any ideas?

**Comment by stevehall19** [comment]
In the code (EventDataDeserializer ln 112-114 or so) it looks like "previous_attribute" is a special case and in this instance the JsonElement has a value of JsonNull. It may just be that a type check needs to be added here and return the empty map if the value is not of type JsonObject

`if("previous_attributes".equals(key)) {
				Map<String, Object> previousAttributes = new HashMap<String, Object>();
				if (element.getAsJsonObject() != null) {
					populateMapFromJSONObject(previousAttributes, element.getAsJsonObject());
				}
				eventData.setPreviousAttributes(previousAttributes);
			}`

Becomes

`if("previous_attributes".equals(key)) {
				Map<String, Object> previousAttributes = new HashMap<String, Object>();

                                if (entry.getValue() instanceof JsonObject) {
				   if (element.getAsJsonObject() != null) {
					populateMapFromJSONObject(previousAttributes, element.getAsJsonObject());
				   }
                                }
				eventData.setPreviousAttributes(previousAttributes);
			}`

**Comment by olivierbellone** [comment]
This looks eerily similar to issue #183. I'll investigate further.

**Comment by stevehall19** [comment]
I does look similar. The null previous_attributes appears to be at root of it. 

Should have put this in the issue, I'm using Stripe API version 2016-03-07 and stripe-java version 2.4.0

**Comment by olivierbellone** [comment]
Hey @stevehall19. We fixed this uphill so that the "Send test webhook" button will no longer send events with `previous_attributes=null` (which doesn't happen in practice). I also patched the Java library so that if will be able to handle such events if they ever happen for any reason.

**Comment by stevehall19** [comment]
Great! Thanks for your help.

Steve
