### ISSUE TITLE
"Unable to lazy-load stripe objects" for TransferTransactionCollection.autoPagingIterable()

### ISSUE THREAD

**Issue by sterfried** [stripe/stripe-java#292]
I may be doing this incorrectly, but when I use this flow:

	TransferCollection transfers = Transfer.list(transfer_params, request_options);
	Iterable<Transfer> transfer_i = transfers.autoPagingIterable();
	Iterator<Transfer> transfer_it = transfer_i.iterator();
	while (transfer_it.hasNext()){
		Transfer transfer = transfer_it.next();
		TransferTransactionCollection transactions = transfer.transactions(new HashMap<String, Object>(), request_options);
		Iterable<TransferTransaction> transactions_i = transactions.autoPagingIterable();
		Iterator<TransferTransaction> transactions_it = transactions_i.iterator();
		while (transactions_it.hasNext()){
			TransferTransaction transaction = transactions_it.next();
		}
	}

it works for what appears to be the first "page" but then throws an error: 

	java.lang.RuntimeException: Unable to lazy-load stripe objects
		at com.stripe.model.PagingIterator.next(PagingIterator.java:60)
		at com.stripe.model.PagingIterator.next(PagingIterator.java:12)
	Caused by: com.stripe.exception.InvalidRequestException: No such transfer: tr_****************; request-id: req_****************
		at com.stripe.net.LiveStripeResponseGetter.handleAPIError(LiveStripeResponseGetter.java:591)
		at com.stripe.net.LiveStripeResponseGetter._request(LiveStripeResponseGetter.java:443)
		at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:65)
		at com.stripe.net.APIResource.request(APIResource.java:133)
		at com.stripe.net.APIResource.requestCollection(APIResource.java:150)
		at com.stripe.model.PagingIterator.list(PagingIterator.java:83)
		at com.stripe.model.PagingIterator.next(PagingIterator.java:55)
		
I noticed this issue _may_ have been addressed for a different collection for Issue #264 .

I attempted to transpose the format described in https://github.com/stripe/stripe-java/issues/264#issuecomment-199552752 but the TransferTransactionCollection.autoPagingIterable() doesn't accept the same parameters and it threw the same exception in that format (for loop, but with parameters).

I was using v. 1.4.1.1 but updated to 2.5.0 hoping it would be addressed, but no difference.

**Comment by olivierbellone** [comment]
Hi @sterfried. I suspect the root of the issue lies with the API, not with the Java library. Would you mind writing to support using the form at https://support.stripe.com/email? Make sure to include the complete stack trace, with the uncensored transfer and request IDs.

**Comment by sterfried** [comment]
@olivierbellone Thanks for the quick response! I will do that and will update if possible.

**Comment by olivierbellone** [comment]
Also, just as an FYI, you can simplify your code using [enhanced for](https://docs.oracle.com/javase/specs/jls/se7/html/jls-14.html#jls-14.14.2) loops:

```java
Iterable<Transfer> itTransfers = Transfer.list(transferParams, requestOptions).autoPagingIterable();
for (Transfer transfer : itTransfers) {
    Iterable<TransferTransaction> itTransferTransactions = transfer.transactions(new HashMap<String, Object>(), request_options).autoPagingIterable();
    for (TransferTransaction transaction : itTransferTransactions) {
        // Do something with transaction
    }
}
```

**Comment by sterfried** [comment]
Yeah I saw that in the comment I referenced so tried that out, but didn't fix the issue. I'll use that going forward though, thanks for the tip!

**Comment by olivierbellone** [comment]
So this is probably a bug in the bindings after all. My understanding is that you are correct and it's basically the same issue as #264.

[`Transfer.transactions()`](https://github.com/stripe/stripe-java/blob/a074e49146e4612619856c0ccf2782de690b3c70/src/main/java/com/stripe/model/Transfer.java#L344) returns a `TransferTransactionCollection`, and `TransferTransactionCollection` extends `StripeCollection`.

The patch for #264 (#275) was implemented in `StripeCollectionAPIResource`, not `StripeCollection`.

I'm wondering if we can simply make `TransferTransactionCollection` extends `StripeCollectionAPIResource` -- in fact, I tried it and it does seem to work, but I'm wary of the side effects that could be introduced by this change.

cc @brandur @tetrakai since you both were involved with #275.

**Comment by sterfried** [comment]
Thank you for the update -- I had a feeling, the two issues were so similar in context!

**Comment by olivierbellone** [comment]
@sterfried We'll try to fix this ASAP, but in the meantime, you can get around this by handling the pagination yourself (for the transactions). Something like this should work:

```java
Iterable<Transfer> itTransfers = Transfer.list(new HashMap<String, Object>(), requestOptions).autoPagingIterable();
for (Transfer transfer : itTransfers) {
    Map<String, Object> listParams = new HashMap<String, Object>();
    TransferTransactionCollection transactionCollection = transfer.transactions(listParams, requestOptions);
    List<TransferTransaction> transactions = transactionCollection.getData();

    do {
        for (TransferTransaction transaction : transactions) {
            // Do something with transaction
        }

        listParams.put("starting_after", transactions.get(transactions.size() - 1).getId());
    } while (transactionCollection.getHasMore());
}
```

**Comment by brandur** [comment]
Hey guys, sorry about the trouble here! It looks like @olivierbellone already determined the heart of the issue, which seems to be due to an omission on my part in #275.

I've opened #294 as a possible fix for the time being. Let me know if you have any questions or comments.

**Comment by brandur** [comment]
Hi @sterfried, version 2.5.1 should now contain helpers for _all_ collection classes, which should allow you to pass parameters and request options to your transactions list in the example you provided above. Sorry about the trouble here!
