### ISSUE TITLE
Fileupload from Google Appengine

### ISSUE THREAD

**Issue by sowdri** [stripe/stripe-java#299]
File objects cannot be created on Google App Engine. So in order to upload documents for id_verification it will be great if FileUpload can support InputStreams such that files from GCS (Google Cloud Storage) or direct multi-part file uploads could be pushed to stripe.

**Comment by brandur** [comment]
+1.

This is very similar to stripe/stripe-python#227, and as noted there, we have a bit of an issue in that backend (thanks to Rack) in that incoming multipart file uploads without a filename are not currently handled. One of my colleagues who is coming back after finishing up school has expressed interesting in fixing this problem though.

I'd suggest we wait for that fix; once it's in, it should be relatively easy to change stripe-java's implementation to take advantage of it.

**Comment by praboud** [comment]
@sowdri as was surfaced in the other issue, you can upload files to Stripe directly from the browser with your publishable API key. [1] IMHO, this is overall better for most use cases than forwarding the file upload through your server, and would also get around the proximate issue ie: that GAE doesn't support creating files.

[1] https://stripe.com/docs/file-upload

**Comment by sowdri** [comment]
Thank you. I'll upload directly from the browser for now.

**Comment by sowdri** [comment]
Basically the problem is that, first the file has to be uploaded to stripe directly via. browser, then I've to get the file_id and send it to the server and then associate it as id_verification document. Doable nonetheless. Otherwise I can do it in a single shot. And since we are a platform we are doing id_verification for multiple clients, it will just be more convenient if we have the support for upload from the server. 

Thank you guys.

**Comment by praboud** [comment]
It's always two requests to Stripe, though - one to upload the file to Stripe, and one to set `account.legal_entity.verification.document` to the file token you got in the first step. This doesn't change whether the upload step is done by the client or the server.

To make explicit what I glossed over previously, doing the file upload from the browser keeps sensitive files off your servers, which makes your security story here easier. Even after stripe-java does support uploading from an `InputStream`, I'd argue that doing the upload from the client is still strictly better than proxying the request through your server.

**Comment by brandur** [comment]
Thanks @praboud!

**Comment by musby** [comment]
Hi I've been searching for ages about how to upload directly from the browser, as is suggested in this case of using Stripe with Google App Engine, so I was hoping I could continue the conversation here on how to accomplish that.

I have been trying with AJAX but from my effort and research it seems it is not possible to get the path to the local file because of security reasons.  The code below shows the closest I've gotten, however I don't know how to upload an image through the browser without it touching the server.  The console returns an error of "Invalid file: must be uploaded in a multipart/form-data request".

Next I will try using Jquery Form Plugin, however I don't know if I will have any success with that.

`var formData = new FormData($('#theHTMLForm')[0]);
		var sendarray={purpose:"identity_document", file:formData};
		sendarray=JSON.stringify(sendarray);

                $.ajax({
			type:'POST',
			url: 'https://uploads.stripe.com/v1/files',
			data: sendarray,
			mimeType: "multipart/form-data",
			headers: {
				"Authorization": "Bearer STRIPEPUBLISHABLEKEY"
			},
			contentType: 'application/json',
			processData: false,
			success:function(data){
				alert('success');
				console.log(data);
			},
			error: function(data){
				alert('error');
				console.log(data);
			}
		});`

**Comment by remi-stripe** [comment]
@musby This example code should work: https://jsfiddle.net/captainapollo/d8yd3761/

**Comment by musby** [comment]
@remi-stripe 

It worked!!  You are a life saver my friend.  I was working on that for like 3 days.

**Comment by dpetrovics-stripe** [comment]
Glad we could help!

**Comment by ob-stripe** [comment]
This was fixed by #544 and released in 5.48.0.
