### ISSUE TITLE
showing me com.stripe.model.Source is not present

### ISSUE THREAD

**Issue by nitesh-jain-avalara** [stripe/stripe-java#306]
I have added all required jars in my build path.I copied the whole code from here .
showing  me that import   com.stripe.model.Source is not present.
Please help me , what could be possible resolution.

Thanks,
Nitesh

**Comment by olivierbellone** [comment]
@nitesh-jain-avalara GitHub issues are mostly for bugs and feature requests about the Java library itself. If you need help with using the library itself, you need to write to support: https://support.stripe.com/email.

That said, if you have both `stripe-java-2.8.0.jar` and `gson-2.2.4.jar` in your classpath, you should be able to import everything from `com.stripe`.
