### ISSUE TITLE
Wrong customer_balance type

### ISSUE THREAD

**Issue by Tritoniwe** [stripe/stripe-java#308]
https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/Customer.java#L16 
it is specified as Integer, however, it is possible to set a number that exceeds int max value through the dashboard or via API.

**Comment by olivierbellone** [comment]
Hey @Tritoniwe, thanks for reporting this. This looks easy enough to fix, so we should have a patched version released shortly.

**Comment by appmagnetics** [comment]
Hi, any news on new release? We are experiencing the same issue.

**Comment by brandur** [comment]
Oops, sorry about the delay here! We've got a pull open in #309 and will push it through soon.

**Comment by brandur** [comment]
Released as 3.0.0!
