### ISSUE TITLE
NoSuchMethodError exception on Charge.create

### ISSUE THREAD

**Issue by VolodymyrTkachuk** [stripe/stripe-java#310]
I tried on versions 2.7 and 2.8 and in both cases got same exception. Here is my code:

```
RequestOptions requestOptions =   RequestOptions.builder().setApiKey(STRIPE_PRIVATE_KEY).build();
Map<String, Object> chargeMap = new HashMap<String, Object>();
chargeMap.put("amount", AMOUNT);
chargeMap.put("currency", "usd");
chargeMap.put("source", token);
chargeMap.put("description", "Example charge");
Charge charge = Charge.create(chargeMap, requestOptions);
```

And I'm getting an exception: 

> java.lang.NoSuchMethodError: com.google.gson.Gson.getDelegateAdapter(Lcom/google/gson/TypeAdapterFactory;Lcom/google/gson/reflect/TypeToken;)Lcom/google/gson/TypeAdapter;
> 	at com.stripe.model.ExternalAccountTypeAdapterFactory.create(ExternalAccountTypeAdapterFactory.java:25)
> 	at com.google.gson.Gson.getAdapter(Gson.java:353)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
> 	at com.google.gson.Gson.getAdapter(Gson.java:353)
> 	at com.google.gson.Gson.fromJson(Gson.java:754)
> 	at com.google.gson.Gson.fromJson(Gson.java:721)
> 	at com.google.gson.Gson.fromJson(Gson.java:670)
> 	at com.google.gson.Gson.fromJson(Gson.java:642)
> 	at com.stripe.net.LiveStripeResponseGetter._request(LiveStripeResponseGetter.java:446)
> 	at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:65)
> 	at com.stripe.net.APIResource.request(APIResource.java:137)
> 	at com.stripe.model.Charge.create(Charge.java:425)

Looks like some configuration problem, but I did not find what is wrong.

Any ideas, what may be wrong?

**Comment by olivierbellone** [comment]
That's a weird one. Maybe it's a version conflict? Is there anything in your project that uses a different version of Gson than the one used by our Java bindings (2.2.4)?

**Comment by VolodymyrTkachuk** [comment]
@olivierbellone Yes, I missed that, 2.1 also was referenced from the project. I cleared dependencies, and now it works as designed.

**Comment by olivierbellone** [comment]
Awesome, thanks for taking the time to close the loop!

**Comment by stephenostermiller** [comment]
I ran into this as well.   Stripe is not compatible with gson-2.1.jar which is what my project had been using.
