### ISSUE TITLE
Account `delete()`-method should not require arguments

### ISSUE THREAD

**Issue by andrewnelder** [stripe/stripe-java#312]
According to the documentation, the Account `delete()`-method requires no arguments; however, our implementation requires that you pass at least a `null`-value.

[Stripe API Docs - Delete Account (Java)](https://stripe.com/docs/api/java#delete_account)

[Account.java @ L297 - L307](https://github.com/stripe/stripe-java/blob/728d17f1a26c6b0ac13e83490af9922a006612bc/src/main/java/com/stripe/model/Account.java#L297-L307)

**Comment by brandur** [comment]
Good catch @andrewnelder! Added a patch in #314.

**Comment by ob-stripe** [comment]
Fixed in #342.
