### ISSUE TITLE
Request api for scala

### ISSUE THREAD

**Issue by skanel** [stripe/stripe-java#319]
Hi Stripe,

I did not found the api for scala, Do you have any recommend for scala?

Thanks

**Comment by brandur** [comment]
Hi @skanel,

Sorry, but we don't maintain an official SDK for Scala :/ Although not the most optimal solution, you should be able to call into this one (stripe-java) from your Scala code.

There are a few unofficial libraries out there, but I couldn't find any that appear to be actively maintained, so you may have to use them at your own risk.

I'm going to close this out, but let us know if you have any other questions.
