### ISSUE TITLE
"Unable to lazy-load stripe objects" for TransferTransactionCollection.autoPagingIterable() (Again)

### ISSUE THREAD

**Issue by sterfried** [stripe/stripe-java#321]
I'm getting the same issue as before with #292 and wanted to make sure I was doing this correctly. I've upgraded the library to the latest version, 2.10.0. and Stripe.VERSION reports the same.

Below is the snippet in question:

`String stripe_user_id = "acct_XXXXXXXXXXXX";`
`RequestOptions request_options = RequestOptions.builder().setStripeAccount(stripe_user_id).build();`
`Map<String, Object> transfer_params = new HashMap<String, Object>();`
`Map<String, Object> created_params = new HashMap<String, Object>();`
`created_params.put("gte", 1451606400);`
`created_params.put("lte", 1474666292);`
`transfer_params.put("created", created_params);`
`Iterable<Transfer> transfer_it = Transfer.list(transfer_params, request_options).autoPagingIterable();`
`for (Transfer transfer : transfer_it) {`
`Map<String, Object> list_params = new HashMap<String, Object>();`
`TransferTransactionCollection transactions = transfer.transactions(new HashMap<String, Object>(), request_options);`
`Iterable<TransferTransaction> transactions_list = transactions.autoPagingIterable();`
`for (TransferTransaction transaction : transactions_list) {`
`System.out.println(transaction.getId());`
`}`
`}`

I'm attempting to get a connected account's transfers created within a timeframe, then get the associated transaction IDs for each balance transfer.

When I attempt to do so, for SOME dates it works fine, but others I get this exception:

`java.lang.RuntimeException: Unable to lazy-load stripe objects
        at com.stripe.model.PagingIterator.next(PagingIterator.java:60)
        at com.stripe.model.PagingIterator.next(PagingIterator.java:12)
`
`...`
`Caused by: com.stripe.exception.InvalidRequestException: No such transfer: tr_XXXXXXXXX; request-id: req_9FXCuQPtSOv4nE
        at com.stripe.net.LiveStripeResponseGetter.handleAPIError(LiveStripeResponseGetter.java:591)
        at com.stripe.net.LiveStripeResponseGetter._request(LiveStripeResponseGetter.java:443)
        at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:65)
        at com.stripe.net.APIResource.request(APIResource.java:142)
        at com.stripe.net.APIResource.requestCollection(APIResource.java:159)
        at com.stripe.model.PagingIterator.list(PagingIterator.java:83)
        at com.stripe.model.PagingIterator.next(PagingIterator.java:55)
`

I have been trying various alternative solutions, but it doesn't seem to help.

If anything is obviously wrong, thanks for your help debugging my code, otherwise, since it is the same error as #292 I wanted to check-in in case you guys had more insight on the cause.

Thanks either way!!

**Comment by brandur** [comment]
Hey @sterfried, sorry to hear about the continuing trouble here :$ @dpetrovics is going to take a look into this and we'll hopefully have something for you soon.

**Comment by sterfried** [comment]
@brandur No problem. It could possibly be my implementation, but the last time this same error popped up, it was out of my hands so figured I'd see what you guys thought.

Thanks for looking into it!

**Comment by dpetrovics** [comment]
Hi @sterfried - sorry for the delay! I'm looking at this now and hope to get back to you shortly.

**Comment by dpetrovics** [comment]
Hi @sterfried - as of now I haven't been able to reproduce your error with a test account. The auto pagination for Transfers seems to work well for me across page boundaries. If you'd like, can you email me (dpetrovics@stripe.com) with a code snippet that has dates that consistently fail for you? It might help in identifying what you're seeing.

**Comment by sterfried** [comment]
@dpetrovics Great, thanks for your help! I've sent along an email with some example code.

**Comment by dpetrovics** [comment]
HI @sterfried , thanks again for discovering this - we should have a fix coming in #322!

**Comment by sterfried** [comment]
@dpetrovics Thanks for the quick response!

**Comment by dpetrovics** [comment]
No problem! We've merged in the fix and released as `2.10.1`. Closing this now, but let us know if it doesn't solve your issue.
