### ISSUE TITLE
Bug in OrderReturnCollection

### ISSUE THREAD

**Issue by semitop7** [stripe/stripe-java#350]
https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/OrderReturnCollection.java
In OrderReturnCollection Should be so:
```
public class OrderReturnCollection extends StripeCollection<OrderReturn> {
}
```
Replace **Order** to **OrderReturn**.

**Comment by brandur-stripe** [comment]
We've released a patch for this in 4.0.0. Thank you for reporting the problem!
