### ISSUE TITLE
Add new field and Expandable object support to Order

### ISSUE THREAD

**Issue by semitop7** [stripe/stripe-java#351]
https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/Order.java

It is possible to add some fields to Order.class, such as:
```
OrderReturnCollection returns;
Long amountReturned;
```
```
ExpandableField<Charge> charge;
ExpandableField<Customer> customer;
```
Using API Endpoint https://api.stripe.com/v1 in the JSON response from server they are present.

**Comment by brandur-stripe** [comment]
We've released a patch for this in 4.0.0. Thank you for reporting the problem!
