### ISSUE TITLE
`rule`-attribute of ChargeOutcome is broken

### ISSUE THREAD

**Issue by anelder-stripe** [stripe/stripe-java#355]
API Version [2017-02-14](https://stripe.com/docs/upgrades#2017-02-14) changed the type of the '[rule](https://github.com/stripe/stripe-java/blob/dd9529f48388b26d08b4377335711b2ad0cfd875/src/main/java/com/stripe/model/ChargeOutcome.java#L9)'-attribute of `ChargeOutcome.java`.  Needs to either be replaced with a String-type or support expansion.  `ChargeOutcomeRule.java` may also need to be removed; depending on the outcome.

**Comment by anelder-stripe** [comment]
In order to make this a non-breaking change, we'll actually need to support both cases.  So expansion is likely the better option here.

**Comment by brandur-stripe** [comment]
Nice find!

I added an attempted fix in #356. Maintaining backwards compatibility is a little awkward though because the naming around `getOutcome` has been taken by the deprecated version, so I had to add a `getOutcomeID`, which is kind of a brand new convention that I just made up.

Given that charge outcomes are relatively new anyway, we may want to consider just releasing a breaking change instead. Thoughts?

**Comment by anelder-stripe** [comment]
I'm not opposed to a breaking change, provided we set in time somewhere that associates the current release with the previous API Version.  That being said, if we can get around it, we probably should.

We had talked about implementing more or less what you did, while we were discussing this async.  So from my perspective what you did is fairly peaceful and easy-enough to change later.

👍

**Comment by jjlueck-tock** [comment]
Quick note from someone waiting for a solution to this issue. Webhook events that come from Stripe for those of us on the latest Stripe API version and latest stripe-java API that happen to contain the String version of the outcome.rule field will fail to parse into an `Event` object. We encountered this last night.

**Comment by brandur-stripe** [comment]
@anelder-stripe After thinking about this a little more, I think adding the `getXXXId` style accessor is a pretty good idea. It's relatively consistent with the rest of the code, and allows us to introduce this type of change and stay backwards compatible. I had the implementation wrong in #356, but I think that #358 should now do it. Would you mind taking a look?

@jjlueck-tock Sorry about the delay! I think we should have a fix for this relatively soon.

**Comment by jjlueck-tock** [comment]
👍

**Comment by jjlueck-tock** [comment]
Hate to bug y'all on this issue, but any progress? we still can read some of our webhook events because of this.

**Comment by brandur-stripe** [comment]
Hi @jjlueck-tock, my apologies for the delay here. I just pushed a patch out in 4.1.0. Can you give that a shot?

**Comment by jjlueck-tock** [comment]
Yup, we'll push this into production tomorrow and I'll report back if we encounter any errors.
