### ISSUE TITLE
No three_d_secure attribute on the Card object

### ISSUE THREAD

**Issue by carlsverre** [stripe/stripe-java#371]
According to the docs the Card object should have a three_d_secure attribute.

https://stripe.com/docs/api#card_object-three_d_secure
https://stripe.com/docs/testing#3ds-cards

I have looked around the code and it doesn't seem like that is being exposed anywhere in the stripe-java API.  Am I missing something or is this an oversight.

I would switch over to the Source api (rather than creating Cards) however I can't see how to add a Source to a Customer so that option seems out as well.

**Comment by brandur-stripe** [comment]
Hi there, this is an oversight, and we're sorry about the trouble. I've added a fix in #372 and we should have it rolled out relatively soon.

Thanks for the report!

**Comment by brandur-stripe** [comment]
Released as version 4.7.0.

**Comment by carlsverre** [comment]
Thanks!

**Comment by carlsverre** [comment]
@brandur-stripe I just tested this version with 4000000000003063 which should have three_d_secure set as required and instead `getThreeDSecure` is returning null for that card.  Any idea whats going on?

**Comment by ob-stripe** [comment]
@carlsverre The `three_d_secure` attribute is only returned for accounts that have been invited into our "old" 3DS beta. For all other accounts, no `three_d_secure` attribute is returned on card objects, so it's expected that `getThreeDSecure()` would return `null` in this case.

If you want to use 3D Secure on a newer account, you need to use our new sources API: https://stripe.com/docs/sources/three-d-secure.

**Comment by carlsverre** [comment]
I see... good to know.  Does this library support adding a Source to a Customer?  I see that in the GUI this should be possible - but I couldn't find a way to do it in this library.

**Comment by ob-stripe** [comment]
@carlsverre Yes. This isn't clearly documented, but you can add attach a source to a customer just like cards/bank accounts:

```java
Customer customer = Customer.retrieve("cus_...");
Map<String, Object> params = new HashMap<String, Object>();
params.put("source", "src_...");
customer.getSources().create(params);
```

Note that the source must be chargeable before it can be attached to a customer.

**Comment by carlsverre** [comment]
Thanks @ob-stripe, I will try switching to that.  Would love to see the docs updated to include that.
