### ISSUE TITLE
Complete javadoc for com.stripe.net.Webhook.Signature#verifyHeader

### ISSUE THREAD

**Issue by a-panchenko** [stripe/stripe-java#377]
There is a need to specify that `tolerance` parameter of `com.stripe.net.Webhook.Signature#verifyHeader` method is in seconds, rather than milliseconds. Currently, it's unclear from the javadoc unless one read the code of the method.

**Comment by ob-stripe** [comment]
PR in #378.

**Comment by ob-stripe** [comment]
Closed via #378.
