### ISSUE TITLE
Missing Event account field

### ISSUE THREAD

**Issue by pibernardi** [stripe/stripe-java#379]
The API Upgrade of 2017-05-25 says that 

"The user_id field of Connect-related event objects (and webhooks) has been renamed to account."

https://stripe.com/docs/upgrades

But the Event class still has the old "userId" field!

**Comment by ob-stripe** [comment]
Hey @pibernardi, thanks for reporting this. There is already a PR in the works for this: https://github.com/stripe/stripe-java/pull/374. An updated version of the library should be released soon.

**Comment by ob-stripe** [comment]
Closed via #374.
