### ISSUE TITLE
Problem with verified account and payouts

### ISSUE THREAD

**Issue by ColCol94** [stripe/stripe-java#397]
Hello,

Sorry to bother on here as I could not receive a response via email. Is there any reason why a verified account might be receiving payout push backs daily for a week? Not my first payment, just a standard deposit. Auto deposit set to on daily, as well as never having received a chargeback or fraudulent charge. If I try for a manual payout, message reds 'Cannot create payouts; please contact support@stripe.com with details, so we can help.' 

Please advise,
Colin

**Comment by remi-stripe** [comment]
@ColCol94 Unfortunately, this form is used to discuss issues with our Java library. Your question is really specific to your own Stripe account and you need to talk to our support team directly from our contact form here: https://support.stripe.com/email
