### ISSUE TITLE
Account.retrieve() always gets legalEntity Null

### ISSUE THREAD

**Issue by santiarias** [stripe/stripe-java#400]
Account.retrieve()  always gets legalEntity null 

https://stripe.com/docs/api#account  shows the right values. 

<dependency>
        <groupId>com.stripe</groupId>
        <artifactId>stripe-java</artifactId>
        <version>5.7.1</version>
    </dependency>

java 1.8

**Comment by remi-stripe** [comment]
@santiarias This is not a bug with the library. It's likely that you are retrieving an account that is not  a Custom account. The `legal_entity` hash is only returned on accounts of type Custom.
