### ISSUE TITLE
OAuth TokenResponse is missing few fields

### ISSUE THREAD

**Issue by sowdri** [stripe/stripe-java#408]
[According to the docs](https://stripe.com/docs/connect/standard-accounts) OAuth token response returns the following data:

```
{
  "token_type": "bearer",
  "stripe_publishable_key": "{PUBLISHABLE_KEY}",
  "scope": "read_write",
  "livemode": false,
  "stripe_user_id": "{ACCOUNT_ID}",
  "refresh_token": "{REFRESH_TOKEN}",
  "access_token": "{ACCESS_TOKEN}",
}
```

The [TokenResponse](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/oauth/TokenResponse.java) only captures the following:

```
public class TokenResponse extends StripeObject {
	Boolean livemode;
	String scope;
	String stripeUserId;
        // ...
}
``` 

Note: The document recommends to store only the `stripeUserId`, but the choice has to be made by the developer and the sdk should capture everything returned by the response. 

Thanks all for the great work.

**Comment by ob-stripe** [comment]
Hey @sowdri. It was a deliberate decision to leave out those fields, as there's basically no reason for a new Connect integration to not use the `stripe_user_id` field for everything.

It's certainly something we can reconsider, but for now we prefer to nudge Java users in the right direction by "forcing" them to use the newer method.

I'm going to close the issue, but if you feel very strongly that this is something that should be in the Java library, feel free to reply with details about your use case.
