### ISSUE TITLE
Error date subscription

### ISSUE THREAD

**Issue by Matiyeu** [stripe/stripe-java#429]
Hello,

when im print date created of an subscription with  
`subscription.getCreated()`
Then i've got this:

> 1511646425

> 

 but "1511646425" correspond to 18/01/70 11:54 

 **wut ?? Test mode ?** 

Thanks 👍

**Comment by codylerum** [comment]
https://stripe.com/docs/api#subscriptions

created is `Time at which the object was created. Measured in seconds since the Unix epoch.`

See https://www.epochconverter.com/

**Comment by Matiyeu** [comment]
Thanks ;)
