### ISSUE TITLE
Dispute.charge is not Expandable

### ISSUE THREAD

**Issue by PeterDimov** [stripe/stripe-java#431]
Dispute.charge is ```Expandable``` according to API docs: https://stripe.com/docs/api#dispute_object

However the current implementation expects a string only: https://github.com/stripe/stripe-java/blob/e2d2fb0fb9cf2a9a6b34e6d69e5993b08f88c6d5/src/main/java/com/stripe/model/Dispute.java#L19

Which causes deserialization with expanded charge to fail with:
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT
```
I have an adjustment balance transaction for a Dispute that causes the entire BalanceTransactionCollection load to fail because of that.

**Comment by ob-stripe** [comment]
Pushed a fix fix for this in #432.
