### ISSUE TITLE
SubscriptionItems cannot be deleted with parameters

### ISSUE THREAD

**Issue by pguillebert** [stripe/stripe-java#437]
Currently I cannot pass extra parameters to the `delete()` method for SubscriptionItems. 

In my use case, I need to disable proration ( https://stripe.com/docs/api/java#delete_subscription_item-prorate ) for a delete call.

The fix is very simple, should I provide a PR for this ? 

Thanks

**Comment by remi-stripe** [comment]
@pguillebert A PR would be awesome now that you already have the fix ready. We can then review and release a version with those changes!

**Comment by ob-stripe** [comment]
Oops, did not notice that you had already committed a fix for this in your fork @pguillebert 🤦‍♂️ 

Ah well, the fix is quite trivial as you pointed out and I added a test while I was at it. PR is in #438.
