### ISSUE TITLE
Can not construct instance of com.stripe.model.StripeObject

### ISSUE THREAD

**Issue by mjain1990** [stripe/stripe-java#450]
I am using spring boot with jackson. I am trying to configure a webhook resource and expecting Event Object as request body. But when I get a webhook call my resource reject that request with 400 because jackson is not able to bind it. What it says is 

```
Can not construct instance of com.stripe.model.StripeObject: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@626f4396; line: 7, column: 15] (through reference chain: com.stripe.model.Event["data"]->com.stripe.model.EventData["object"])
```

I searched for its solution and it says to add JsonTypeInfo on StripeObject. I don't want to create a another class in my own project for the same. Is there something which I am missing?

**Comment by ob-stripe** [comment]
Hi @mjain1990. stripe-java uses Gson as its JSON library, not Jackson.

You can deserialize JSON payloads into `Event` objects using the `Webhook.constructEvent()` method, which will also let you verify webhook signatures. You can find more information here: https://stripe.com/docs/webhooks/signatures#verify-official-libraries.
