### ISSUE TITLE
Checkout token issue

### ISSUE THREAD

**Issue by fran-mv** [stripe/stripe-java#460]
Hi, I'm having problems when getting the checkout token. I receive the (credit or debit) card with the field currency=null instead of currency="eur". Is that the expected behaviour? In that case I'm not able to modify the card contained in the token so as it has the currency field != null. I need that to add a card to a custom account

I provide here all the information:

**This is the html code that I use to make the form:**

```
<!DOCTYPE html>
<html>
    <head>
        <title>Mustaid GO</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div>
            <form action="your-server-side-code" method="POST">
                <script
                    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="pk_test_QqkeiO6Sef3bcSQrukq58pYi"
                    data-name="Ash Mostaza Beta"
                    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                    data-locale="auto"
                    data-zip-code="true"
                    data-currency="eur"
                    data-billing-address="true"
                    data-email="xx@xx.com"
                    data-label="Introducir Tarjeta"
                    data-panel-label="Confirmar">
                </script>
            </form>
        </div>
    </body>
</html>
```

**And this is the card token that I always receive:**
```
<com.stripe.model.Token@815594218 id=tok_1C0VxzEY9hE5pJnZeU9ryze2> JSON: {
  "id": "tok_1C0VxzEY9hE5pJnZeU9ryze2",
  "object": "token",
  "amount": null,
  "bank_account": null,
  "card": {
    "address_city": null,
    "address_country": null,
    "address_line1": null,
    "address_line1_check": null,
    "address_line2": null,
    "address_state": null,
    "address_zip": "25800",
    "address_zip_check": "pass",
    "available_payout_methods": null,
    "brand": "Visa",
    "country": "US",
    "currency": null,
    "cvc_check": "pass",
    "default_for_currency": null,
    "dynamic_last4": null,
    "exp_month": 12,
    "exp_year": 2034,
    "fingerprint": "mAHUsqElSEWe8r7P",
    "funding": "credit",
    "last4": "4242",
    "name": "xxxx",
    "recipient": null,
    "status": null,
    "three_d_secure": null,
    "tokenization_method": null,
    "description": null,
    "iin": null,
    "issuer": null,
    "type": null,
    "id": "card_1C0VxyEY9hE5pJnZxVF1jbVQ",
    "object": "card",
    "account": null,
    "customer": null,
    "metadata": {}
  },
  "client_ip": "xx.x.xxx.xx",
  "created": 1519828295,
  "currency": null,
  "email": "xx@xx",
  "livemode": false,
  "type": "card",
  "used": false
}
```

I was not able to do this tasks: 

`String token;`

1) Add the card to a custom account with this token:
```
Map<String, Object> accountParams = new HashMap<>();
accountParams.put("external_account", token);
Account account = Account.retrieve(accountid, null);
```  
Error in the next line with stack trace `com.stripe.exception.InvalidRequestException: You must provide a card that has the 'currency' field set when adding a card to a Stripe account.; request-id: req_nTSp0ctxSNGLdi`
```  
account.getExternalAccounts().create(accountParams); 
```  
However, I have no problems when adding it to a customer. 

2) Modify the card of the token:
```
Card card;
Token rtoken = Token.retrieve(token);

card = rtoken.getCard();
card.setCurrency("eur");
rtoken.setCard(card);
```
This way the  `Token.retrieve(token)` token object has the currency field = `null`, though the card and the rtoken objects don't. I have no idea about how to generate another token id from this updated card or this updated rtoken.

3) Modify the card of the token through this other way:
```
Map<String, Object> updateParams = new HashMap<>();
updateParams.put("object", "card");
updateParams.put("exp_month", 8);
updateParams.put("exp_year", 2020);
updateParams.put("number", "4242424242424242");
updateParams.put("currency", "eur");
```  
Error in the next line with stack trace `com.stripe.exception.APIConnectionException: IOException during API request to Stripe (https://api.stripe.com): null Please check your internet connection and try again. If this problem persists,you should check Stripe's service status at https://twitter.com/stripestatus, or let us know at support@stripe.com.`
```  
card.update(updateParams);
```
 

I need to add cards to my connected accounts because I have to do transfers to my clients. Otherwise my Stripe integration would have no sense.

I will thank any help 😘

**Comment by ob-stripe** [comment]
@fran-mv This is expected behavior. Tokens created by Checkout will always have `currency` set to `null`, so they cannot be used as external accounts for custom accounts.

You must use Elements to create tokens with the `currency` parameter. Here's a basic example: https://jsfiddle.net/ywain/rprufyg5/.

Note that using debit cards as external accounts is currently only supported for US accounts, so the only supported currency is `usd`. While you could create a card token with `currency=eur`, you wouldn't be able to use this token to create an external account for a custom account.

This isn't an issue with the Java library, so I'm going to close this issue. If you have more questions, please reach out to support at https://support.stripe.com/email.
