### ISSUE TITLE
Adding OSGi Header

### ISSUE THREAD

**Issue by kmhughes** [stripe/stripe-java#463]
The system I have runs inside of Apache Karaf, an OSGi container that runs on the JVM.

I am thinking of using Stripe for our billing, but would need the library to work with OSGi. All this requires is some changes made to the META-INF/MANIFEST.MF file in your jar, it does not touch bytecode or add classes to the jar. The nice thing about these changes is that they have zero effect on anyone not using OSGi, but does help those of us who do. GSON, your only dependency, is already an OSGi bundle.

I can make the appropriate changes to your gradle file if you would be willing to accept a patch.

**Comment by brandur-stripe** [comment]
Hi @kmhughes, I haven't worked with OSGi at all and probably don't grasp all the details of this kind of change, but if it's benign like you suggest, then yes, we'll accept a patch. Thanks for offering to make the changes yourself!

**Comment by kmhughes** [comment]
Hi @brandur-stripe, cool thanks! So glad you folks moved to Gradle, it makes this change very, very simple. The Maven version is a little more involved.

**Comment by kmhughes** [comment]
Hi @brandur-stripe, I have added in the Gradle lines to add in the OSGi headers. I have tested in my OSGi container and it works perfectly.

You can see what the OSGi plugin did below.

`Manifest-Version: 1.0
Implementation-Title: stripe-java
Bundle-SymbolicName: stripe-java
Implementation-Version: 5.33.2
Bundle-ManifestVersion: 2
Bnd-LastModified: 1521647353000
Import-Package: com.google.gson;version="[2.8,3)",com.google.gson.anno
 tations;version="[2.8,3)",com.google.gson.reflect;version="[2.8,3)",c
 om.google.gson.stream;version="[2.8,3)",com.stripe,com.stripe.excepti
 on,com.stripe.exception.oauth,com.stripe.model,com.stripe.model.oauth
 ,com.stripe.net,javax.crypto,javax.crypto.spec,javax.net.ssl
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
Tool: Bnd-3.4.0.201707252008
Implementation-Vendor: Stripe, Inc. (https://stripe.com)
Export-Package: com.stripe,com.stripe.exception,com.stripe.exception.o
 auth;uses:="com.stripe.exception",com.stripe.model;uses:="com.google.
 gson,com.google.gson.reflect,com.stripe.exception,com.stripe.net",com
 .stripe.model.oauth;uses:="com.stripe.model",com.stripe.net;uses:="co
 m.google.gson,com.stripe.exception,com.stripe.exception.oauth,com.str
 ipe.model,com.stripe.model.oauth,javax.net.ssl"
Bundle-Version: 5.33.2
Bundle-Name: stripe-java
Created-By: 1.8.0_151 (Oracle Corporation)
`

**Comment by brandur-stripe** [comment]
@kmhughes Once again, this is awesome. Thanks for testing, and thanks for the contribution!

**Comment by kmhughes** [comment]
You are most welcome, @brandur-stripe . Many thanks for accepting the pull.

**Comment by ob-stripe** [comment]
Released in 5.33.3. Thanks @kmhughes!
