### ISSUE TITLE
.toString returns NullPointerException when called for an Order

### ISSUE THREAD

**Issue by elenacanovi** [stripe/stripe-java#465]
Hi all,

I have successfully created some test orders. However, when I try to call the method `toString` for an `Order`,  I get the following error:
```
NullPointerException   com.google.gson.JsonPrimitive.isPrimitiveOrString (JsonPrimitive.java:282)
```

Note that if I call all the other `Order` methods (such as `getId`), everything works fine. 

Thanks.

**Comment by ob-stripe** [comment]
Hey @elenacanovi, thanks for the report and sorry for the inconvenience. I've prepared a patch for this issue and we will release an update for the library shortly.

**Comment by elenacanovi** [comment]
Thanks!
