### ISSUE TITLE
JsonMappingException exception is throwing when retrieving a customer

### ISSUE THREAD

**Issue by nomadus** [stripe/stripe-java#496]
The code was working with an older stripe version 3.5.0 library, but with the newest library it throws:

> Caused by: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.stripe.net.StripeResponse and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.stripe.model.Customer["lastResponse"])

Here is the code pieces:
In the serviceImpl class I retrieve Customer object via
`customer = Customer.retrieve(currentAccount.getCustomerStripeId());`

In the controller class:
```
         Customer currentCustomer = stripeService.findCustomerByUserId(id);

        //StripeResponse response = currentCustomer.getLastResponse();
        //System.out.println("the customer is " + response.body());
        //Customer card = APIResource.GSON.fromJson(response.body(), Customer.class);
        if (currentCustomer == null) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<>(currentCustomer, HttpStatus.OK);
```
This piece of code throws above error. When I re-write the method as below:

 

```
        Customer currentCustomer = stripeService.findCustomerByUserId(id);
        StripeResponse response = currentCustomer.getLastResponse();
        System.out.println("the customer is " + response.body());
        Customer customer = APIResource.GSON.fromJson(response.body(), Customer.class);
        if (currentCustomer == null) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<>(customer, HttpStatus.OK);
```
The customer is returned with no issues. What have changed in the library? Do I have to re-write my code base as above?

**Comment by ob-stripe** [comment]
Hi @nomadus. I think this issue is caused by the addition of the [`lastResponse`](https://github.com/stripe/stripe-java/blob/a0f572267b6871c7ca03ed8a9e53a7470bd81130/src/main/java/com/stripe/model/StripeObject.java#L45) attribute on `StripeObject`s in version [5.24.0](https://github.com/stripe/stripe-java/blob/master/CHANGELOG.md#5240---2017-11-28) (#421).

The library uses Gson as its JSON library, and using `APIResource.GSON.fromJson()` is indeed the canonical way of deserializing JSON payloads into Stripe objects.

You can go with your rewritten method, or alternatively you can configure Jackson to ignore transient fields with [`PROPAGATE_TRANSIENT_MARKER`](https://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/MapperFeature.html#PROPAGATE_TRANSIENT_MARKER).

**Comment by dagetachew** [comment]
is this issue resolved yet ? I am getting the same exception just for passing ChargeCreateParams object to the charge.create() method. it works fine if I put spring.jackson.mapper.propagate-transient-marker=true in the properites file.
I am not implementing any of stripe interfaces and the below exception is thrown
""Type definition error: [simple type, class com.stripe.net.StripeResponse]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.stripe.net.StripeResponse and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.stripe.model.Charge["lastResponse"])

**Comment by ob-stripe** [comment]
Hi @dagetachew. I don't think this issue can be solved from the stripe-java library. stripe-java uses Gson as its JSON library, not Jackson, so we cannot ensure that Stripe objects will play nicely with Jackson.

The proper way to fix this would be to never use Jackson to serialize or deserialize Stripe objects from/to JSON. You can use the following methods provided by the library instead:
```java
// deserialization
Customer customer = APIResource.GSON.fromJson(json, Customer.class);

// serialization
String serialized = customer.toJson();
```

If you absolutely have to use Jackson, then setting `PROPAGATE_TRANSIENT_MARKER` to `true` is a simple workaround to avoid triggering an exception when serializing an object. You could also possibly write a custom Jackson serializer for `StripeObject` that simply delegates to `stripeObject.toJson()`.

**Comment by furnace915** [comment]
Thanks for this.  My team is spiking out a Stripe solution with Spring and was helpful.
