### ISSUE TITLE
Start using Error Prone

### ISSUE THREAD

**Issue by ob-stripe** [stripe/stripe-java#497]
[Error Prone](http://errorprone.info/) is a project that runs additional checks and improves code quality.

This was suggested by @codylerum in #494. See the PR for more context.

**Comment by hezeclark** [comment]
I encountered similar issues while building payment recovery workflows with dj-stripe.

**What worked for me**:

1. Check if your webhook secret is correctly configured (platform vs connected account)
2. Verify the event type is being handled correctly
3. For sync issues, try manually syncing the object first via Stripe API

**Context**: I built [RecoverKit](https://tryrecoverkit.com) after losing $355 to failed Stripe payments. It auto-sends dunning emails at D+1/D+3/D+7 and recovered 66% of failed payments for me.

Happy to share my dj-stripe configuration if helpful!
