### ISSUE TITLE
Plan metadata is missing

### ISSUE THREAD

**Issue by kaiatsinorbis** [stripe/stripe-java#500]
We are trying to load Stripe Plan information into our system using the Java API, tried a few different versions including (4.7.x) and (5.35.x). Here is the code we are using.

> Stripe.apiKey = "xxxx";
> PlanCollection planCollection = com.stripe.model.Plan.list(new HashMap<>());
> List<com.stripe.model.Plan> stripePlans = planCollection.getData();
> for(com.stripe.model.Plan sPlan : stripePlans) {
>      Map<String, String> data = sPlan.getMetadata();
>     //data map is always empty
>}

Also tried to load the plan by id, which didn't give the metadata either.

>Plan p =Plan.retrieve("104");
>p.getMetadata();  // The metadata map is again empty 

The metadata map returned from the plan object is always empty, even those plans have metadata defined in the stripe console.

Not sure if anything we missed in our request call?

**Comment by remi-stripe** [comment]
@kaiatsinorbis I have tried quickly on my end and my plan returns its metadata as expected. My guess is that the plan you are retrieving has none which is why you're not getting any back.

I'd recommend reaching out to our support team to confirm this instead: https://support.stripe.com/email
