### ISSUE TITLE
getName on SubscriptionPlan is deprecated - but non-existing in server API

### ISSUE THREAD

**Issue by michaelkrog** [stripe/stripe-java#501]
I recently upgrade from a version 3.* to 5.35.1 when upgradeing server API to latest version(with Billing). And everything seemed to go smoothly.

However, as getName on subscriptionplan is just deprecated everything compiles nicely. But name does not exist anymore in the server api, so it is just null. Instead I need to use getNickName, to get a display string for the plan(and set the nickname).

I am just wondering it SubscriptionPlan.getName() should just be removed?

**Comment by remi-stripe** [comment]
@michaelkrog A lot of developers will use the latest version of our library but have an account on an older API version where the plan's `name` property still exists. This method is deprecated but still needs to be present in that case.
