### ISSUE TITLE
Set a memo on Subscription via API call

### ISSUE THREAD

**Issue by NicolasRiche** [stripe/stripe-java#506]
Hi,

I want to set a 'memo' in a subscription (and then this memo will appear on all invoices generated by the subscription). It's possible to do it in Stripe dashboard, but I didn't succeed to set it via API (either by using Stripe-java or with a curl request).

The memo field isn't listed in create subscription API doc. 
I set the memo in dashboard and then I looked the logs. The POST request body is:

```
{
  "tax_percent": "14.975",
  "billing": "charge_automatically",
  "invoice_settings": {
    "description": "MY MEMO"
  },
  "prorate": "true"
}
```

I thought, maybe that undocumented, I tried to put manually the invoice_settings/description parameters but I get an error:

```
{
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: description",
    "param": "description",
    "type": "invalid_request_error"
  }
}
```

Is there any way to set the memo via API call?

Another solution for me may be to display the subscription metadata in each invoice, not sure if it's possible.

Thank you.

**Comment by remi-stripe** [comment]
@NicolasRiche This is not supported in the API at the moment and is only available in the dashboard. You'll have to reach out to our support team to discuss this feature instead: https://support.stripe.com/email
