### ISSUE TITLE
Net value not updating

### ISSUE THREAD

**Issue by mamagotope** [stripe/stripe-java#508]
When i create and capture a charge the BalanceTransaction object net and fee values are correct, but if the charge is refounded the BalanceTransaction object net value is incorrect, is the same as before, when it should be -fee value.

Example:
Create a charge with 2100 amount
Capture it and Balance is {Fee=86, Net=2014}
Then refound the captured charge (refounded=2100)
Get the Balance again {Fee=86, Net=2014}
When it should be
{Fee=86,Net=-86}

**Comment by remi-stripe** [comment]
@mamagotope that is unlikely to be a bug in the library. We don't refund our fee on refunds which is why it's not updated. I'd recommend talking to the support team instead: https://support.stripe.com/email

**Comment by mamagotope** [comment]
@remi-stripe that's why i think the net value is incorrect, because it's the same when the charge is captured 
 and when the charge is refounded.

**Comment by remi-stripe** [comment]
@mamagotope I still think there's no bug here since it's expected behavior. I'd recommend talking to our support team directly instead!
