### ISSUE TITLE
Missing "hosted page url" in "Invoice" object.

### ISSUE THREAD

**Issue by afzalex** [stripe/stripe-java#514]
According to current api version of stripe, an Invoice object has "hosted_page_url " which could be used to directly pay invoice using Stripe hosted page.

**Comment by brandur-stripe** [comment]
Just to be clear, you meant `hosted_invoice_url` right?

**Comment by afzalex** [comment]
yeah ,, my typo.. its `hosted_invoice_url`

**Comment by remi-stripe** [comment]
those were added just 2 days ago but I can push a PR in a bit!

**Comment by remi-stripe** [comment]
Pushed a PR in https://github.com/stripe/stripe-java/pull/515. Will fix the other languages too while I'm at it.

**Comment by ob-stripe** [comment]
Released in 5.39.0.
