### ISSUE TITLE
Missing setClientId in RequestOptionsBuilder

### ISSUE THREAD

**Issue by Flo354** [stripe/stripe-java#545]
Hi,

I am trying to use the class `RequestOptionsBuilder` to build my environments with differents apiKey and clientId.

The problem is that RequestOptionsBuilder always use `clientId = Stripe.clientId`. There is no setter to modify it.

Why?

**Comment by ob-stripe** [comment]
Hi @Flo354, this was probably just an oversight. Switching between different client IDs at runtime is a rather uncommon use case, which is probably why this was never reported before.

In any case, I have a fix pending for review in #546. We'll release an updated version of the library shortly.

**Comment by ob-stripe** [comment]
Fixed in 5.47.0.

**Comment by Flo354** [comment]
Thanks!
