### ISSUE TITLE
[Feature Request] Invoice API - no getter for invoice url

### ISSUE THREAD

**Issue by vivekpatel111** [stripe/stripe-java#554]
I want to get `hosted_invoice_url` and `invoice_pdf` from **Invoice** class object from `com.stripe.model` package. This data is already available in class as attribute.

```
  @SerializedName("hosted_invoice_url") String hostedInvoiceURL;
  @SerializedName("invoice_pdf") String invoicePDF;
```

Below is reference _Rest API_ call taken from [API Documentation page](https://stripe.com/docs/api#list_invoices), in which above data is returned. So please provide **getter function** for the same in _Java SDK_.

### Request
> GET https://api.stripe.com/v1/invoices

### Response
```
{
  "object": "list",
  "url": "/v1/invoices",
  "has_more": false,
  "data": [
    {
      "id": "in_1CkvU72eZvKYlo2CQJL1lqoA",
      "object": "invoice",
      "amount_due": 50,
      "amount_paid": 0,
      "amount_remaining": 50,
      "billing": "charge_automatically",
      "billing_reason": "subscription_cycle",
      "hosted_invoice_url": "https://pay.stripe.com/invoice/invst_sfNCSplFzIjT0bwgQnXkvLX7wu",
      "invoice_pdf": "https://pay.stripe.com/invoice/invst_sfNCSplFzIjT0bwgQnXkvLX7wu/pdf",
      "lines": {
        "data": [
          {...}
        ],
        "has_more": false,
        "object": "list",
        "url": "/v1/invoices/in_1CkvU72eZvKYlo2CQJL1lqoA/lines"
      },
      "livemode": false,
      "metadata": {
      },
      ...,
      ...,
      ...
    },
    {...},
    {...}
  ]
}
```

**Comment by ob-stripe** [comment]
Hi @vivekpatel111. We use Project Lombok to automatically generate accessors for class attributes, so this already exists! You can call `getHostedInvoiceURL()` and `getInvoicePDF()` in `Invoice` instances :)

**Comment by vivekpatel111** [comment]
@ob-stripe I'm using [v5.36.0](https://github.com/stripe/stripe-java/tree/v5.36.0) at my end. Is there any significant changes for migrating to latest version [v5.51.0](https://github.com/stripe/stripe-java/tree/v5.51.0)?

**Comment by vivekpatel111** [comment]
@ob-stripe [v5.39.0](https://github.com/stripe/stripe-java/tree/v5.39.0) solves my issue. 
Thanks for support .

Changelog link for [v5.39.0](https://github.com/stripe/stripe-java/blob/master/CHANGELOG.md#5390---2018-06-07) 
- Add `hosted_invoice_url` and `invoice_pdf` properties to `Invoice` model

**Comment by ob-stripe** [comment]
@vivekpatel111 No worries. As a general rule, we use [semantic versioning](https://semver.org/), so you can always safely upgrade between minor versions. Backwards-incompatible changes are only introduced in new major versions.
