### ISSUE TITLE
Sources do not match byte code

### ISSUE THREAD

**Issue by lure** [stripe/stripe-java#555]
Hi
The sources provided through maven for version 5.49+ do not match the byte code. This is most likely the result of lombok generations. Project maintainer may want to use [lombok maven plugin](http://awhitford.github.io/lombok.maven/lombok-maven-plugin/faq.html) 
Thank you.

**Comment by ob-stripe** [comment]
Hi @lure. We use Gradle for our build process, not Maven. We do use the Gradle plugin recommended by Lombok [0].

Is the fact that the sources don't match the byte code a serious issue? I don't have enough experience with the Java ecosystem to tell myself, but if it is, I suppose we could commit the delombok'd source files instead of the "raw" ones.

[0] https://projectlombok.org/setup/gradle

**Comment by lure** [comment]
Hi @ob-stripe 
thank you for fast answer . Basically - yes, not having the real sources is a somewhat issues, making debugging by far less comfortable. 
That would be really nice if you could provide the real sources.

**Comment by ob-stripe** [comment]
@lure Alright, I'll take a look at how other projects that use Lombok handle this issue.

In the meantime, you can get the delombok'd sources by running `gradle delombok` in the stripe-java project. The sources will be created in the `build/delombok` directory.

**Comment by lure** [comment]
Thank you, @ob-stripe

**Comment by ob-stripe** [comment]
I've taken a look at what other projects using Lombok do, and there doesn't seem to be any strong consensus: some projects generate their source JAR using the original files (like we currently do) while others use the delomboked sources (e.g. [here](https://github.com/blink-ai/slack-sdk/blob/7285e164b77c5f490456b2967be24ad06991dfee/SlackSDK/build.gradle#L47-L51)).

I've also not be able to find any "official" guidance from Project Lombok on this specific issue, or even general guidance on whether projects that use any sort of code generation should generate their sources JAR pre- or post-generation.

@brandur What do you think? It looks like it should be safe to generate the sources JAR using the delomboked sources. Can you think of a reason why we shouldn't?

**Comment by brandur-stripe** [comment]
> @brandur-stripe What do you think? It looks like it should be safe to generate the sources JAR using the delomboked sources. Can you think of a reason why we shouldn't?

@ob-stripe I don't have too much context on the issue, but I'd +1 using the delomboked sources: I'd imagine they'd be much more pleasant to step through a debugger because you have real code instead of metaprogramming.

**Comment by ob-stripe** [comment]
@lure I've just released version 6.2.1 of the library, which is identical to 6.2.0 except that the sources JAR is now generated using the delomboked sources.
