### ISSUE TITLE
Odd SSL errors with Stripe Java API libs

### ISSUE THREAD

**Issue by hrstoyanov** [stripe/stripe-java#562]
There is something odd in the way the Java Stripe API wrapper configures SSL: When I use it in OpenLiberty (OL) container, it pick the configured SSL certificates store from the container, which is empty by default, and I start to see SSL errors like this one:

https://github.com/OpenLiberty/open-liberty/issues/4377#issuecomment-408978980

The issue was solved by adding either Stripe.Com or parent (DigiCert) certificates to the OL trust store configuration. However, this should be unnecessary, since Stripe API need only JDK's standard cacert , right?

I don't see the same issue with Auth0.Com or Amazon AWS JAVA SDK 2.0 java libs, all bypassing the container SSL configuration and working flawlessly (I presume with the default JDK SSL context and cacert files).

You can examine the 2 Java libs I mentioned - they are both on github - and see what you are doing differently.

**Comment by ob-stripe** [comment]
Hi @hrstoyanov, thanks for the report!

We do tweak some SSL parameters to enable TLS 1.2 on Java 1.7 (as Stripe's API requires TLS 1.2, per PCI rules). I don't think we change anything related to the cert store, but I could be wrong.

Can you share what versions of Java and stripe-java you're using?

> However, this should be unnecessary, since Stripe API need only JDK's standard cacert , right?

Yes, AFAIK the certs for Stripe's CA (Digicert) should be present in the default certificate store.

**Comment by hrstoyanov** [comment]
```5.50.0```

I also posted the link for the detailed issue.

**Comment by ob-stripe** [comment]
Late update: I was never able to find what exactly caused the issue described here in stripe-java's code. However, we're likely going to drop support for Java 1.7 in the next major version, which will also let us remove all the custom SSL tweaking that we do (since Java 1.8 and more recent versions use TLS 1.2 by default). Hopefully this will fix the problem described here.
