### ISSUE TITLE
Plan\Subscription field inconsistency. 

### ISSUE THREAD

**Issue by lure** [stripe/stripe-java#571]
Plan description in stripe's dashboard: 
Note that nickname is empty. 
<img width="309" alt="screen shot 2018-08-07 at 11 54 31" src="https://user-images.githubusercontent.com/289835/43787755-c464019a-9a39-11e8-86bc-854ed0977d2e.png">

Retrieve user's plan, note that name is null and nickname is not null. 
```
"plan": {
    "id": "some_id",
    "object": "plan",
    "active": true,
    "amount": 20000,
    "billing_scheme": "per_unit",
    "created": 1531245435,
    "currency": "usd",
    "interval": "year",
    "interval_count": 1,
    "livemode": false,
    "metadata": {},
    "nickname": "Pro Annual",
    "product": "prod_DCak502cdbre8",
    "tiers": null,
    "tiers_mode": null,
    "transform_usage": null,
    "usage_type": "licensed",
    "name": null,
    "statement_description": null,
    "statement_descriptor": null,
    "trial_period_days": null
  }
```
Go to sources, 
```
   * @deprecated Prefer using the {@code getProduct().getName()} method instead.
   * @see <a href="https://stripe.com/docs/upgrades#2018-02-05">API version 2018-02-05</a>
```
However, getProduct returns a String, not an object.

**Comment by remi-stripe** [comment]
@lure When you retrieve a Plan via the API, the `product` property is the Product id by default as documented [here](https://stripe.com/docs/api#plan_object-product). This property is [Expandable](https://stripe.com/docs/api#expanding_objects) though which lets you retrieve the full Product object at the same time.

In Java the code would look like this:

```
List<String> expandList = new LinkedList<String>();
expandList.add("product");

Map<String, Object> params = new HashMap<String, Object>();
params.put("expand", expandList);

Plan plan = Plan.retrieve("my_plan_id", params, null);
Product product = plan.getProduct().getProductObject();
String productName = product.getName();
```
