### ISSUE TITLE
Request: Getter for invoice_prefix on Customer object

### ISSUE THREAD

**Issue by itgeorge** [stripe/stripe-java#585]
Currently there appears to be no way to get the value of the ```invoice_prefix``` (https://stripe.com/docs/api#customer_object-invoice_prefix) field on the Customer object. There is no getter (there also appears to be no such field in the Customer.java class) and I'm not aware of a way to request a property by it's name - e.g. something like ```customer.getProperty("invoice_prefix")```.

The use-case for this is using Stripe's auto-generated unique prefix as an identifier (more specifically a prefix in an identifier) for objects in the client code that correlate to the Customer object in Stripe, to avoid having to generate such a prefix in client code.

**Comment by ob-stripe** [comment]
Fixed in 6.12.0.

Thanks for the report @itgeorge!

**Comment by itgeorge** [comment]
Thanks for the quick fix!
