### ISSUE TITLE
Could not initialize class com.stripe.model.Product

### ISSUE THREAD

**Issue by arch9745** [stripe/stripe-java#589]
encountering the error: Could not initialize class com.stripe.model.Product when running in jboss 7.
The code is simple.

```java
Map<String, Object> params = new HashMap<String, Object>();
params.put("name", "somename");
params.put("type", "service");
Product.create(params);
```

The stripe and gson jars have been deployed.  javax.api and gson have been listed as dependencies for the stripe jar. What else is needed?

**Comment by ob-stripe** [comment]
Hi @arch9745. Can you share the full stacktrace? Also, can you specify which versions of Java and stripe-java you're using? (I assume JBoss 7 runs with Java 7, but I'm completely unfamiliar with JBoss.)

**Comment by arch9745** [comment]
I actually just got past that error. It was just jboss being really picky on how it handles class loading. I had installed the stripe jar under com/stripe. Installing under com/stripe/model made it work. You would think com/stripe should have done the trick since thats the base path for the jar.

**Comment by ob-stripe** [comment]
Alright, thanks for the reply! Closing the issue.
