### ISSUE TITLE
Getting customer properties

### ISSUE THREAD

**Issue by SnuK87** [stripe/stripe-java#594]
**Version:**
``` Xml
<groupId>com.stripe</groupId>
<artifactId>stripe-java</artifactId>
<version>6.12.0</version>
```

**Use case:**
I want to read some properties (e.g. expiration of credit card) of the `Customer` object that I get when I update a customer (e.g. add a source).

``` Java
Customer stripeCustomer = Customer.retrieve(profile.getStripeId());
Map<String, Object> updateParams = Collections.singletonMap("source", sourceId);
Customer updatedStripeCustomer = stripeCustomer.update(updateParams);
```

When I take a look at the JSON schema I would expect to do something like

``` Java
ExternalAccount externalAccount = updatedStripeCustomer.getSources().getData().get(0);
int expMonth = externalAccount.getTypeData().getExpMonth();                                
```

But the `ExternalAccount` only provides a few getter and most of them just return a String of the top level properties.

Please correct me if I miss something. If not this should be possible in the future to make it more convenient to work with the library.

**Comment by ob-stripe** [comment]
Hi @SnuK87. A customer's attached payment sources may be of different types: [cards](https://stripe.com/docs/api/java#card_object), [bank accounts](https://stripe.com/docs/api/java#customer_bank_account_object) or [sources](https://stripe.com/docs/api/java#source_object). `ExternalAccount` is a parent class for those different types.

Unfortunately at this time, it is necessary to cast the object yourself. (This is a known limitation of the Java library that we hope to be able to fix in a future version.) Here's an example:

```java
Customer customer = Customer.retrieve(profile.getStripeId());
ExternalAccount customerSource = customer.getSources().getData(0);
if (customerSource.getObject().equals("card")) {
  Card card = (Card)customerSource;
  Integer expMonth = card.getExpMonth();
} else if (customerSource.getObject().equals("source")) {
  Source source = (Source)customerSource;
  if (source.getType() == "card") {
    Integer expMonth = source.getTypeData().get("exp_month");
  }
}
```

If you're updating the source, you probably already know the type though, so you could cast immediately without having to check `getObject()` first.

I hope this helped, but if you have more questions, please follow up with our support at https://support.stripe.com/email.

**Comment by SnuK87** [comment]
@ob-stripe Thanks for the quick response.

I'm currently using the `toJson()` method parse the json of the `ExternalAccount`. But your solution looks a bit better.

Thanks again.
