### ISSUE TITLE
Request: Add a way to fetch all charges for an invoice

### ISSUE THREAD

**Issue by itgeorge** [stripe/stripe-java#597]
The API currently allows to get the latest charge for an invoice through ```invoice.getCharge()```.

However there seems to be no way to retrieve all charges for an invoice, except writing custom code to fetch all charges between two dates and filter them by invoice id, which seems error-prone.

The Stripe Dashboard seems to be able to do this - it lists "Payments" for an invoice for which one or more payments failed, and those payments contain charge ids.

**Comment by remi-stripe** [comment]
@itgeorge Unfortunately this feature is limited to the dashboard at the moment. It's not missing in stripe-java per se, it is just not yet public in the API. I'll raise it internally though to see if we could add support for this publicly in the future!
