### ISSUE TITLE
Missing "flat amount" in Plan.Tier object

### ISSUE THREAD

**Issue by marco-aquilanti** [stripe/stripe-java#608]
Hi,
I am using Stripe Java library (V 7.2.0) and I don't have available"flat amount" in the object Tier when I retrieve a Plan. 
I tried using curl command and the value flat_amount is correctly populated in the JSON response from the server exactly how documentation says (https://stripe.com/docs/api/plans/object).
The problem is: flat_amount is missing in inner class Plan.Tier (https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/Plan.java) so I cannot access it in my Java application.

`public static class Tier extends StripeObject {    
    Long unitAmount;
    Long upTo;
   /**
    * The {@code amount} attribute.
    *
    * @return the {@code amount} attribute
    * @deprecated Prefer using the {@code unitAmount} attribute instead.
    * @see <a href="https://stripe.com/docs/upgrades#2018-08-23">API version 2018-08-23</a>
    */
   @Deprecated
   Long amount;
    }`

**Comment by remi-stripe** [comment]
@marco-aquilanti This feature was just released and it is not yet part of the API libraries. It's something we hope to ship soon though!

**Comment by marco-aquilanti** [comment]
@remi-stripe  Thank you for the quick reply.

**Comment by remi-stripe** [comment]
@marco-aquilanti I just released it in 4.11.0 so if you upgrade you should get it!

**Comment by remi-stripe** [comment]
Correction, this will ship in 7.3.0 soon. 4.11.0 was a mixup and that version is removed.

**Comment by marco-aquilanti** [comment]
Thank you @remi-stripe. 
Really impressed from the quick answer I got.
