### ISSUE TITLE
wallet provider is missing from Authorization object

### ISSUE THREAD

**Issue by martintreurnicht** [stripe/stripe-java#633]
See https://stripe.com/docs/api/issuing/authorizations/object#issuing_authorization_object-wallet_provider for more information

**Comment by remi-stripe** [comment]
@martintreurnicht Thanks a lot for the report! I'll work on adding support for this soon and hopefully we can release this in the next few days!

**Comment by martintreurnicht** [comment]
Awesome! Thanks for the quick feedback

**Comment by remi-stripe** [comment]
This is being released in 7.12.0!
