### ISSUE TITLE
NullPointerException rawEvidence is null for Dispute

### ISSUE THREAD

**Issue by alejandrod** [stripe/stripe-java#650]
Use case:
Dispute looks like:
```json
  {
      "id": "dp_00000000000000",
      "object": "dispute",
      "amount": 1000,
      "balance_transactions": [
        
      ],
      "charge": {
        "id": "ch_00000000000000"
      },
      "created": 1547164242,
      "currency": "usd",
      "evidence_sub_object": {
        
      },
      "evidence_details": {
        "due_by": 1548806399,
        "submission_count": 0
      },
      "is_charge_refundable": false,
      "livemode": false,
      "metadata": {
        
      },
      "reason": "general",
      "status": "needs_response",
      "balance_transaction": "txn_00000000000000"
    }
```

`DisputeDataDeserializer` line 39
`JsonElement rawEvidence = disputeAsJsonObject.get("evidence");`
rawEvidence is null

Libary version : "7.13.0"
Stripe API version: 2018-11-08

We should check for null

**Comment by remi-stripe** [comment]
@alejandrod Do you have a bit more details about how you ended up with that payload for the dispute object? Based on the id with only zeroes, my guess is that you used the "Send test event" button for the webhook endpoint but I can't seem to reproduce this issue.

**Comment by alejandrod** [comment]
Yes. @mio-stripe I think it is. Thanks!

**Comment by remi-stripe** [comment]
@alejandrod I'm not entirely sure I follow what you meant by your answer. Would you be able to provide a lot more details about the issue? Especially the exact payload of the whole JSON object being sent so that I can try to reproduce.

**Comment by yossikal** [comment]
Hi @remi-stripe, the issue is when sending a charge.dispute.created test webhook from stripe's dashboard to our endpoint.

**Comment by remi-stripe** [comment]
@yossikal I'm unfortunately having some problem reproducing this issue on my side. Would you be able to clarify which API version is associated with your Stripe account at the moment?

**Comment by yossikal** [comment]
@remi-stripe  sure.
apiVersion = "2018-11-08". 
Sending the test webhook with connect parameters.

**Comment by remi-stripe** [comment]
@yossikal I'm sorry for the back and forth but I can not seem to reproduce this in my account. I'm using the latest API version in a brand new account and the latest version of stripe-java and the Dispute deserializes without issues.

Would you be able to share the raw event JSON as it appears in the Dashboard when you click this button? I feel like you're getting a different output than I am for some reason.

**Comment by yossikal** [comment]
@remi-stripe No problem, here's the JSON:
```
{
  "created": 1326853478,
  "livemode": false,
  "id": "charge.dispute.created_00000000000000",
  "type": "charge.dispute.created",
  "object": "event",
  "request": null,
  "pending_webhooks": 1,
  "api_version": "2018-11-08",
  "account": "acct_00000000000000",
  "user_id": "acct_00000000000000",
  "data": {
    "object": {
      "id": "dp_00000000000000",
      "object": "dispute",
      "amount": 1000,
      "balance_transaction": "txn_00000000000000",
      "balance_transactions": [
      ],
      "charge": "ch_00000000000000",
      "created": 1548857878,
      "currency": "usd",
      "evidence": {
        "access_activity_log": null,
        "billing_address": null,
        "cancellation_policy": null,
        "cancellation_policy_disclosure": null,
        "cancellation_rebuttal": null,
        "customer_communication": null,
        "customer_email_address": null,
        "customer_name": null,
        "customer_purchase_ip": null,
        "customer_signature": null,
        "duplicate_charge_documentation": null,
        "duplicate_charge_explanation": null,
        "duplicate_charge_id": null,
        "product_description": null,
        "receipt": null,
        "refund_policy": null,
        "refund_policy_disclosure": null,
        "refund_refusal_explanation": null,
        "service_date": null,
        "service_documentation": null,
        "shipping_address": null,
        "shipping_carrier": null,
        "shipping_date": null,
        "shipping_documentation": null,
        "shipping_tracking_number": null,
        "uncategorized_file": null,
        "uncategorized_text": null
      },
      "evidence_details": {
        "due_by": 1550534399,
        "has_evidence": false,
        "past_due": false,
        "submission_count": 0
      },
      "is_charge_refundable": false,
      "livemode": false,
      "metadata": {
      },
      "reason": "general",
      "status": "needs_response"
    }
  }
}
```

**Comment by remi-stripe** [comment]
@alejandrod Okay this is the exact JSON I get. Which version of stripe-java are you using to deserialize this event?

**Comment by yossikal** [comment]
@remi-stripe stripe-java version: `7.13.0`

We use this in scala, this is the formatter:
```
  implicit val DisputeFormat: Format[com.stripe.model.Dispute] = new Format[com.stripe.model.Dispute] {
    override def writes(o: com.stripe.model.Dispute): JsValue = Json.parse(ApiResource.GSON.toJson(o, o.getClass))

    override def reads(json: JsValue): JsResult[com.stripe.model.Dispute] = JsSuccess(ApiResource.GSON.fromJson(json.toString, classOf[com.stripe.model.Dispute]))
  }
```

**Comment by ob-stripe** [comment]
@yossikal The JSON string you posted in your original message includes an `evidence_sub_object` key and no `evidence` key. My guess is that this JSON string was reserialized from a `Dispute` object, rather than being the raw JSON sent by Stripe's webhook test button. Is that correct?

If so, then the issue is that `Dispute` objects are not correctly serialized back to JSON. This is because the Java library needs to be able to handle multiple API versions, and the type of the `evidence` attribute changed from a string to an object a while ago (https://stripe.com/docs/upgrades#2014-12-08). The object is stored under the `evidenceSubObject` property, since the `evidence` string property existed before. We have a custom deserializer to fill the correct property, but no custom serializer to do the opposite.
