### ISSUE TITLE
Missing Invoice.getCustomerObject()

### ISSUE THREAD

**Issue by stickfigure** [stripe/stripe-java#674]
It looks like (as of 7.19.0) there is no getCustomerObject() method on Invoice. I'd like to be able to expand the customer field of an invoice (like you can with Charge). Thanks!

**Comment by remi-stripe** [comment]
@stickfigure Thanks for the report! It looks like the library never supported this but I'm working on fixing it now!

**Comment by remi-stripe** [comment]
@stickfigure This was released on 7.20.0 today!
