### ISSUE TITLE
Invalid Stripe API version: 2019-2-19

### ISSUE THREAD

**Issue by bjornharvold** [stripe/stripe-java#682]
Using Stripe Java v7.24.0
Using JDK 1.8 181
Account version: 2018-2-28
Stripe testing version: 2019-02-19

I am currently working on our Stripe integration. I want to upgrade my Stripe version to the latest while I am here. I updated our dependency on Stripe Java to 7.24.0 and I set Stripe.apiVersion to 2019-02-19.

When I start running through my integration tests I get the error:

`Invalid Stripe API version: 2019-2-19`

This is my first time trying to upgrade our Stripe API version so please bare with me if I am missing something here. I cannot see this error anywhere in the Stripe documentation so I am not sure where to go from here.

**Comment by remi-stripe** [comment]
@bjornharvold based on the error message, it seems you are passing `2019-2-19` in the string instead of `2019-02-19`. Just double check your code and make sure to add the missing zero in front of the 2.

**Comment by bjornharvold** [comment]
And that's exactly what the problem was. Incorrect date format. Alright.... moving right along gentlemen. Nothing to see here!

Thank you :-)
