### ISSUE TITLE
Document Webhook Object Deserialization in Migration Guide

### ISSUE THREAD

**Issue by codylerum** [stripe/stripe-java#699]
In v7 the charge object (assuming I've check that the event type should have a charge object) in a webook could be obtained via.

```
Event event = Webhook.constructEvent(payload, signature, secret);
Charge charge = (Charge) event.getData().getObject();
```
The getObject however is now deprecated. It would appear that the correct call is now

```
 Charge charge = (Charge) event.getDataObjectDeserializer().getObject();
```

This should be documented in the migration guide as well as I don't see a test deserializing an object from a webhook.  It would be helpful if there was a test that constructed the webhook Event from signature and payload. Checked the event type and then deserialized it.

```
Event event = Webhook.constructEvent(payload, signature, secret);
if (event.getType().equals(STRIPE_EVENT_CHARGE_SUCCEEDED)) {
   Charge charge = (Charge) event.getDataObjectDeserializer().getObject();
   doSomething(charge);
}
```

https://github.com/stripe/stripe-java/blob/master/src/test/java/com/stripe/net/WebhookTest.java

**Comment by remi-stripe** [comment]
@codylerum Thanks for the feedback! We'll work on improving this!

**Comment by mickjermsurawong-stripe** [comment]
Hi @codylerum! Thank you for the quick feedback here.
There's a section about the event deserialization event under "Event response structure" https://github.com/stripe/stripe-java/wiki/Migration-guide-for-v8----version-upgrade. 
I will add to it explicitly the new way of deserializing the data as you suggest.

On test, maybe we wouldn't to test logic on the Event object in Webhook object? Event can actually be retrieved both from constructing the webhook payload, and from `Event#retrieve`.
There are existing tests on this event data deserialization in [0]. Please let me know if I can improve on the tests to provide better examples.

[0] https://github.com/stripe/stripe-java/blob/master/src/test/java/com/stripe/model/EventDataObjectDeserializerTest.java

**Comment by codylerum** [comment]
@remi-stripe & @mickjermsurawong-stripe  No problem. Other than that I was able to sort things out and get everything updated to v8

Not sure how I missed that in the documentation.

Creating a new webhook endpoint each time we we bump versions will definitely be a bit of a change though I see how it is needed for strict compatibility.

**Comment by codylerum** [comment]
@mickjermsurawong-stripe I think what I'm more looking for is a specific example of the way the stripe java api recommends constructing the Event from webhook payload and extracting the specific object based on event type. You have a simple usage in the ReadMe for creating a charge - https://github.com/stripe/stripe-java/blob/master/README.md

Maybe something like that but maybe in the wiki like the migration docs to it doesn't cutter the readme?

**Comment by mickjermsurawong-stripe** [comment]
Glad to hear that you were able to able upgrade to v8 successfully! And thank you for the feedback so far.

I made 2 PRs, cc you both, to add documentations to both source code and the migration update guide, and also a test on `Event` class itself instead of `Webhook` for the reason that event class also supports retrieving from `/v1/events` endpoint as well.

**Comment by mickjermsurawong-stripe** [comment]
hi @codylerum! 
8.0.2 is released, adding the test and java doc to reflect migration guide--also updated. (8.0.1 is an accidental release with no actual change) I'm closing this issue now, but please let me know if i'm still missing something else in this major version release. Thank you again for your contribution :)
