### ISSUE TITLE
How create Session object in java project?

### ISSUE THREAD

**Issue by lmdic** [stripe/stripe-java#716]
In my java project in **build.gradle.kts**.

`implementation("com.stripe:stripe-java:8.1.0")`

Now, how in my java code I can create this session object

https://stripe.com/docs/api/checkout/sessions/create

?

**Comment by remi-stripe** [comment]
@lmdic At the moment the APIs associated with the `Session` object are not supported in stripe-java. This is due to `Session` being in beta for now and subject to changes. We will add the `Session` object in the future though once it has fully stabilized.
