### ISSUE TITLE
Maven import 9.0.0 Missing artifact

### ISSUE THREAD

**Issue by casper5822** [stripe/stripe-java#732]
I did the upgrade from stripe-java 8.10 to 9.0.0, but maven import seems not working:

Error missing artifact in maven project.

**Comment by mickjermsurawong-stripe** [comment]
Hi @casper5822, thank you for the report! We did have a deploy problem yesterday, and it seems like we didn't resolve that entirely. Will update you here once it's on Maven.

**Comment by mickjermsurawong-stripe** [comment]
Hi @casper5822, v9.0 is on Maven now. Please let us know if you have feedback using the new release!

**Comment by casper5822** [comment]
Ok, it works. Thank you for all.
