### ISSUE TITLE
Event deserialization example in migration guide for v9 isn’t idiomatic Java 8

### ISSUE THREAD

**Issue by alexbishop1** [stripe/stripe-java#740]
The event deserialization part of the [migration guide for v9 on the wiki](https://github.com/stripe/stripe-java/wiki/Migration-guide-for-v9) includes this code example:

```java
    Event event = getEventFromWebhookOrEndpoint();
    EventDataObjectDeserializer dataObjectDeserializer = event.getDataObjectDeserializer();
    if (dataObjectDeserializer.getObject().isPresent()) {      
      StripeObject stripeObject = dataObjectDeserializer.getObject().get();
      doSomething(stripeObject);
    } 
```

The use of the `isPresent()` method on `Optional` is unusually unnecessary and is discouraged. It would be more idiomatic to use a lambda:

```java
    Event event = getEventFromWebhookOrEndpoint();
    EventDataObjectDeserializer dataObjectDeserializer = event.getDataObjectDeserializer();
    dataObjectDeserializer.getObject().ifPresent(stripeObject -> {
      doSomething(stripeObject)
    });
```

(I would have created a pull request directly against the wiki but that doesn’t seem to be possible.)

**Comment by mickjermsurawong-stripe** [comment]
Thank you @alexbishop1 for reporting the details we miss here!

Rightly, when we are sure that events should be there, the proposed snippet would be ideal.
I worry a little though that the snippet assumes it is okay when data object is absent--nothing is logged or there's no attempt to do retry.

To achieve that effect, I should probably have something explicit in the else branch.
```
    if (dataObjectDeserializer.getObject().isPresent()) {      
      StripeObject stripeObject = dataObjectDeserializer.getObject().get();
      doSomething(stripeObject);
    } else {
      // handle absent data object with `deserializeUnsafe` or `deserializeUnsafeWith`
    }
```
Would that look more reasonable to you?

**Comment by alexbishop1** [comment]
Yeah, that looks better.

Java 9 and above has `ifPresentOrElse(…)`:

```java
    Event event = getEventFromWebhookOrEndpoint();
    EventDataObjectDeserializer dataObjectDeserializer = event.getDataObjectDeserializer();
    dataObjectDeserializer.getObject().ifPresentOrElse(stripeObject -> {
      doSomething(stripeObject)
    }, () -> {
      // handle absent data object with `deserializeUnsafe` or `deserializeUnsafeWith`
    });
```

But I understand that you probably want to to only use Java 8 in the code examples.

**Comment by mickjermsurawong-stripe** [comment]
Updated the wiki. On the java doc itself, there's a similar example using the explicit check `isPresent` and throwing error in else branch under the context that webhook endpoint has matching API version. I leave the java-doc as-is. Would appreciate any further suggestions you may have.

Ah yup, we hope to have documentation that works for all versions we now support. But I didn't know Java9 has that interface TIL!

Thanks for giving us quick feedback on version 9.

**Comment by alexbishop1** [comment]
Thanks for looking at this so quickly.
