### ISSUE TITLE
Invoice-related webhook events not parsable by the v9.1.0 library

### ISSUE THREAD

**Issue by jjlueck-tock** [stripe/stripe-java#742]
After upgrading to the 9.1.0 version of this library, any webhook related to invoices in our test environment fail with the error `java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.payment_intent` when deserializing the object.

It appears as though the library expects the payment_intent field to be an object when it is in fact a String identifier. We do not experience this issue with the 8.1.0 version of the library.

**Comment by remi-stripe** [comment]
@jjlueck-tock Sorry for the trouble on that one. We're working on a fix and hope to have a fix released by the end of the day.

**Comment by remi-stripe** [comment]
@jjlueck-tock We released stripe-java 9.2.0 which should fix the issue. It also goes hand in hand with a change on our side where `payment_intent` on `Invoice` is now always a string but can be [expanded](https://stripe.com/docs/api#expanding_objects) if needed
