### ISSUE TITLE
Can't unset tax_info.tax_id

### ISSUE THREAD

**Issue by snieguu** [stripe/stripe-java#772]
Java version: 1.8.0_211
Stripe Java library: 9.9.0

Although documentation stands that:
> tax_info.tax_id REQUIRED
> The customer’s tax ID number. This can be unset by updating the value to null and then saving.

When I update Customer with below code:
```
CustomerUpdateParams.TaxInfo taxInfo = CustomerUpdateParams.TaxInfo.builder()
                    .setTaxId(null)
                    .setType(CustomerUpdateParams.TaxInfo.Type.VAT)
                    .build();
CustomerUpdateParams customerUpdateParams = CustomerUpdateParams.builder()
                    .setEmail(email)
                    .setTaxInfo(taxInfo)
                    .setSource(token)
                    .build();
result.get().update(customerUpdateParams);
```
I get the error:
> Missing required param: tax_info[tax_id].; code: parameter_missing

**Comment by remi-stripe** [comment]
@snieguu You should stop using the `tax_info` property on the Customer object as this is actively deprecated. Instead, you should create/delete TaxId resources: https://stripe.com/docs/api/customer_tax_ids/delete
