### ISSUE TITLE
JsonMappingException exception is throwing when retrieving an account

### ISSUE THREAD

**Issue by andreeahash** [stripe/stripe-java#795]
Hello,

I am using **api version - 2019-05-16** and **java sdk - 10.0.2** inside a spring boot app and I get the following error at retrieve account (for connect):
`Caused by: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.stripe.net.StripeResponse and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.stripe.model.Account["lastResponse"])`

The call I make is: 'Account.retrieve(accountId)'

I have tried setting following properties on my application context, although I am not sure these are picked up by the java sdk:
'spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.mapper.PROPAGATE_TRANSIENT_MARKER=true'

Also, I have tried during a direct get via api, and the response does not contain the field 'lastResponse'.

Could you, please, advise? (I can provide a test account id, if necessary)

Thanks in advance,
Andreea.

**Comment by ob-stripe** [comment]
Hi @andreeahash. Stripe's Java library uses [Gson](https://github.com/google/gson) for serializing and deserializing JSON, not Jackson. There are no references to Jackson anywhere in the library.

Your application is probably doing something custom to use the `lastResponse` property with Jackson. Can you check whether that's the case?

**Comment by andreeahash** [comment]
Hello. 
Regarding the lastResponse, I don't use anywhere in the code, the only thing I have regarding account serialization were some logs for - account.getRequirements().toJson(), but I've removed them and I still get the same error.
For the gson, what could I use for the settings in order to bypass that error?
Thanks.

**Comment by andreeahash** [comment]
Found the issue: I was using the Account object from the Stripe library as a response of an api I created and I guess the issue was when trying to serialize that using jackson - although, i've used this for a while and it only starting failing recently (in the last few months, let's say)
