### ISSUE TITLE
UpdatePaymentMethod: unable to delete properties

### ISSUE THREAD

**Issue by decoursin** [stripe/stripe-java#803]
I'm unable to delete properties at all when trying to update a PaymentMethod. I've all 4 of the following approaches. I will use the `address.city` as an example:
* PaymentMethodUpdateParams.BillingDetails.Address.builder().setCity(null)
* PaymentMethodUpdateParams.BillingDetails.Address.builder().setCity("")
* PaymentMethodUpdateParams.BillingDetails.Address.builder().putExtraParam("postal_code", null)
* PaymentMethodUpdateParams.BillingDetails.Address.builder().putExtraParam("postal_code", ""

I've also tried mixing-and-matching these 4 cases, but nothing works.

I get this error when it's empty string: ```com.stripe.exception.InvalidRequestException: You cannot set 'billing_details[address][line2]' to an empty string. We interpret empty strings as null in requests. You may set 'billing_details[address][line2]' to null to delete the property.```

It seems to be roughly the same issue as: https://github.com/stripe/stripe-java/issues/788.

I would reckon that the `PaymentMethod.update` is almost completely useless without the ability to delete values.

**Comment by ob-stripe** [comment]
Hi @decoursin. Fields that can be unset have an overload method that accepts an `EmptyParam` value, e.g.: https://github.com/stripe/stripe-java/blob/4a7a241288cc626a6ef0142a1c3ec79ba5174857/src/main/java/com/stripe/param/CustomerUpdateParams.java#L255

The only valid `EmptyParam` value is `EmptyParam.EMPTY`. So for instance this is how you'd unset the `address` field on a customer:
```java
Customer customer = Customer.retrieve("cus_123");
CustomerUpdateParams params = CustomerUpdateParams.builder()
  .setAddress(EmptyParam.EMPTY)
  .build();
Customer updatedCustomer = customer.update(params);
```

In the case of `PaymentMethodUpdateParams`, none of fields in `billing_details[address]` nor the parent field `billing_details[address]` itself are unsettable in the API, so the Java library does not provide overload methods to pass `EmptyParam.EMPTY` for any of these fields.

I will raise this issue internally, but I also recommend you reach out to support at https://support.stripe.com/email to request this feature and give some details about your use case.

**Comment by decoursin** [comment]
I think the `customer.footer` should be un-settable, but it's not:
```
Exception in thread "main" com.stripe.exception.InvalidRequestException: You cannot set 'invoice_settings[footer]' to an empty string. We interpret empty strings as null in requests. You may set 'invoice_settings[footer]' to null to delete the property.
```
If I try to set it to `null` it simply doesn't change value of `customer.footer` meaning it has no effect.

**Comment by ob-stripe** [comment]
@decoursin You are correct, this is a bug in the library. There should be a `setFooter(EmptyParam value)` override, but it doesn't exist currently. We'll look into it and release a fix.

**Comment by ob-stripe** [comment]
Sorry for the late reply! As of version 12.2.0, you should now be able to do the following:

```java
CustomerUpdateParams params = CustomerUpdateParams.builder()
  . setFooter(EmptyParam.EMPTY)
  .build();
Customer updatedCustomer = customer.update(params);
```

Closing, but feel free to reply if you're still having issues with this.

**Comment by decoursin** [comment]
That's wonderful, thank you very much!
