### ISSUE TITLE
Exception when casting Invoice object on webhook in case of "invoice.payment_succeeded"

### ISSUE THREAD

**Issue by makahleh** [stripe/stripe-java#807]
My code : 
 
```java
 Invoice invoice = (Invoice) event.getDataObjectDeserializer().getObject();
 Customer customer = invoice.getCustomerObject();
```

NullPointerException at the first line & in the second line the customer object is null!

The same code was working fine 2 months ago,
Stripe maven version : 8.0.2
API version: 2019-03-14.

Could you advise?

Thanks.

**Comment by remi-stripe** [comment]
@makahleh Would you be able to provide an example event id that you are trying to deserialize?

**Comment by makahleh** [comment]
@remi-stripe
I’m not sure what do you mean by “ event id “
but the event type is invoice.payment_succeeded

**Comment by remi-stripe** [comment]
Sorry I mean the id of one of the event that you can't deserialize: `evt_1234567` which would let me look at it and understand what's happening.

**Comment by makahleh** [comment]
Ok, here it is


evt_1ExXsKCiNugxWonKNlmDtnKg

thanks

**Comment by ob-stripe** [comment]
Hi @makahleh. Can you try replacing `getObject()` with `deserializeUnsafe()` and share the result?

**Comment by makahleh** [comment]
@ob-stripe 
Actually i'm away from my machine this weekend, i will try that and get back to you on Sunday :)


But i have a question,
I found in this : https://github.com/stripe/stripe-java/issues/771 something to say that there is versioning issues and there is no backward-compatibility, but i can't understand the full picture.

When stripe update their APIs, the java SDK will be updated accordingly, and the removed fields from the API side will be removed from  the newest version of the SDK (not Deprecated).
So if anyone has integrated using the old version of the SDK and the old version of the APIs shouldn't be affected right?
Why i am facing problems like that since the maven dependency and the APIs version are the same??
Knowing that my webhook was tested successfully when i integrated before 2-3 months(i'm not sure).

Thanks.

**Comment by makahleh** [comment]
@ob-stripe 

Hello again :)

I tried "deserializeUnsafe()" and yet i cannot get the customer object from the Invoice object.

**Comment by ob-stripe** [comment]
@makahleh Can you share the exception and stacktrace?

**Comment by makahleh** [comment]
@ob-stripe 
There is no exceptions, but the customer object that extracted from an invoice object is always null 

```
        Invoice invoice = (Invoice) stripeEvent.getDataObjectDeserializer().getObject();
        Customer customer = invoice.getCustomerObject(); // The problem is the customer object is null.
```

Note that i tried the following changes with no luck :
 1- upgrading Stripe SDK version from 8.0.2 to latest.
 2- deserializeUnsafe().

**Comment by ob-stripe** [comment]
@makahleh Ah, thanks for the clarification! The behavior you're describing is expected and not an issue with the library.

The [`customer`](https://stripe.com/docs/api/invoices/object#invoice_object-customer) field on [invoice objects](https://stripe.com/docs/api/invoices/object) is [expandable](https://stripe.com/docs/api/expanding_objects). This means that by default, the field only contains a string with the customer's ID.

Expanding fields can only be done in API requests. When receiving webhook events, fields are always unexpanded. This means that you need to change your code like this:

```java
String customerId = invoice.getCustomer(); // retrieve the unexpanded customer ID
```

and if you need the full customer object, you'll need to retrieve it separately:

```java
Customer customer = Customer.retrieve(customerId);
```

I'm closing the issue since this is the normal behavior of the API and not an issue with the library, but feel free to reply if anything's unclear.

**Comment by makahleh** [comment]
@ob-stripe 
Thanks for clarification, 
The only question in my mind is that the casting was working 3 months ago without calling the API to get the customer object. So what you are saying is that the API response has changed and it does not contain the customer object that related for the invoice ??

Knowing that i haven't changed the API version on the dashboard.

Thanks.

**Comment by ob-stripe** [comment]
> The only question in my mind is that the casting was working 3 months ago without calling the API to get the customer object. So what you are saying is that the API response has changed and it does not contain the customer object that related for the invoice ??

No, fields in webhook events have always been unexpanded, so this specific case would never have worked. Maybe you were getting the invoice separately with the `customer` field expanded? E.g. like this:

```java
// get the invoice from the webhook event
Invoice invoice = (Invoice) event.getDataObjectDeserializer().getObject();

List<String> expandList = new LinkedList<String>();
expandList.add("customer");
Map<String, Object> params = new HashMap<String, Object>();
params.put("expand", expandList);

// fetch the invoice back from the API but with the `customer` field expanded
invoice = Invoice.retrieve(invoice.getId(), params);
Customer customer = invoice.getCustomerObject();
```
