### ISSUE TITLE
Support for Typed Parameter for Level3 object in Charge

### ISSUE THREAD

**Issue by Thilakeswar** [stripe/stripe-java#810]
Earlier while using old JAR versions, we were able to send the Level3 Data as an Untyped params in the Charge API request. With the current JAR update and API version update, [typed parameters](https://github.com/stripe/stripe-java/wiki/Migration-guide-for-v9#typed-parameters) are supported for most of the Stripe requests.

However there is no support provided for the Level3 data in the Typed Parameters provided for the Charge API request.

**Comment by remi-stripe** [comment]
@Thilakeswar The Level3 data is a feature not publicly supported. We usually don't release support for gated features in the libraries as the API could change which would introduce breaking changes and major versions.
At the moment, the recommended approach is to pass the Level3 data as untyped the same way you did on older versions of the library.

**Comment by Thilakeswar** [comment]
@remi-stripe  Thanks for responding. Will we be able to use the method chargeCreateParams.builder().putExtraParam() to set the Level3 data using the builder methods?

**Comment by remi-stripe** [comment]
Yes! That's what I would recommend so that you keep the type safety on the other parameters!
