### ISSUE TITLE
Getters for Builder

### ISSUE THREAD

**Issue by Thilakeswar** [stripe/stripe-java#811]
I have constructed a Charge builder like below,
```
ChargeCreateParams.Builder chargeCreateParamsBuilder = new ChargeCreateParams.Builder();

		chargeCreateParamsBuilder.setAmount(Long.valueOf("100"));
		chargeCreateParamsBuilder.setDescription("desc");
		chargeCreateParamsBuilder.setCurrency("USD");
		chargeCreateParamsBuilder.putMetadata("CompanyName", "Stripe");
		chargeCreateParamsBuilder.putMetadata("Designation", "Remote Dev");
```
Before building the builder using `chargeCreateParamsBuilder.build()`, at some point of time, say for ex, I need to verify whether I had set a meta data in the builder.(another ex, Maybe I might be validating the value set in the builder after some time)

I now need to retrieve all the values set as Meta data in the builder. As of now, I am not able to retrieve the vaules set in the Builder object.

There is no support to retrieve the nodes set in the builder.

**Comment by remi-stripe** [comment]
@Thilakeswar Today, we don't have getters for this so it's not possible to access the information that way. What we would recommend is that you keep a separate map for your metadata and only add it to the builder later once it's complete or has been validated!

**Comment by Thilakeswar** [comment]
There is a way @remi-stripe 

I tried to convert the builder to a map which contains the nodes set in the builder as a key-value pair as below,
```
              ChargeCreateParams.Builder chargeCreateParamsBuilder = new ChargeCreateParams.Builder();
		chargeCreateParamsBuilder.setAmount(Long.valueOf("100"));
		chargeCreateParamsBuilder.setDescription("desc");
		chargeCreateParamsBuilder.setCurrency("USD");
		chargeCreateParamsBuilder.putMetadata("CompanyName", "Stripe");
		chargeCreateParamsBuilder.putMetadata("Designation", "Remote Dev");

                Map<String, Object> builderToMap = chargeCreateParamsBuilder.build().toMap();
                //Validations on this map and reconstruct builder
```

As of now, I might be use the above code for the same. But do let us know if there are getters to retrieve the node set in the builder.

Is it possible to add this request as a feature request and not as an issue? So that you guys can bring this up in your later releases?

**Comment by ob-stripe** [comment]
I think this is a reasonable request. No promises as to when we'll get to it, but let's keep this open for now.

**Comment by Thilakeswar** [comment]
@remi-stripe  Thanks a lot. Glad you had added the future tag so that you can take this up in future updates.

Also, i have renamed the title from `Retrieve a node's value from constructed Builder Object` to `Getters for Builder` so that other folks can find this and doesn't raise a new request for the same.

**Comment by eaglerainbow** [comment]
Just for the sake of completeness here: #859 asked for getters not for the builder but for the entity itself. #859 has been closed with reference to this issue here.

**Comment by ob-stripe** [comment]
I've given this a bit more thought and I think getters directly on builder classes are rather uncommon and a bit of a violation of the single responsibility principle.

In version 13.2.0, we've added getters on the resulting parameters classes (i.e. the classes that are returned by the parameters builders). Would that work for your use case, @Thilakeswar? You'd be able to do something like this:

```java
ChargeCreateParams.Builder chargeCreateParamsBuilder = new ChargeCreateParams.Builder();
chargeCreateParamsBuilder.setAmount(Long.valueOf("100"));
// etc.

Long amount = chargeCreateParamsBuilder.build().getAmount();
// do whatever validations is needed

// finally build the "real" parameters class instance that you'll use for your API request
ChargeCreateParams chargeCreateParams = chargeCreateParamsBuilder.build();
```

**Comment by ob-stripe** [comment]
I'm timing out and closing this issue for now. If you strongly feel that we should add getters to the builders (in addition to the existing getters on the resulting built objects), feel free to reply and we'll reopen and discuss further.
