### ISSUE TITLE
Duplicate/Confusing nodes in the PaymentIntent object in v 10.9.1 JAR

### ISSUE THREAD

**Issue by Thilakeswar** [stripe/stripe-java#814]
There were two nodes in PaymentIntentCreateParams to notify the off session. 
1) PaymentIntentCreateParams.offsession  
2) PaymentIntentCreateParams.OffSession.ONE_OFF  / PaymentIntentCreateParams.OffSession.RECURRING

Can the deprecated node be marked in the JAR or can the unused node be deleted to avoid confusions?

**Comment by remi-stripe** [comment]
@Thilakeswar This parameter is a boolean. It was an enum for a few weeks and we wanted to avoid breaking any existing integration by changing this. We plan to remove this in the next major version which should land in a week or two. I do agree it's confusing and it was made as a one-off to minimize disruption.

**Comment by Thilakeswar** [comment]
@remi-stripe As of now, we will use the boolean value. Glad that you will be removing this in your next major version release. Thanks!
