### ISSUE TITLE
RequestOptionsBuilder does not set default timeouts

### ISSUE THREAD

**Issue by bpicolo** [stripe/stripe-java#817]
The RequestOptionsBuilders defaults to 0 for both connectTimeout as well as readTimeout:
https://github.com/stripe/stripe-java/blob/aa9be6cf41aa1528bfc612a6920dc5f9073d2525/src/main/java/com/stripe/net/RequestOptions.java#L103-L104

This is a big variation from the default timeouts in RequestOptions generally, declared here:
https://github.com/stripe/stripe-java/blob/aa9be6cf41aa1528bfc612a6920dc5f9073d2525/src/main/java/com/stripe/Stripe.java#L9-L10

This is a pretty large foot-gun in the library right now. If this builder is used, but connectTimeout and readTimeout are not explicitly set, you've arrived at an infinite timeout for requests to Stripe. 
https://github.com/stripe/stripe-java/blob/8aebffd7b3d9a9ad953efd4bdd62bf5daea2c623/src/main/java/com/stripe/net/LiveStripeResponseGetter.java#L215
https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#setConnectTimeout-int-

Any outage in networking to Stripe (or some types of outages of Stripe) can lead to cascading failures due to thread exhaustion of a service making use of the Stripe Java client in this way, which is the default. This is surprising behavior.

Straightforward proposed fix - default RequestOptionsBuilder connectTimeout and readTimeout to the typical Stripe default timeouts.

**Comment by brandur-stripe** [comment]
Thanks for the report Ben.

(I'm sure you'll have seen already, but CC @ob-stripe @rattrayalex-stripe just in case.)

**Comment by ob-stripe** [comment]
Hi @bpicolo, thanks for the report! This should be fixed in version 10.12.2.
