### ISSUE TITLE
Concern on 812 Pull request (https://github.com/stripe/stripe-java/pull/812)

### ISSUE THREAD

**Issue by Thilakeswar** [stripe/stripe-java#822]
Can anyone please explain more on this issue which has been fixed in this pull request - #812? Am using the stripe-java version [10.9.1](https://github.com/stripe/stripe-java/blob/878a60cb05014d7e1727b440ef8f3ef58a7d6a51/CHANGELOG.md#1091---2019-07-16) This NPE has been fixed only in the version [10.12.1](https://github.com/stripe/stripe-java/blob/878a60cb05014d7e1727b440ef8f3ef58a7d6a51/CHANGELOG.md#10121---2019-07-30) If I haven't upgraded to this version, will I face any issues?

**Comment by ob-stripe** [comment]
@Thilakeswar Only if you use the `getRawJsonObject()` method, either directly (which is very rarely necessary) or indirectly (typically by using a mapping or serialization library that uses reflection to call all getters, e.g. [modelmapper](http://modelmapper.org/)).

That said, it should always be safe to upgrade to a new minor or patch version, i.e. if you're on any 10.x version you can always safely upgrade to the latest 10.x.
