### ISSUE TITLE
Account.getLoginLinks() not matching documentation

### ISSUE THREAD

**Issue by TwoTenPvP** [stripe/stripe-java#823]
Previously, we used library version 7.0.0, when upgrading to 10.14.0 the getLoginLinks getter on the Account type is no longer accessible and/or found. It's still documented everywhere on the stripe documentation like this:

```java
Account account = Account.retrieve("acct_XXYYZZ", null);
account.getLoginLinks().create();
```

but this code does not compile because of the getter not being found. The only alternative I have found seems to be the static ``LoginLink.createOnAccount()`` but that has 3 parameters which are not covered by the docs, I suspect this is not intended.

I am unsure if this is an issue with the lib or with the docs.

**Comment by remi-stripe** [comment]
@TwoTenPvP Sorry about the confusion here. The right way to create a LoginLink is to do this:

```
login_link = LoginLink.createOnAccount("acct_123");
```

I'll get our docs fixed, thanks a lot for reporting!

**Comment by remi-stripe** [comment]
The docs have been updated, thanks for the flag!

**Comment by TwoTenPvP** [comment]
> The docs have been updated, thanks for the flag!

Still not seeing updated docs

**Comment by remi-stripe** [comment]
Thanks for the heads up. It looks like the docs reverted back to the wrong example so I'll get it fixed!

**Comment by NicholasBrooksTR** [comment]
FYI -- Looks like the Java example is still out of date in the Express docs:
https://stripe.com/docs/connect/integrate-express-dashboard#create-login-link
