### ISSUE TITLE
StripeException implements Serializable, but its stripeError field is not serializable

### ISSUE THREAD

**Issue by richardfearn** [stripe/stripe-java#832]
`StripeException` implements `Serializable`, but it has a `stripeError` field (of type `StripeError`) that is not serializable, and is not `transient`.

**Comment by ob-stripe** [comment]
Thanks for the report @richardfearn! We'll publish a fix soon.

**Comment by ob-stripe** [comment]
Fixed in 11.5.1. The `stripeError` field is now `transient`.

**Comment by richardfearn** [comment]
Thank you!
