### ISSUE TITLE
totalCount not populated in PaymentMethodCollection when listing a customer's payment methods

### ISSUE THREAD

**Issue by richardfearn** [stripe/stripe-java#837]
If I create a new customer with a payment method, and then list the payment methods for the new customer, the `PaymentMethodCollection` contains one payment method, but its `totalCount` field is `null`. I was expecting this to be 1.

A test program that demonstrates this is [attached](https://github.com/stripe/stripe-java/files/3565678/ListPaymentMethods.java.txt). The output is:

    Customer ID: cus_Fjg8mYgWed9NBU
    totalCount: null
    data.size: 1

This occurs with version 10.14.0 and 11.15.1.

**Comment by remi-stripe** [comment]
@richardfearn `total_count` has been actively deprecated for multiple years and we are not including it anymore in new lists such as for the PaymentMethod resource. You need to paginate to get a count of PaymentMethods though in your case you can just look that `has_more` is `false` and that the `data` array only has one element.

**Comment by richardfearn** [comment]
Ah, OK. I saw that `StripeCollection.count` and `getCount()` are [deprecated](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/StripeCollection.java#L60), but `totalCount` and `getTotalCount()` [are not](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/StripeCollection.java#L48-L49), so I thought that they ought to be populated.

Thanks!

**Comment by ob-stripe** [comment]
Thanks for reporting this @richardfearn. `totalCount` is now marked as deprecated in the latest version (11.6.1.).
