### ISSUE TITLE
API_VERSION = "2019-08-14" instead  "2019-09-09" in the new version (11.8.0) of the library

### ISSUE THREAD

**Issue by RobertBag** [stripe/stripe-java#843]
The com.stripe.Stripe class contains API_VERSION = "2019-08-14" instead of "2019-09-09" in the new version (11.8.0) of the library.

**Comment by RobertBag** [comment]
The event.getDataObjectDeserializer().getObject() method returns an empty java.util.Optional.

**Comment by ob-stripe** [comment]
Hi @RobertBag. We've just released stripe-java 12.0.0 which is pinned to the latest API version 2019-09-09.
