### ISSUE TITLE
test mode webhook pushing wrong data to me

### ISSUE THREAD

**Issue by JohnnyChenS** [stripe/stripe-java#845]
since yesterday i found the webhook in test mode push me the wrong event detail , customers upgrade their monthly subscriptions to yearly (currently i found this problem only occurred when customers update their subscription from monthly to yearly), and my code create an invoice to charge them immediately, in the past users should wait no more than one hour to see if the automatically charge is successful, but now stripe charge them immediately and push me the invoice.payment_succeeded event at the same time, but the content it push me mistaking the target product ,the yearly paid one, customer wants to upgrade to as the one he owned (the monthly paid one), and the whole order's amount price is negative, but it is correct on the stripe's dashboard. below is the content that stripe pushed to my server  and the event id is "evt_1FJXAXCcSMq81spvGuia6xpC" 

`{
    "request":
    {
        "id": "req_s6uxo0u9K9tvv8"
    },
    "data":
    {
        "object":
        {
            "id": "in_1FJXAWCcSMq81spvTzJ7idcK",
            "object": "invoice",
            "account_country": "CA",
            "account_name": "Tapcash Inc.",
            "amount_due": 0,
            "amount_paid": 0,
            "amount_remaining": 0,
            "attempt_count": 0,
            "attempted": true,
            "auto_advance": false,
            "billing": "charge_automatically",
            "billing_reason": "subscription_update",
            "closed": true,
            "collection_method": "charge_automatically",
            "created": 1568690156,
            "currency": "usd",
            "customer": "cus_FmFyLExbrKaQML",
            "customer_email": "gsgsl.us@tapcash.com.cn",
            "customer_tax_exempt": "none",
            "customer_tax_ids": [],
            "date": 1568690156,
            "default_tax_rates": [],
            "ending_balance": -35999,
            "finalized_at": 1568690156,
            "forgiven": false,
            "hosted_invoice_url": "https://pay.stripe.com/invoice/invst_jqrNATDm7pz4rnlLp3lJqH7Iht",
            "invoice_pdf": "https://pay.stripe.com/invoice/invst_jqrNATDm7pz4rnlLp3lJqH7Iht/pdf",
            "lines":
            {
                "object": "list",
                "data": [
                {
                    "id": "ii_1FJXAWCcSMq81spvFxNRK8us",
                    "object": "line_item",
                    "amount": -39899,
                    "currency": "usd",
                    "description": "Unused time on tool4seller - Professional Ad Analysis Package after 17 Sep 2019",
                    "discountable": false,
                    "invoice_item": "ii_1FJXAWCcSMq81spvFxNRK8us",
                    "livemode": false,
                    "metadata":
                    {},
                    "period":
                    {
                        "end": 1600225265,
                        "start": 1568690156
                    },
                    "plan":
                    {
                        "id": "plan_FmeHEF5O6oPcIV",
                        "object": "plan",
                        "active": true,
                        "amount": 39900,
                        "amount_decimal": "39900",
                        "billing_scheme": "per_unit",
                        "created": 1568105139,
                        "currency": "usd",
                        "interval": "day",
                        "interval_count": 365,
                        "livemode": false,
                        "metadata":
                        {},
                        "name": "tool4seller - Professional Ad Analysis Package",
                        "nickname": "365days",
                        "product": "prod_Fi7ddxsXBbyt1s",
                        "usage_type": "licensed"
                    },
                    "proration": true,
                    "quantity": 1,
                    "subscription": "sub_FpBFpGnRXzwcQK",
                    "subscription_item": "si_FpBFXNAq3xKqPI",
                    "tax_amounts": [],
                    "tax_rates": [],
                    "type": "invoiceitem"
                },
                {
                    "id": "sub_FpBFpGnRXzwcQK",
                    "object": "line_item",
                    "amount": 3900,
                    "currency": "usd",
                    "discountable": true,
                    "livemode": false,
                    "metadata":
                    {
                        "accountId": "127"
                    },
                    "period":
                    {
                        "end": 1571368556,
                        "start": 1568690156
                    },
                    "plan":
                    {
                        "id": "plan_FmFCKKeLOGjQXb",
                        "object": "plan",
                        "active": true,
                        "amount": 3900,
                        "amount_decimal": "3900",
                        "billing_scheme": "per_unit",
                        "created": 1568011876,
                        "currency": "usd",
                        "interval": "day",
                        "interval_count": 31,
                        "livemode": false,
                        "metadata":
                        {},
                        "name": "tool4seller - Advanced Ad Analysis Package",
                        "nickname": "31days",
                        "product": "prod_FmFCqsq0BUHGhA",
                        "usage_type": "licensed"
                    },
                    "proration": false,
                    "quantity": 1,
                    "subscription_item": "si_FpBXjwOTOPkaL5",
                    "tax_amounts": [],
                    "tax_rates": [],
                    "type": "subscription",
                    "unique_line_item_id": "sli_ba4e54f2d53a16"
                }],
                "has_more": false,
                "total_count": 2,
                "url": "/v1/invoices/in_1FJXAWCcSMq81spvTzJ7idcK/lines"
            },
            "livemode": false,
            "metadata":
            {},
            "number": "BB52A9D3-0053",
            "paid": true,
            "period_end": 1568690156,
            "period_start": 1568690156,
            "post_payment_credit_notes_amount": 0,
            "pre_payment_credit_notes_amount": 0,
            "starting_balance": 0,
            "status": "paid",
            "status_transitions":
            {
                "finalized_at": 1568690156,
                "paid_at": 1568690156
            },
            "subscription": "sub_FpBFpGnRXzwcQK",
            "subtotal": -35999,
            "total": -35999,
            "total_tax_amounts": []
        }
    },
    "livemode": false,
    "created": 1568690156,
    "id": "evt_1FJXAXCcSMq81spvGuia6xpC",
    "api_version": "2017-08-15",
    "type": "invoice.payment_succeeded",
    "pending_webhooks": 1,
    "object": "event"
}`

**Comment by remi-stripe** [comment]
@JohnnyChenS To me this looks like expected behaviour. When you move from monthly to yearly, it resets the billing cycle and charges them immediately.

I'd recommend contacting our support team to discuss this since it would not be a bug in the library. You can contact them here: https://support.stripe.com/contact

**Comment by JohnnyChenS** [comment]
thank you, your support team have helped me solved the problem. thx
