### ISSUE TITLE
Getting total count for collections

### ISSUE THREAD

**Issue by totof3110** [stripe/stripe-java#846]
Hello,

We noticed that https://github.com/stripe/stripe-java/pull/839 was deprecating `com.stripe.model.StripeCollection.getTotalCount()`, advising to use "pagination parameters". Looking at the code I don't see where do get the total count from other than this method. Can you advise?

Thanks!

**Comment by remi-stripe** [comment]
@totof3110 It is not possible to get the total count anymore. You need to paginate through the results to get the total on your end instead.

Calculating a total is costly, especially on large collection, causing the API to take longer than usual to respond so this feature was marked as deprecated years ago.

**Comment by totof3110** [comment]
Bummer... Thanks for the quick reply.
