### ISSUE TITLE
Deployment issue with version 13.x

### ISSUE THREAD

**Issue by Flo354** [stripe/stripe-java#856]
Hi there,

It seems to me that there is a deployment issue with the releases of the version 13.0.0 and 13.1.0.
Version 13.1.0 is not available in maven, and the two versions does not have a proper release in "release" tab.

**Comment by Flo354** [comment]
Thanks!

**Comment by ob-stripe** [comment]
Quick update: Maven Central is still having trouble (https://status.maven.org/) so at this time v13.1.0 may still only be downloaded directly from GitHub.

**Comment by ob-stripe** [comment]
Maven seems to have recovered and I was finally able to push v13.1.0. It should be available on Maven Central within a day.

Closing, but feel free to reply!
