### ISSUE TITLE
Access to Value of amountToCapture for Application

### ISSUE THREAD

**Issue by eaglerainbow** [stripe/stripe-java#859]
How should a consuming application retrieve the `amountToCapture` as in

https://github.com/stripe/stripe-java/blob/f773212886e7da424e4d8ed7eb9c34e905646c5f/src/main/java/com/stripe/param/PaymentIntentCaptureParams.java#L17

There is apparently no getter method, and `friend` is only visible within the same package.

**Comment by eaglerainbow** [comment]
I have found the workaround

```
piCaptureParams.toMap().get("amount_to_capture")
``` 

but this is super-ugly, as it only returns `Object`.

**Comment by remi-stripe** [comment]
@eaglerainbow Can you say a bit more about your current integration? In which case do you set `amount_to_capture` as a parameter and then later need to access the value you set yourself but from the params instead of from your own integration?

**Comment by eaglerainbow** [comment]
@remi-stripe: Sure...
I have here the situation that I want to capture a PaymentIntent with an amount authorized before. However, the logic to determine the amount requested to be captured is rather complex and is hidden in a method that returns me an instance of `PaymentIntentCaptureParams`. In case of an error raised (exception was raised), I'd like to formulate an error message with something like `The amount of xxx.yy USD could not be captured due to ...` (error handling is a little more complex than this, but this is it in a nutshell).
I don't want to call the amount calculation logic again, but I'd like to say in the error message exactly what was requested to be captured. Unfortunately, it's rather hard to get to that information right now.

**Comment by remi-stripe** [comment]
@eaglerainbow I see. I do feel like extracting it from the parameters, even with a helper, seems a bit surprising when your own application should know what it's trying to capture/do.

We might add getters in the future though it's not something we have planned in the near future at least. But it's a similar feature request as https://github.com/stripe/stripe-java/issues/811 that we tagged as future for now. I'm going to close this one in favour of the other one and you can follow along there but in the meantime accessing the map and then fetching the param from it is likely the easiest though I agree it feels brittle.

**Comment by ob-stripe** [comment]
Hi @eaglerainbow. We just added getter methods to all parameter classes in stripe-java 13.2.0, so you can now do e.g:

```java
Long amountToCapture = paymentIntentCaptureParams.getAmountToCapture();
```
