### ISSUE TITLE
Global Timeout not used.

### ISSUE THREAD

**Issue by luxlabs** [stripe/stripe-java#909]
Class `RequestOptionsBuilder` in the constructor 
`public RequestOptionsBuilder() {
this.apiKey = Stripe.apiKey;
            this.clientId = Stripe.clientId;
            this.connectTimeout = 30000;
            this.readTimeout = 80000;
        }`
should read set connectTimeout and readTimeout using the get methods (`getConnectTimeout` and `getReadTimeout`) on `Stripe` class

**Comment by ob-stripe** [comment]
Thanks for the report @luxlabs. We will release a fix soon.

**Comment by remi-stripe** [comment]
This has been fixed in 16.0.0
