### ISSUE TITLE
Upcoming Invoices Improvement

### ISSUE THREAD

**Issue by hopperd** [stripe/stripe-java#920]
We have an integration of Stripe into our platform that will creating upcoming invoices for customers as transactions happen in our system. When trying to fetch upcoming invoices for a customer that may not have any upcoming invoices currently the response back is an error.

`{
  "error": {
    "code": "invoice_upcoming_none",
    "doc_url": "https://stripe.com/docs/error-codes/invoice-upcoming-none",
    "message": "No upcoming invoices for customer: cus_abc",
    "type": "invalid_request_error"
  }
}`

This makes flow control a little trickier to handle and also produce false error rates/counts in the stripe API section. I would propose that returning either 404 which can be more easily handled by flow control properly marking that there is nothing found, or returning a result that is just an empty array.

**Comment by remi-stripe** [comment]
@hopperd Thanks a lot for the feedback! I do agree that handling that one can be a bit confusing today as it's different from other endpoints though I'm not sure the 404 would make this better in this case.

I'm going to raise this feedback with our engineering team internally but I encourage you to reach out to our support team: https://support.stripe.com/contact?email=true As the feedback is more about the API and not a feature request specific to the stripe-java I'm going to close this out. If we did change the API then stripe-java would reflect those changes.
