### ISSUE TITLE
Make method calls non-static

### ISSUE THREAD

**Issue by benmccann** [stripe/stripe-java#93]
The fact that the API is all static makes it hard to inject mocks for testing our application

**Comment by chrylis** [comment]
+1 for a cleaner 2.0. The static setup like this is routine in JavaScript, but it causes no end of headaches (container management, configuration, testing) in Java.

**Comment by pandacalculus** [comment]
+1 - we've also hit this when attempting to write tests that mock out the actual calls to Stripe. Have to jump thru some ugly hoops to get the job done.

**Comment by lnhrdt** [comment]
+1 to echo everyone else. It's a difficult API to have to work with in a TDD environment.

**Comment by thomasseaton** [comment]
To anyone coming across this when searching for a solution, you can mock a request by doing:
`
StripeResponseGetter stripeMock = mock(StripeResponseGetter.class);
APIResource.setStripeResponseGetter(stripeMock);
`
