### ISSUE TITLE
No version after 16.6.0

### ISSUE THREAD

**Issue by Flo354** [stripe/stripe-java#941]
Hi there,

Just to let you know in case you didn't see this, the version 16.7.0, 16.8.0 and 17.0.0 are not published in maven.

When will they be released?

Thanks,

**Comment by ob-stripe** [comment]
Hi @Flo354, thanks for the report. We think this might be an issue on Maven Central's end: recent versions were successfully uploaded to them (you can see them at https://repo1.maven.org/maven2/com/stripe/stripe-java/) yet they don't appear on the website at https://mvnrepository.com/artifact/com.stripe/stripe-java.

We will investigate and post here as soon as we have an update.

**Comment by ob-stripe** [comment]
Looks like 17.0.0 is now visible at https://mvnrepository.com/artifact/com.stripe/stripe-java, but not 16.7.0 or 16.8.0 🤔

**Comment by Flo354** [comment]
Hi,

They are now all visible. Seems you were right. It was only an issue from
maven.

Thanks,


Le ven. 17 janv. 2020 à 00:44, Olivier Bellone <notifications@github.com> a
écrit :

**Comment by ob-stripe** [comment]
👍 Thanks @Flo354!
