### ISSUE TITLE
Creation of an External Account does not follow a general pattern

### ISSUE THREAD

**Issue by lukaszwelnicki** [stripe/stripe-java#945]
**API version: 17.1.0**

There are two ways that an External (bank) Account could be created for a particular Account:
1. Create the External Account during the Account creation itself:
`AccountCreateParams accountCreateParams = AccountCreateParams.builder()
				.setExternalAccount("ext_acc_token")
				.build();
Account.create(accountCreateParams);`
the `setExternalAccount(...)` method accepts either a String representing a token of an existing External Account, or a String representing a dictionary of parameters described in the documentation of External Account creation (account_number, currency, object, etc.). It would be great if this method accepted an object of type representing the actual ExternalAccount, which also would implement the builder pattern the same way as many other types.

2. Create the External Account using a reference to an existing Account:
`account.getExternalAccounts().create(params);`
In this case, the params argument could be either of type `Map<String, Object>` or `ExternalAccountCollectionCreateParams`. In the case of the latter, the builder object lacks the methods representing actual fields (account_number, currency, object, etc.). It would be great if it could follow a pattern of many different types, like `PersonCollectionCreateParams`. I guess this issue is somehow associated to the one described in the first point.

Best Regards,
Łukasz

**Comment by remi-stripe** [comment]
@lukaszwelnicki Thanks for reaching out! Today, we don't want to support passing raw bank account or card details in the API that way for security reasons (and PCI for cards). This is usually bad practice, and we actively block it for cards by default.

What you're describing can work but we actively discourage this. Instead, you really should create a bank account or card token client-side with Stripe.js securely and then use the token server-side instead.

Does that make sense?

**Comment by lukaszwelnicki** [comment]
@remi-stripe Thank you for the response. I totally understand this reasoning and I will follow your guidelines. I will close this issue now.

Best Regards,
Łukasz
