### ISSUE TITLE
please add support for serializing Stripe objects back to JSON

### ISSUE THREAD

**Issue by vitezg** [stripe/stripe-java#96]
It would be great to have official support for serializing the Stripe object back to JSON format.
The use case is saving the objects to the disk for later processing / caching.

Serializing and then deserializing almost works, however at least when deserializing an Event object EventDataDeserializer.java will throw a NullPointerException on line 105, because the data.object.object attribute does not get created. 

Example code:

String json=APIResource.GSON.toJson(Event.retrieve("..."));
// the json string is now missing the data.object.object attribute, which 
// will result in an NPE
Event restored=APIResource.GSON.fromJson(json, Event.class);

**Comment by nicksellen** [comment]
I had a similar issue, "source" field inside a charge was being serialized as an empty object.

I created my own GSON objects based on the stripe ones and so far it's working:

    private static final Gson GSON_TO = new GsonBuilder()
        .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
        .registerTypeAdapter(EventData.class, new EventDataDeserializer())
        .registerTypeAdapter(ChargeRefundCollection.class, new ChargeRefundCollectionDeserializer())
        .registerTypeAdapter(FeeRefundCollection.class, new FeeRefundCollectionDeserializer())
        .registerTypeAdapter(StripeRawJsonObject.class, new StripeRawJsonObjectDeserializer())
        .registerTypeAdapter(Dispute.class, new DisputeDataDeserializer())
      .create();
    
    private static final Gson GSON_FROM = new GsonBuilder()
        .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
        .registerTypeAdapter(EventData.class, new EventDataDeserializer())
        .registerTypeAdapter(ChargeRefundCollection.class, new ChargeRefundCollectionDeserializer())
        .registerTypeAdapter(FeeRefundCollection.class, new FeeRefundCollectionDeserializer())
        .registerTypeAdapter(StripeRawJsonObject.class, new StripeRawJsonObjectDeserializer())
        .registerTypeAdapter(Dispute.class, new DisputeDataDeserializer())
        .registerTypeAdapter(PaymentSource.class, new PaymentSourceDeserializer())
      .create();

**Comment by nicksellen** [comment]
and the methods to call them:

    public static String toJson(StripeObject obj) {
      return GSON_TO.toJson(obj);
    }
    
    public static <T extends StripeObject> T fromJson(String json, Class<T> klass) {
      return GSON_FROM.fromJson(json, klass);
    }

**Comment by nicksellen** [comment]
... next error is with the Transfer object. The Transfer json from stripe api (latest version as of now) includes a "bank_account" field. Transfer.java expects "account" though.

I created this extra class that inherits from it which gives Gson the expected field to bind to:

    public static class TransferWithBankAccount extends Transfer {

        BankAccount bankAccount;
        
        public BankAccount getBankAccount() {
          if (bankAccount != null) {
            return bankAccount;
          }
          return getAccount();
        }

        public void setBankAccount(BankAccount account) {
          bankAccount = account;
          setAccount(account);
        }
        
      }

It would be nice to have this work properly though :)

**Comment by kyleconroy** [comment]
I've added this to the roadmap for version two of stripe-java.

**Comment by andrhamm** [comment]
:+1:

**Comment by pugnascotia** [comment]
I hit this today when trying to write unit tests for a webhook processor - it would be great if serialisation / deserialisation worked generally.

**Comment by ob-stripe** [comment]
Just realized this was handled in #339, which was released in 3.7.0.
