### ISSUE TITLE
3D Secure subscriptions payment fails

### ISSUE THREAD

**Issue by FV-Valraiso** [stripe/stripe-java#962]
I just updated to version 17.8.0.
Since, all my payments in test mode on subscriptions using 3D Secure v1 & v2 fails.
I tested several 3D Secure test card from https://stripe.com/docs/testing I have the problem with all of them.

For a charges or using cards without 3D Secure it works fine.
I checked all changelogs and the migration guide I didn't find anything that could explain.

**Comment by remi-stripe** [comment]
@FV-Valraiso This wouldn't be a bug with the stripe-java library itself. You should read [this doc](https://stripe.com/docs/billing/migration/strong-customer-authentication) and follow the recommendations.

If you have any follow-up questions, you should instead contact our support team directly https://support.stripe.com/contact. You can also talk to Stripe developers and users alike on IRC on Freenode in the #stripe channel if you have any specific questions
