### ISSUE TITLE
customerBalanceTransaction.create() is missing?

### ISSUE THREAD

**Issue by tuddman** [stripe/stripe-java#982]
Am I missing something, or is the `customerBalanceTransaction.create()` function missing?

cannot find any `create` method in the [CustomerBalanceTransaction class](
https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/CustomerBalanceTransaction.java)

[the docs](https://stripe.com/docs/api/customer_balance_transactions/create?lang=java)  list this as the example to create a customer balance transaction:

```
Customer customer =
  Customer.retrieve("cus_abc123...");

Map<String, Object> params = new HashMap<>();
params.put("amount", -500);
params.put("currency", "usd");

BalanceTransaction balanceTransaction =
  customer.getBalanceTransactions().create(
    params
  );
```

first, I can call `customer.balanceTransactions() works` but `customer.getBalanceTransactions()` does not.

there is no create method to actually create a customer balance transaction?

using `stripe-java v18.4.0`

**Comment by remi-stripe** [comment]
@tuddman Thanks for the report. The `create()` method today is on the class `CustomerBalanceTransactionCollection` [here](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/CustomerBalanceTransactionCollection.java#L116)

The docs are incorrect and I'll make sure we fix them, the `customer.balanceTransactions().create()` is the correct code.
