### ISSUE TITLE
List all Cards by Customer

### ISSUE THREAD

**Issue by merihsakarya** [stripe/stripe-java#997]
**Java SDK Version**
**1.8**

**API Version**
**18.12.0**

I am trying to list all cards by customer but 'customer.getSources().list(params)' returns PaymentSourceCollection object and can not cast to Card object.

https://stripe.com/docs/api/cards/list?lang=java

```
Stripe.apiKey = "sk_test_123";

Customer customer = Customer.retrieve("cus_ABC");
Map<String, Object> params = new HashMap<>();
params.put("object", "card");
params.put("limit", 3);

CardCollection cards = (Card) customer.getSources().list(params);
```

Thanks

**Comment by remi-stripe** [comment]
@merihsakarya What you need to do here is iterate over the `PaymentSourceCollection` and then cast each element to a `Card` object instead

```
Customer customer = Customer.retrieve("cus_ABC");

PaymentSourceCollectionListParams params =
  PaymentSourceCollectionListParams.builder()
    .setObject("card")
    .build();

PaymentSourceCollection collection = customer.getSources().list(params);
Iterable<PaymentSource> it = collection.autoPagingIterable();
for (PaymentSource paymentSource : it) {
  Card card = (Card) paymentSource;
  System.out.println(card.getId());
  System.out.println(card.getLast4());
}
```

To simplify though I highly recommend using the `PaymentMethod` [API](https://stripe.com/docs/api/payment_methods/object) instead. It will make your life easier for cards and all existing card objects (card_12345) will work as PaymentMethods automatically.

Also, I redacted your API key above but you should make sure to roll it now even if just Test mode as anyone could have seen it!
